- Cargo.lock
- Cargo.toml
- src/inspect.rs
- src/invoke.rs
- src/main.rs
Add inspect sub-command that displays information about the wasm file, initially just the wasm funcctions.
```
❯ stellar-contract-cli inspect --file target/wasm32-unknown-unknown/release/example_add_i64.wasm
Functions:
• add (val, val) -> (res)
```
For developer interactions for understanding what is in a wasm file.
This is just the start of functionality and other functionality can be added.
> Add inspect sub-command

- src/main.rs
Remove 'ok' from output when command succeeds.
Frivolous.
[TODO or N/A]
> Remove 'ok' from output

- Cargo.lock
- Cargo.toml
- src/inspect.rs
Add contract spec to inspect subcommand.
For debugging the contract spec in contracts. Eventually it can be pretty formatted.
[TODO or N/A]
> Add contract spec to inspect subcommand

- src/main.rs
Print full raw error.
The errors story for the CLI is not particularly organized and by printing the error we at least get full visibility into what error is happening at this point, even if the output isn't pretty.
Should really circle back on making the error output nicer. At least making it just a human readable well formed string.
> Print full raw error

- Makefile
Add install target to Makefile.
For convenience while developing with other things, it is convenient to be able to make install.
[TODO or N/A]
> Add install target to Makefile

- Cargo.lock
- Cargo.toml
- src/inspect.rs
- src/strval.rs
Decode contract spec XDR in WASM files.
As a first step so that the CLI can display the contract spec in a human readable format to the user. Near term the same logic will be used for generating client code.
Close https://github.com/stellar/stellar-contract-cli/issues/6
Dependent on https://github.com/stellar/rs-stellar-xdr/pull/76
Related to https://github.com/stellar/rs-stellar-contract-sdk/pull/140
[TODO or N/A]
> Decode contract spec in inspect

- Cargo.lock
- Cargo.toml
- src/invoke.rs
- src/strval.rs
Uses a file to store xdr LedgerKey-LedgerEntry pairs.
There are some TODO's in here that we should address next. I can also remove them and add issues instead.
This PR dumps xdr for now, but it's also possible to output JSON using Serde. I was able to get JSON working without without specifying custom serializers, but the output wasn't friendly. We would definitely  benefit from spending some time specializing some of the XDR types with Serde.  I have included the generic Serde output from the experiment I did, with ledger key on the first line, and the ledger entry on the second -
```
{"ContractData":{"contract_id":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"key":{"Symbol":[97,112]}}}
{"last_modified_ledger_seq":0,"data":{"ContractData":{"contract_id":[0,0,0,0,0,0,0 …
```
> Read and write xdr to file for persistent storage

- .github/workflows/rust.yml
- Makefile
- rust-toolchain.toml
Use the toolchain file in GitHub Actions.
There's no reason to respecify values that are included already in the toolchain file since the action will load them from there.
[TODO or N/A]
> Use the toolchain file in GitHub CI

- src/inspect.rs
Output env interface version in inspect sub-command.
For debugging and inspecting contracts.
Close https://github.com/stellar/rs-stellar-contract-sdk/issues/142
[TODO or N/A]
> Output env interface version in inspect sub-command

- src/inspect.rs
Change name of env meta to Env Meta for the line that prints saying there is no env meta.
It's env meta.
[TODO or N/A]
> Fix name of env meta when not provided

- src/inspect.rs
- src/invoke.rs
- src/main.rs
Add help messages to options.
To make it possible for new users to understand what the different CLI options do.
Close https://github.com/stellar/stellar-contract-cli/issues/34
[TODO or N/A]
> Add help messages to options

- Cargo.lock
- Cargo.toml
- README.md
- src/deploy.rs
- src/invoke.rs
- src/main.rs
- src/snapshot.rs
- src/utils.rs
Resolves #29 and related to #22.
The two new commands take a JSON SCVec as an argument. I haven't updated how arguments are passed to the existing command that invokes WASM directly, but wanted to get input on this change before moving forward.
The user experience also isn't great, but I think we can make some improvements. The user needs to construct the JSON, which isn't really feasible by hand. For example, I tested this by using a rust test case and printed out the arguments that I wanted.
> Allow the option use the call and create contract host functions

- .gitignore
- src/deploy.rs
- src/invoke.rs
- src/snapshot.rs
Auto-create `.soroban` dir when needed, and put `ledger.json` in there.
So it is easy to `.gitignore` all the soroban cli files. (If we add more)
Default path may not work on windows?
> Put ledger.json -> .soroban/ledger.json to keep all cli local files contained

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- src/contractspec.rs
- src/invoke.rs
- src/jsonrpc.rs
- src/main.rs
- src/serve.rs
Add `cli serve` command
It serves a jsonrpc API on `http://localhost:8080/rpc` which can be called with something like:
```sh
$ curl -v
-X POST
--header "content-type: application/json"
http://localhost:8080/rpc
--data-binary '{"jsonrpc":"2.0", "id":1, "method":"call", "params":{"id": "1", "func":"add", "args":[5, 3]}}'
```
This call command is similar to doing a cli invoke with:
```sh
$ cli invoke --contract 1 --fn add --arg 5 --arg 3
``` 
This is just a first pass at what the preflight request could look like. But it would need to include much more data in the response, so this will definitely change.
Fixes https://github.com/stellar/soroban-cli/issues/58
In particular, the idea is to let you run your dapp locally against the sandbox (The dev would do this separately). The API from `cli …
> cli serve, first pass at sandbox preflights

- Cargo.lock
- Cargo.toml
- src/completion.rs
- src/main.rs
This commit adds a `completion` subcommand that will generate autocomplete code for shells supported by `clap_complete`.
To enable users to enter commands and arguments more quickly and explore the CLI.
N/A
Build the CLI using `cargo build` then you should see the `completion` command after running `cargo run`. Running `cargo run completion --help` will display more detailed usage instructions.
To test the functionality run (for bash): `source <(cargo run completion bash)` and tab-completion for `soroban-cli` should be enabled in the current shell.
I've also been using an alias `sb` which can use completions by running `complete -o default -F _soroban-cli sb`.
If you use the suggested installation instructions in the `--help` completions should stay up-to-date with the `soroban-cli` if a …
> Add shell autocomplete using clap_complete crate

- README.md
- src/main.rs
Add links to Soroban Docs and remove SDF from help output. Also add `--locked` to install command.
Having `Stellar Development Foundation <info@stellar.org>` in the output of the CLIs output isn't particularly helpful. If someone is having problems we don't want them to email `info@stellar.org`. Instead we should connect people with the docs.
It's relatively important to use `--locked` when installing, otherwise the lock file will be ignored and any just released software could be installed.
> Add links to Soroban Docs

- src/invoke.rs
- src/utils.rs
Update the storage of contract code in ledger.json to use the new ScContractCode XDR type.
The format for storing contracts was changed in the ledger, but the CLI has not yet been updated to match it, but is erroring when invoking contracts.
More reinforcement for why we need to add more tests to the CLI.
> Fix contract invoke

- Cargo.lock
- Cargo.toml
- src/inspect.rs
- src/invoke.rs
- src/serve.rs
Add names to input types in spec functions.
When defining an interface it is helpful to give names to the arguments of the functions so a user of the interface knows what to put in the arguments. This is especially helpful when multiple arguments have the same type, since a name is the only thing that distinguishes them.
Close stellar/rs-soroban-sdk#434
> Add names to input types in spec functions

- Cargo.lock
- Cargo.toml
- src/inspect.rs
Use a parser independent of Vm/Host for inspecting wasm files.
@graydon pointed out that we can't inspect files that are not compatible with the current Vm, which makes debugging when we have old files really difficult. The inspect command should work really with any file over time. We're using the `wasmparser` crate to parse wasm files in the SDK macros, using it here is simple. Maybe at some point we can consolidate this logic into a wasm utilities crate, although it feels a little premature to do so right now.
Close https://github.com/stellar/rs-soroban-sdk/issues/447
> Use a parser independent of Vm/Host for inspecting wasm files

- .github/workflows/rust.yml
Add ci job that checks if rust-analyzer can parse project.
A couple times now we have done things that are technically allowed in Rust but are not supported by rust-analyzer. Everytime we've walked the change back because rust-analyzer compatibility is important for developer productivity. Let's prevent these things from happening by checking if rust-analyzer can parse the project.
Same as https://github.com/stellar/rs-soroban-env/pull/371.
> Check if rust-analyzer can parse project

- Cargo.lock
- Cargo.toml
Add BytesN support to spec.
So that functions that accept BytesN can be generated as such.
Close stellar/stellar-xdr-next#15
> Add BytesN support to spec

- Cargo.lock
- Cargo.toml
- src/gen.rs
There is an existing `gen` command which currently generates rust bindings for a soroban smart contract. This PR adds an option to generate a JSON representation for a soroban smart contract spec.
Fixes https://github.com/stellar/soroban-cli/issues/56
[N/A]
> Add json output option for gen command

- src/invoke.rs
- src/main.rs
- src/snapshot.rs
Improve the error reporting of the `invoke` subcommand.
We used to print the internal (Debug) representation of the error data structures, which is not very helpful for the end user. 
We still need to implement the same for the other subcommands.
Comment for reviewers: it seems like creating a type with every possible error is really verbose, which makes me think it may not be very idiomatic.
Coming from Golang I was tempted to create errors from strings, but maybe this is just the price to pay in order to have structured errors?
> Improve invoke error reporting

- src/invoke.rs
Change the error message for when the wasm file has a read error to output the name of the wasm file instead of the ledger file.
It is the wasm file that has the issue, so we should include it in the error message rather than the ledger file.
> Fix wasm file not found error

- src/invoke.rs
Add a print statement at the end to print out the `events` from `host`.  cc @sisuresh 
To make the contract event example more meaningful. It's much better to show the event being printed than describing it as part of the host that can be retrieved. 
The print relies on the `Debug` trait of `xdr::ContractEvent`, which isn't pretty. We might want to add the proper `Display` impl of it at the `xdrgen` later.
> Print event at the end of invocation

- src/strval.rs
Parse BytesN same as Bytes.
BytesN were added as a type to the spec. They are the same as Bytes, so can be parsed the same.
> Fix BytesN strvals

- src/strval.rs
- src/utils.rs
Add support for hex strvals to Bytes/BytesN.
So that people can type bytes as hex in addition to the existing formats of G strkeys and JSON number arrays.
> Add support for hex strvals to Bytes/BytesN

- src/read.rs
Default to string output in read subcommand.
Convenience.
> Default to string output in read subcommand

- src/strval.rs
Parse values destined for a u64 argument as an Object U64 instead of as a u63.
u64 values should be parsed as a u64 object, not a u63 value.
Close #117
> Fix strval u64 parsing

- Cargo.lock
- Cargo.toml
- src/deploy.rs
- src/invoke.rs
- src/read.rs
- src/serve.rs
- src/snapshot.rs
Resolves #116.
1. The contents of `LedgerInfo` are stored in `ledger.json`.
2. `timestamp` and `sequence_number` are incremented on `invoke` and `serve`.
3. The only way to update the `LedgerInfo` fields at the moment is to update the values at the end of `ledger.json` (Ex. `}},"ext":"v0"}]],"protocolVersion":19,"sequenceNumber":4,"timestamp":12,"networkId":[0]}`. I can add a `set_ledger_Info` command, but wanted to get input before I went that route.
> Set and store LedgerInfo

- src/invoke.rs
A simple fix for the vm-holds-a-reference-to-host issue introduced with the recent wasmi upgrade
> Forget vm before finishing host

- src/invoke.rs
Reverts stellar/soroban-cli#131
Adding in the forget didn't seem to fix the problem.
> Revert "Forget vm before finishing host"

- src/invoke.rs
The VM was holding a reference to the host. Using a dedicated scope for the VM (`invoke_function()`) releases it and the internal host reference.
> invoke: Ensure all references to the host are released before `try_finish()` 

- src/invoke.rs
Put the `Event #n:` prefix of event logs onto the same line as the event they relate to.
They are currently printing on the previous events line because the new line is in the wrong place.
Close #138
> Fix output logs of events

- src/serve.rs
Have CLI serve accept the client headers from js-soroban-sdk.
So that js-soroban-sdk can talk to the local sandbox via cli serve.
[TODO or N/A]
> Add js sdk client headers through cors

- Cargo.lock
- Cargo.toml
- src/invoke.rs
Add option for choosing which account invoke happens as.
So it's possible to choose which account is sending the invocation.
Close https://github.com/stellar/soroban-cli/issues/153
> Add option for choosing which account invoke happens as

- Cargo.lock
- Cargo.toml
- src/invoke.rs
- src/read.rs
Change the read subcommand so that it can be given just a contract ID and it will output all the data stored.
While I've been testing invoker functionality it's easier to just look at a contracts data as a whole rather than individual records.
> Support getting all data for contract with read command

- src/serve.rs
When a transaction is received via sendTransaction or simulateTransaction, read out the source account and use it as the source account of the host when invoking the transaction.
To add support for using the source account as msg.sender style auth.
Close https://github.com/stellar/soroban-cli/issues/158
> Add source account support to serve simulate/sendTransaction

- Cargo.lock
- Cargo.toml
- src/deploy.rs
- src/main.rs
Allow deploying contract to remote RPC server instead of local sandbox
#41 
WIP
> Deploy contract to RPC server

- src/deploy.rs
Allow setting private key from environment variable `PRIVATE_STRKEY`
```
--private-strkey <PRIVATE_STRKEY>
Private key to sign the transaction sent to the rpc server [env: PRIVATE_STRKEY=]
```
Security 
N/A
> deploy: Allow setting private key from env variable

- src/deploy.rs
Update deploy subcommand so that when it's used against an RPC server uses `create_contract_from_source()` instead of `create_contract_from_ed25519()`
Also, print the contract ID once created.
I used this CPP test as a reference: https://github.com/stellar/stellar-core/blob/2dccaae1ec9db8e82580bc5e7b84d404d1836f3c/src/transactions/test/InvokeHostFunctionTests.cpp#L135
#152 
I haven't really been able to test this end-to-end against an RPC server because `soroban-cli serve` still only seems to support `HostFunction::InvokeContract`
> Update deploy subcommand to use `create_contract_from_source()`

- src/deploy.rs
Rename private key to secret key
For consistency with our other UX experiences when discussing keys.
Close #169
> Rename private key to secret key

- src/serve.rs
Log errors to stderr in serve
It's impossible to know what caused a transaction to fail without seeing the contents of the error. While there might be nicer things for us to do, simply logging the error to stderr will go a long way for a developer running serve locally in understanding what happened.
> Log errors to stderr in serve

- Cargo.toml
- src/main.rs
Rename the binary that gets installed when installing `soroban-cli`, from `soroban-cli` to `soroban`.
In a conversation with @tomerweller last week we were discussing the long name of this tool, and he suggested simply `soroban`. I think it works.
There may be other short names we may want to consider, but this is as short as we can go without losing any meaning.
> Rename soroban-cli to soroban

- Cargo.lock
- Cargo.toml
- src/token/create.rs
Update the sdk to 864a309b.
So we can build/deploy/invoke a working contract without environment version errors in https://github.com/stellar/soroban-example-dapp/pull/20
[TODO or N/A]
> Update the sdk to 864a309b

- src/deploy.rs
Allow user to specify custom salt when deploying to remote rpc server, via:
```sh
$ soroban deploy \
--wasm target/wasm32-unknown-unknown/release/soroban_hello_world_contract.wasm \
--rpc-server-url http://localhost:8000/soroban/rpc \
--secret-key "$SECRET_KEY" \
--network-passphrase "$NETWORK_PASSPHRASE" \
--salt 0
Contract ID: 1f3eb7b8dc051d6aa46db5454588a142c671a0cdcdb36a2f754d9675a64bf613
```
It means that the contract will have a deterministic ID, so it will fail if it is already deployed.
[TODO or N/A]
> Allow user to specify custom salt when deploying to remote rpc server

- src/deploy.rs
- src/invoke.rs
- src/main.rs
- src/rpc/mod.rs
- src/token/create.rs
- src/token/wrap.rs
- src/utils.rs
Allow invoking a contract through a remote RPC server (i.e. from a real network) instead of local sandbox
Note that, as `getContractData` is yet to be implemented by the RPC server, it is allowed to provide the contract through the `--wasm` flag. We should probably remove this in the future.
Also:
* refactor transaction signing
* It doesn't yet print the costs or the invocation results (let's do that later since I want to unblock end to end testing)
* this requires https://github.com/stellar/go/pull/4621
> Invoke contract from RPC server

- README.md
Change example binary name
In the Cargo.toml the binary is given the shorter name so when installed is the one added to your path.
N/A
> Fix binary name in instructions in README

- src/invoke.rs
- src/rpc/mod.rs
Print result when using an RPC Server
You really want to see the host function invocation result
Needs a change on the RPC Server so that it conforms with the agreed `getTransactionStatus` spec https://stellarorg.atlassian.net/wiki/spaces/PJC/pages/4402151440/soroban-rpc+API+Docs#getTransactionStatus-(Meridian-or-use-Horizon) (CC @tamirms )
> invoke: Print result when using an RPC Server

- Cargo.toml
- build.rs
- src/version.rs
Add git sha to version information.
So that we know if something is a development version or not, and which version exactly.
> Add git sha to version information

- src/token/create.rs
- Add the contractCode ledger entry to the token init op footprint.
- Fix type of the Admin & Metadata footprint entries
- Fixes https://github.com/stellar/go/issues/4627
I fixed this by getting the TxEnvelope from horizon, and running `simulateTransaction` with it. Then used laboratory to compare the submitted footprint with the simulated one.
> Add contractCode to token init footprint

- src/deploy.rs
If `--id` is not specified when deploying a contract to the sandbox, we can generate a random one.
Makes the sandbox closer to a real network behaviour.
Does not check for existing contract id conflict.
> Make sandbox deploy contract id optional

- src/invoke.rs
- src/serve.rs
- src/utils.rs
Output the ledger footprint when invoking as JSON.
To provide some access, albeit limited, to finding out what footprint is required for different invocations.
Maybe make it easier to debug some situations like https://github.com/stellar/soroban-cli/pull/201.
In terms of what format to output it? I considered XDR, Rust values, and JSON. None are great because of how binaries and contract IDs get formatted, so I just picked JSON. We really need to improve our formatting of these values.
> Output the ledger footprint when invoking

- src/invoke.rs
Now that the Go RPC Server supports `getContractData` ( https://github.com/stellar/go/pull/4652 ), we can enforce it when running invoke.
This means that `--wasm` won't be allowed when running `soroban invoke --rpc-url foo`
Also, it fixes the expected contract code type.
Allowing `soroban invoke --rpc-url foo --wasm bar` was just a workaround 
N/A
> invoke: Fix (and enforce) getContractData invocation

- src/invoke.rs
Add back ability to use --wasm in remote invoke.
It was removed in https://github.com/stellar/soroban-cli/pull/205, but we don't need to remove it.
The diff of #205 and #206 combined becomes:
```diff
--- a/src/invoke.rs
+++ b/src/invoke.rs
@@ -5,8 +5,8 @@ use clap::Parser;
use hex::FromHexError;
use soroban_env_host::xdr::{
InvokeHostFunctionOp, LedgerFootprint, Memo, MuxedAccount, Operation, OperationBody,
-    Preconditions, ScStatic, ScVec, SequenceNumber, Transaction, TransactionEnvelope,
-    TransactionExt, VecM,
+    Preconditions, ScContractCode, ScStatic, ScVec, SequenceNumber, Transaction,
+    TransactionEnvelope, TransactionExt, VecM,
};
use soroban_env_host::{
budget::{Budget, CostType},
@@ -42,7 +42,7 @@ pub struct Cmd {
)]
account_id: StrkeyPublicKeyEd25519,
-    /// WASM …
```
> Add back ability to use --wasm in remote invoke

- src/deploy.rs
- src/invoke.rs
- src/main.rs
- src/read.rs
- src/serve.rs
- src/token/create.rs
- src/token/wrap.rs
Group sandbox and rpc options together in the help output.
We have issue that the CLI is confusing to use because of the multiple sets of options. We have longer running discussions about how we might tackle that longer term. Grouping the options in the help is a low hanging fruit way we can improve the readability of the help. This isn't intended to solve the issue once and for all, but it'll hold us over.
> Group sandbox and rpc options together

- src/serve.rs
Change `serve` subcommand to default to `localhost:8000/soroban/rpc`.
This is where quickstart serves things by default. Having them be the same makes switching back and forth simpler, as you don't need to change the URL, just the network passphrase.
[TODO or N/A]
> Change cli serve defaults and path to match quickstart docker

- src/rpc/mod.rs
- src/serve.rs
Change the URL the invoke client connects to, to not append the rpc path and rely on the user providing the full path at the command line. Also prints the served path to the command line so people know what it is.
https://github.com/stellar/soroban-cli/pull/211 changed the path that get served to be /soroban/rpc instead of /api/v1/jsonrpc, to match soroban-rpc.
However, the soroban invoke command still sends requests to /api/v1/jsonrpc. This doesn’t seem to matter for the real soroban-rpc server, but the invoke command doesn’t work with the local serve anymore.
> Fix the url the invoke client connects to for the rpc

- .github/workflows/publish.yml
Publish binaries.
For installs without building from source.
This doesn't have a huge use, given that most people can install soroban-cli using cargo, and most people who need to install it will probably already have cargo installed because it's required for developing contracts.
But this has use in some places where it is difficult to install from source. For example, when installing soroban-cli into a repl.it, the build consumes so much disk space that it often fails to install.
There's plenty of things we can improve about this. For example, we should publish binaries for Windows and Linux-aarch64. Also, we will probably subsume this into the shared publish.yml workflow that lives in the stellar/actions repo, but for now this will do.
> Publish binaries

- .github/workflows/rust.yml
- tests/e2e_rpc_server.rs
Add token creation and invocation e2e test
Coverage :)
N/A
> Add token contract e2e test

- src/completion.rs
Change `soroban-cli` to `soroban` for the `completion` command
Completion got broken when the bin name changed to `soroban`. This PR fixes that.
> Fix the bin name in the completion command

- src/serve.rs
Allow missing params list for `getHealth` method.
Fixes #151
[TODO or N/A]
> Fix jsonrpc compliance issue #151

- .github/workflows/publish.yml
Set the version from the release name.
The upload step in the release process is failing. See https://github.com/stellar/soroban-cli/actions/runs/3392390018.
The version wasn't being set correctly, and so was blank.
> Fix publish binary ci job

- Cargo.lock
- Cargo.toml
Switch to specifying development versions on dependencies instead of separately as patches.
See https://github.com/stellar/rs-soroban-env/pull/568.
Close https://github.com/stellar/rs-soroban-env/issues/567
> Lean on workspace inheritance for deps for development

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
Rename `soroban-cli` to `soroban`.
We removed the `-cli` suffix on the command a while ago because we had feedback from external and internal folks that we should shorten the command. It got recently accidentally added back in #251.
This PR is intended to be merged to `main` after #257.
> Fix soroban-cli => soroban

- cmd/soroban-rpc/docker/Dockerfile
Update the docker building file for the soroban-rpc to match the new location.
The location has changed due to the porting of the utility between repos.
This PR is a pre-req to the quickstart update.
N/A
> soroban-rpc: Update the docker building file for the soroban-rpc to match the new location

- cmd/soroban-rpc/internal/config/config.go
- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/main.go
Break the soroban-rpc daemon out of the main function. 
That would allow us to write tests that invoke a server while bypassing the command line processor.
N/A
> soroban-rpc: separate the daemon from the main function

- Makefile
- cmd/soroban-rpc/internal/config/version.go
- cmd/soroban-rpc/main.go
Add version information to soroban-rpc
Before making the next release, we should version and timestamp our released binaries.
N/A
```bash
> soroban-rpc version
soroban-rpc 0.2.1 (e224d8745a92ba3d626f795587bf55d1fd154474)
```
> soroban-rpc: Add version information

- cmd/soroban-rpc/main.go
- go.mod
- go.sum
update soroban-rpc version printing to include the xdr version
To improve tooling building transparency
N/A
```bash
> soroban-rpc version
soroban-rpc 0.2.1 (1f9220d764358c1515b2ed53d3c512c8765b5769) tsachi/addXdrVersion
stellar-xdr d194cc6cd79e3b368c43477556b0084e81b9dcbc
```
> cmd/soroban-rpc: print xdr version

- .github/workflows/soroban-rpc.yml
- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/src/deploy.rs
- cmd/soroban-cli/src/invoke.rs
- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-cli/src/serve.rs
- cmd/soroban-cli/src/strval.rs
- cmd/soroban-cli/src/token/create.rs
- cmd/soroban-cli/src/token/wrap.rs
- cmd/soroban-cli/src/utils.rs
- cmd/soroban-rpc/internal/test/docker-compose.yml
- cmd/soroban-rpc/internal/test/get_contract_data_test.go
- cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
- cmd/soroban-rpc/internal/test/integration.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/internal/test/transaction_test.go
- cmd/soroban-rpc/main.go
- go.mod
- go.sum
- tests/it/e2e_rpc_server.rs
- tests/it/invoke_sandbox.rs
Update the soroban-rpc xdr, on top of get-ledger-entry branch
> Updating xdr for soroban-rpc

- .github/workflows/soroban-rpc.yml
- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/src/deploy.rs
- cmd/soroban-cli/src/invoke.rs
- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-cli/src/serve.rs
- cmd/soroban-cli/src/strval.rs
- cmd/soroban-cli/src/token/create.rs
- cmd/soroban-cli/src/token/wrap.rs
- cmd/soroban-cli/src/utils.rs
- cmd/soroban-rpc/internal/jsonrpc.go
- cmd/soroban-rpc/internal/methods/get_ledger_entry.go
- cmd/soroban-rpc/internal/test/docker-compose.yml
- cmd/soroban-rpc/internal/test/get_contract_data_test.go
- cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
- cmd/soroban-rpc/internal/test/integration.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/internal/test/transaction_test.go
- cmd/soroban-rpc/main.go
- go.mod
- go.sum
- tests/it/e2e_rpc_server.rs
- tests/it/invoke_sandbox.rs
Add a new rpc `getLedgerEntry` method to supersede `getContractData`.
Because the contract storage has changed with the new xdr, `getContractData` can no longer be used by soroban-cli to fetch the contract code. We could have added the `getContractCode` endpoint from the original spec. But, it's come up several times that actually `getLedgerEntry` is both lower-level and more useful.
The plan will be to deprecate `getContractData`, and remove it in favour of `getLedgerEntry` in the next release.
- Will need two requests, one to get the code address, and a second to get the actual code.
> Add a more generic getLedgerEntry rpc method

- .github/workflows/soroban-rpc.yml
Run the tests on ubuntu focal.
Because stellar-core doesn't currently install on ubuntu jammy.
[TODO or N/A]
> Run soroban-rpc tests on ubuntu focal so stellar-core can install

- cmd/soroban-rpc/main.go
Bring back the xdr commit hash in the version output.
It was accidentally removed in #274 
[TODO or N/A]
> re-incorporate xdr commit into version command

- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/Cargo.toml
Upgrade crate-git-revision to 0.0.4
Keep on the same version as other soroban crates. Once fully upgraded there won't be any duplicates in the lockfiles.
I think this is the last of the stellar repos that have this crate in their manifest.
N/A
> Upgrade crate-git-revision to 0.0.4

- cmd/soroban-cli/src/deploy.rs
- cmd/soroban-cli/src/install.rs
- cmd/soroban-cli/src/invoke.rs
- cmd/soroban-cli/src/main.rs
- cmd/soroban-cli/src/read.rs
- cmd/soroban-cli/src/serve.rs
- cmd/soroban-cli/src/token/create.rs
- cmd/soroban-cli/src/utils.rs
- tests/it/e2e_rpc_server.rs
- tests/it/invoke_sandbox.rs
- Added `install` command to install the WASM without creating a contract instance
- Added `--wasm-hash` option to `deploy` command (not `invoke` for now) to use the installed WASM
This supports the contract factory use case that requires to install the contract code separately and also showcases the new API capabilities.
This is still imperfect - e.g. a WASM hash should probably be returned when the contract is deployed, but I'm not sure what would be the right way to display it.
> Additional CLI support for the contract deployment changes.

- cmd/soroban-cli/src/token/wrap.rs
see #277 
Fix that the footpoint was not set correctly when deploying the wrapped token contract.
see #277 
Lack of test cases
> soroban-cli: fix that the footpoint was not set correctly when deploying the wrapped token contract

- cmd/soroban-cli/src/version.rs
Add xdr and env version to version subcommand output.
So that when using the soroban-cli it is easy to see what versions of the shared dependencies are in use. When we encounter problems we can check if we're using a version of the CLI compatible with the version of RPC, compatible with the version of stellar-core, etc.
> Add xdr and env version to version subcommand output

- .github/workflows/rust.yml
- cmd/soroban-cli/src/deploy.rs
- cmd/soroban-cli/tests/it/e2e_rpc_server.rs
- Fix bug in `soroban deploy --wasm-hash` sequence calculation introduced in https://github.com/stellar/soroban-tools/commit/eadacececc2b1071232db7ab045738d461908481
- Incidentally fixes https://github.com/stellar/soroban-tools/issues/290
- Fix conflicting contract ids in e2e tests
- The token contract and the newly installed one were using the same salt, resulting in a conflict between the tests.
- Use the temporary `stellar/quickstart:pr-389-soroban-dev` to run e2e tests so they work for now.
- Remove hardcoded `--salt` params from e2e tests altogether.
- This means the cli will autogenerate a random salt for each one.
- The e2e tests are then independent from each other and are less likely to conflict.
- The e2e do not need a clean network to run anymore.
To fix the e2e tests for …
> Bugfixes for e2e tests in release/v0.3.0 branch

- .github/workflows/rust.yml
Run `apt-get update` before `apt-get install` in ci.
We're seeing failures which are likely to do with the apt-get repositories that are cached being out of date. It's common practice to run update before install.
> Fix apt-get install failures in ci

- Cargo.lock
- Cargo.toml
Update soroban-env, stellar-xdr, soroban-sdk.
To remove the crate-git-revision 0.0.3 dep from the dep graph because it causes invalidations of the entire build.
Close #296
> Remove crate-git-revision 0.0.3 from dep graph

- .github/workflows/publish.yml
Build Linux binaries on Ubuntu 20 instead of Ubuntu 22.
To get an older version of glibc, so that the Linux binaries are compatible with a wider variety of Linux distributions in use right now.
> Use an older version of glibc for published binaries on Linux

- cmd/soroban-cli/src/invoke.rs
- cmd/soroban-cli/src/read.rs
- cmd/soroban-cli/src/serve.rs
- cmd/soroban-cli/src/strval.rs
Rename StrValError to Error and implement it with thiserror. Also remove Error suffix for `UnknownError` since `Error::Unknown` is clearly an error.
Make it more idiomatic and follow the same convention for errors used across the crate.
[TODO or N/A]
> chore: StrValError --> and implemented using thiserror

- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/src/invoke.rs
- cmd/soroban-cli/src/serve.rs
- cmd/soroban-cli/src/token/create.rs
- cmd/soroban-cli/src/token/wrap.rs
Use LedgerSnapshot::update to update snapshot instead of unpacking the host and updating ledger info and entries separately.
The update function that takes a host and updates a snapshot was added in https://github.com/stellar/rs-soroban-sdk/pull/802 to reduce the amount of code applications like the CLI needed to write to update the snapshot. It also moves responsibility and knowledge about what it means to update a snapshot into the snapshot library, where that knowledge is specialized.
> Use LedgerSnapshot::update to update snapshot

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
This upgrades binaryen to version 111.
Binaryen (and wasm-opt) now enables the `SignExt` and `MutableGlobals` features by default, which are also enabled in the LLVM backend. In the future Binaryen will align its default feature selection with the LLVM backend.
This is _probably_ is ok for soroban - wasmi supports both these.
This also points to potential future optimizations by explicitly turning on more features that wasmi supports but that aren't enabled in wasm-opt by default.
The [changelog](https://github.com/brson/wasm-opt-rs/blob/master/CHANGELOG.md) for 0.111.0.
Just upgrading deps.
N/A
> Upgrade wasm-opt to 0.111.0

- cmd/soroban-cli/src/optimize.rs
Disable optional features when calling wasm-opt.
In https://github.com/stellar/soroban-tools/pull/331 I mentioned that the new wasm-opt enables signext and mutable globals by default.
After a closer look, soroban disables these features explicitly when setting up the wasmi vm, so it seems to me they should be disabled in wasm-opt too.
na
> Disable optional features in wasm-opt

- cmd/soroban-rpc/internal/test/integration.go
The current code was producing the message `unable to find commit hash` without specifying what commit hash was being looked for. 
The code for scanning the commits was incorrect. It should have evaluated parents of commits in order to properly find the full hash based on the short hash.
N/A
> integration testing: fix "unable to find commit hash" during tests

- cmd/soroban-cli/src/events.rs
- cmd/soroban-rpc/internal/methods/get_events.go
The topic matching code was a little convoluted given the simplified invariants it needs to maintain:
- the topic filter needs to match the **number** of segments exactly (e.g. `transfer/GABC/10` should not match `transfer/GABC`)
- a filter segment should match the topic segment **exactly** or be a wildcard (`*`)
Simpler code = easier to read/maintain/debug.
Both of these have unit tests, so N/A.
> soroban-cli, soroban-rpc: Simplify topic matching code.

- .github/workflows/soroban-rpc.yml
The soroban-rpc integration tests started to fail with errors like: 
```
unable to prepare context: unable to 'git clone' to temporary context directory: error fetching: /usr/lib/git-core/git-remote-https: /tmp/_MEIRQrBNt/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /lib/x86_64-linux-gnu/libssh.so.4)
```
See https://github.com/stellar/soroban-tools/actions/runs/3932760675/jobs/6725700781
> soroban-rpc: fix docker-compose error in integration tests

- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/src/serve.rs
The "adapts" the CLI to changes to the SDK APIs that arrived in https://github.com/stellar/rs-soroban-sdk/pull/824 though apparently there is no adaptation required, just a version bump. Also includes a small fix to a clippy issue.
> Bump to new env and SDK versions, fix clippy issue

- .github/workflows/soroban-rpc.yml
After fixing the integration tests a few days ago (https://github.com/stellar/soroban-tools/pull/340) they started failing again with a different error: ` AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'`
see, for instance https://github.com/stellar/soroban-tools/actions/runs/3974532238/jobs/6813853311
> soroban-rpc: Fix integration tests again

- cmd/soroban-rpc/internal/config/config.go
- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/main.go
include a `captive-core-use-db` command option to be passed to captive core config 
have more control of ram vs disk usage at deployment/runtime
> include captive-core-use-db command option

- go.mod
- go.sum
updated the go mod for `github.com/stellar/go` to refer to latest commit hash of soroban-xdr-next.
> bumped version of soroban-xdr-next branch 

- .github/workflows/e2e.yml
bumped toolchain version used on e2e test to be same as code config
prior e2e config was pinned at 1.66.0, code config has recently bumped to 1.67.0
> increased the rust toolchain version on e2e test config

- .dockerignore
- cmd/soroban-rpc/docker/Dockerfile
the docker build file for soroban rpc fails with error during go build:
```
#6 33.81 /usr/bin/ld: cannot find -lpreflight
```
need the build to work, as quickstart uses it to build soroban-rpc, updated the dockerfile to use the Makefile `build-soroban-rpc` target
> update docker build for latest make target

- Makefile
- cmd/soroban-rpc/docker/Dockerfile
added new build arg for version override on dockerfile for soroban rpc
need ability to override the version stamp placed into soroban rpc bin, default is derive from git tag, but some environments like Jenkins package builder, may have a user defined Version value that should be stamped into bin instead.
> new build arg for version override on dockerfile build of soroban rpc

- cmd/soroban-cli/src/serve.rs
Missed adding getNetwork to `soroban serve` in https://github.com/stellar/soroban-tools/pull/366
So `soroban serve` is at least more consistent with soroban-rpc.
[TODO or N/A]
> Add getNetwork to soroban serve for consistency

- cmd/soroban-rpc/lib/preflight/Cargo.toml
avoid publishing the preflight package, which is used internally as part of the soroban-rpc build.
we don't need to publish this package.
N/A
> avoid publishing the preflight library

- .github/workflows/e2e.yml
- .github/workflows/soroban-rpc.yml
- Cargo.toml
- go.mod
- go.sum
bump soroban versions to latest for preview7 release
all soroban refs need to be at latest versions for release
> bump soroban versions for cargo, go, e2e

- go.mod
- go.sum
update go monorepo dep
the horizon repo is ready for release, sync with soroban-tools
N/A
> update go monorepo dep

- go.mod
- go.sum
updated go monorepo dep for with `go get github.com/stellar/go@soroban-xdr-next`
pull in fix that was pushed to monorepo:soroban-xdr-next, https://github.com/stellar/go/pull/4772
> updated go mod ref to latest on soroban-xdr-next

- .github/workflows/soroban-rpc.yml
This reduces the noise when finding test errors
> soroban-rpc: build libpreflight in its own workflow step

- cmd/soroban-rpc/internal/jsonrpc.go
- cmd/soroban-rpc/internal/methods/health.go
Make sure that the DB is ready in the `getHealth()` endpoint
`soroban-rpc` is not really ready until we reach the first checkpoint (before which the DB won't be ready, and ingestion won't be able to start)
The `getHealth` endpoint now becomes a bit heavier
> soroban-rpc: Check DB on health endpoint

- .github/workflows/e2e.yml
updating system-test to use newer [1.0.7 system-test ](https://github.com/stellar/system-test/releases/tag/v1.0.7) version which has new test coverage on auth next, fix for latest cli compatibility(removal of the `--fn`), and some speed improvements on e2e test run duration.
[update] some performance testing results, using a larger gh runner profile with more cores sped up workflow execution of the system test suite, reducing typical 50+ minute duration to about 24 minutes. Furthermore, using a pre-compiled image for core, cut the duration time down to about 15 minutes. However, holding off on using core images for now from system test, since they are not published yet.
more test coverage on soroban functionality([auth next](https://github.com/stellar/system-test/pull/34)) and faster ci …
> update e2e to use latest system-test

- cmd/soroban-cli/src/contract/invoke.rs
- cmd/soroban-cli/src/strval.rs
- cmd/soroban-cli/tests/fixtures/test-wasms/custom_type/src/lib.rs
- cmd/soroban-cli/tests/it/custom_types.rs
Each contract method argument provides a full type for UDT and add an example input.
Examples:
```
ssome_types 
USAGE:
some_types [OPTIONS]
OPTIONS:
--address <Address>                          Example:
--address GDIY6AQQ75WMD4W46EYB7O6UYMHOCGQHLAQGQTKHDX4J2DYQCHVCR4W4
--bool                                       Example:
--bool 
-h, --help                                       Print help information
--i32 <i32>                                  Example:
--i32 -1
--option <Option<u32>>                       Example:
--option 1
--set <Set<Address>>                         Example:
--set '[ "GDIY6AQQ75WMD4W46EYB7O6UYMHOCGQHLAQGQTKHDX4J2DYQCHVCR4W4" ]'
--strukt <{ a: u32, b: bool, c: Symbol }>    This is from the rust doc above the struct Test
Example:
--strukt '{ "a": 1, "b": true, "c": …
```
> feat: add better docs for UDT and add examples for each arg

- cmd/soroban-rpc/internal/ingest/ledgerentry.go
- go.mod
- go.sum
Store the value of all the ledger entries, regardless of their type.
https://github.com/stellar/soroban-tools/issues/378
This will allow the `getLedgerEntry` method to work for any ledger entry type (initially we only enabled the entries needed to implement `simulateTransaction`).
In pubnet, it adds ~5GB extra to the DB (which isn't much since we are already at 27GB, most of which is from 24h of txmeta)
> soroban-rpc: Store all ledger entry types

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
Remove the `config` cargo crate dep.
`cargo +nightly udeps --all-targets`, says it is unused. And afaict it has never been used. I think it was added accidentally in https://github.com/stellar/soroban-tools/pull/275, can you confirm @willemneal ?
[TODO or N/A]
> Remove unused `config` cargo crate

- cmd/soroban-rpc/internal/config/config.go
- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/internal/jsonrpc.go
- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/preflight/pool.go
- cmd/soroban-rpc/internal/test/integration.go
- cmd/soroban-rpc/main.go
Limit preflight-computation concurrency through a worker pool
The number of workers can be configured through `--preflight-worker-count` and defaults to the number of CPUs in the machine.
preflight-obtention is CPU-bound, according to @tsachiherman it is a good idea to limit it to the number of course. 
I am on the fence about this though (the OS will be self-limiting in this regard). Also, although the worker pool code is not overly complicated it does add some complexity.
> soroban-rpc: Limit preflight-computation concurrency through a worker pool

- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/tests/fixtures/test-wasms/custom_type/src/lib.rs
Fix symbol construction and update hashes.
[TODO or N/A]
> fix(cli): symbol

- .github/workflows/soroban-rpc.yml
- cmd/soroban-rpc/internal/methods/get_events_test.go
- cmd/soroban-rpc/internal/test/docker-compose.yml
- cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/internal/test/transaction_test.go
- go.mod
- go.sum
Adapt soroban-rpc to the new value overhaul XDR changes (that is https://github.com/stellar/go/pull/4814 , which in turn comes from https://github.com/stellar/stellar-xdr/pull/70 )
It's part of https://github.com/stellar/soroban-tools/issues/471
It closes https://github.com/stellar/soroban-tools/issues/477
TODO:
> soroban-rpc: adapt to value overhaul changes

- .github/workflows/soroban-rpc.yml
- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/events.rs
- cmd/soroban-rpc/internal/test/docker-compose.yml
The Golang dependencies already had XDR support for structured debug events whilst Core and the Rust dependencies didn't.
This caused the soroban-rpc integration tests to break with XDR decoding errors.
This change bumps Core and the Rust dependencies to also support structured debug events.
> Bump all dependencies to support structured debug events

- .cargo-husky/hooks/pre-commit
- .github/workflows/full-help-docs.yml
- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/bin/doc-gen.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- cmd/soroban-cli/src/commands/mod.rs
- docs/README.md
- docs/soroban-cli-full-docs.md
- Add a separate `doc-gen` binary to the CLI project; needs to be run with a feature flag so that we can avoid adding its dependencies (currently only [clap-markdown](https://docs.rs/clap-markdown)) to the main project's dependencies.
- Run new bin with `cargo run --bin doc-gen --features clap-markdown` to generate a markdown documentation page in the `docs/` folder, so people can read about the entire CLI all together
- Link to this from `soroban --help` output
- Start strategically adding both long help (available with `--help`; gets included in this comprehensive doc) and short help (available with just `-h`) for root `soroban` help docs and some subcommands (only `soroban contract invoke --help`, for now)
This fixes the frustration of the current CLI, which requires typing `--help` …
> feat: auto-generate comprehensive CLI docs

- .github/workflows/e2e.yml
bumping versions of system-test and soroban core git ref to latest
to enable e2e tests to pass, tests need to be in sync with latest soroban tools cli/rpc interfaces and core version.
this pr obsoletes a slightly older pr, which was doing similar bump but with different version of core [#531](https://github.com/stellar/soroban-tools/pull/531#discussion_r1147937107)
> update e2e to use system-test 1.0.10 and latest soroban core git ref

- cmd/soroban-cli/tests/fixtures/test-wasms/hello_world/src/lib.rs
- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight.h
- cmd/soroban-rpc/lib/preflight/src/lib.rs
Add contract events to simulateTransaction's response. This change modifies libpreflight to return contract events and the `simulateTransaction` JSONRPC method to include contract events in its response.
Closes https://github.com/stellar/soroban-tools/issues/475
N/A
TODO:
> soroban-rpc: Add contract events to simulateTransaction's response

- go.mod
- go.sum
Update the go.mod dependency to point to the newly released `soroban-v0.0.7` tag.
So we can release this with the latest changes.
[TODO or N/A]
> Update go dep to soroban-v0.0.7

- cmd/soroban-cli/src/commands/config/locator.rs
- cmd/soroban-cli/src/commands/config/network/mod.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- docs/soroban-cli-full-docs.md
Add two new ENV variables to allow the network and contract id to be set.
Also improved help headings to make things clearer.
This way you can set which network with an ENV variable which is useful for testing and scripts.
[TODO or N/A]
> feat(CLI): add SOROBAN_(NETWORK/CONTRACT_ID)

- .github/workflows/update-completed-sprint-on-issue-closed.yml
Automatically assign the `CompletedSprint` field when an issue or PR is closed.
Because we keep forgetting, which is a pain for @mollykarcher.
Just trying it on this repo, in case it doesn't work. The oauth key restrictions mean we can't test this locally without just pushing it and seeing. If it works we should use it on other repos as well.
Depends on https://github.com/stellar/actions/pull/51
> Try out the new action to automatically update the CompletedSprint field when issue closed

- .github/workflows/e2e.yml
setting e2e to use last stable version v0.7.0 of soroban examples for contracts to use in tests
latest main on soroban examples has recent commits that seem to be causing breaking change for the contracts to be used by e2e tests, need to triage that problem further, this change is meant to just get the e2e back to passing in interim.
> change e2e to use last stable soroban examples for test contracts

- cmd/soroban-rpc/lib/preflight/src/lib.rs
Followup to  #553 
(Found out by @sreuland at https://github.com/stellar/soroban-tools/commit/9be3f2c5036ad2db237df98516b9ae872f9fd997#r108326767 )
> soroban-rpc: libpreflight: Avoid panicking when address and nonce are both None

- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/internal/jsonrpc.go
- go.mod
Each HTTP request is assigned an ID logged using the the stellar/go/support/http middleware
Within each HTTP request, each JSONRPC request is logged using the global HTTP ID and the per-request JSONRPC ID.
Additionally, I added the version and commit of soroban-rpc to the startup log.
Done as part of #497 
N/A
> soroban-rpc: Add logging for HTTP requests and JSONRPC requests

- cmd/soroban-rpc/internal/config/config.go
- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/main.go
- go.mod
- go.sum
Add a `--log-format` commandline flag to allow changing the logging format (for now it can be set to `json` or `text`)
The `stellar/go` dependency is bumped to get https://github.com/stellar/go/pull/4841
#497 
N/A
> soroban-rpc: Add JSON logging

- .github/workflows/e2e.yml
use 4 core gh runner for e2e workflow, and see if the duration times are still good with that compute level.
potential savings in compute costs by using a lower core runner
the duration time for gha workflow of e2e is compute intensive
> try using 4 core gh runner for e2e workflow

- .github/workflows/rust.yml
Use an 8-core windows github runner to get 150gb disk.
Should fix the failure here: https://github.com/stellar/soroban-tools/pull/585
[TODO or N/A]
> Use an 8-core box to build on windows, so we get more disk

- .github/workflows/e2e.yml
bumping system test ver to [1.0.12](https://github.com/stellar/system-test/releases/tag/v1.0.12)
this version will fix the system test docker build err on phantomjs
> fixed phantomjs e2e build error

- .github/workflows/e2e.yml
- go.mod
- go.sum
bumped up the versions of core to [61f76a1137b](https://github.com/stellar/stellar-core/commit/61f76a1137b82cbf6724c54bdd325daebed28151) and soroban-examples to main in e2e tests and pulled in the latest for `github.com/stellar/go` from `soroban-xdr-next` as that has new xdr defs.
They were previously at Preview8 versions, but newer soroban rs env interface and xdr has been added and soroban-tools had the rs env updated but needed xdr update for rpc ingestion and e2e needed to point at latest refs.
> Update soroban ref versions

- .github/workflows/soroban-rpc.yml
Apparently the docker issue in https://github.com/stellar/soroban-tools/pull/628, was *not* fixed, but is just intermittent. :(
All the docker support issues say to use docker-compose v2, so let's try installing that.
[TODO or N/A]
> Try new docker compose plugin

- .github/workflows/soroban-rpc.yml
- cmd/soroban-rpc/internal/test/docker-compose.yml
Update the Core version used in soroban-rpc's integration tests after a bug was fixed on Core's side 
We want a bugless Core
N/A
> soroban-rpc: Bump core dependencies supporting fees

- cmd/soroban-cli/src/commands/contract/inspect.rs
- cmd/soroban-cli/src/wasm.rs
If there is env meta to show for the contract, include it in the output of `soroban contract inspect --wasm foo.wasm`
This also improves the `contract inspect` output, to format output nicer, and include doc strings.
e.g.
```
• Function: withdraw
Docs: Whatever docstring the function has goes here.
Inputs: VecM(
[
ScSpecFunctionInputV0 {
doc: StringM(),
name: StringM(to),
type_: Address,
},
ScSpecFunctionInputV0 {
doc: StringM(),
name: StringM(share_amount),
type_: I128,
},
ScSpecFunctionInputV0 {
doc: StringM(),
name: StringM(min_a),
type_: I128,
},
ScSpecFunctionInputV0 {
doc: StringM(),
name: StringM(min_b),
type_: I128,
},
],
)
Output: VecM(
[
Tuple(
ScSpecTypeTuple {
value_types: VecM(
[
I128,
I128,
],
),
},
),
],
)
```
Fixes https://github.com/stellar/soroban-tools/issues/593
We …
> Add meta output to soroban-cli contract inspect output

- .github/workflows/e2e.yml
- Cargo.lock
- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/internal/test/get_ledger_entries_test.go
- cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/internal/test/transaction_test.go
- cmd/soroban-rpc/lib/preflight.h
- cmd/soroban-rpc/lib/preflight/Cargo.toml
- cmd/soroban-rpc/lib/preflight/src/fees.rs
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
- cmd/soroban-rpc/lib/preflight/src/lib.rs
- go.mod
- go.sum
Calculate soroban transaction data in libpreflight
This changes the API of `simulateTransaction`. `SimulateTransactionResponse` changes as follows:
* Instead of returning a footprint, we return the full soroban transaction data.
* The list of events is returned globally instead of per host function
* A new field, `minResourceFee`, is added to tell the user what fee should be used with respect to the resources consumed by the host function invocations.
Closes #622 
N/A
> soroban-rpc: Calculate soroban transaction data in libpreflight

- cmd/soroban-rpc/main.go
Print the compiled xdr version during `soroban-rpc version` : 
```
$ soroban-rpc version
soroban-rpc dev
stellar-xdr 2f16687fdf6f4bcfb56805e2035f69997f4b34c4
```
Could help us with debug efforts.
n/a
> soroban-rpc: print xdr version in dev compilation

- Makefile
ensure that failed builds would not result in corrupted soroban-rpc binaries being built without a commit hash.
The makefile wasn't verifying that the `git` command was executed successfully.
It wasn't an issue before; however, during build the .git directory was omitted in https://github.com/stellar/quickstart/pull/449. This PR would ensure that such a case would be caught early.
n/a
> soroban-rpc: ensure building with proper commit hash version

- cmd/crates/soroban-test/tests/fixtures/hello/Cargo.toml
Do not publish soroban-hello test fixture.
It is a test fixture. It isn't intended to be published. In the v0.8.0 release it was attempted published because cargo-workspace looks for all crates in the repo. Other test fixtures we configure with publish = false, and looks like we just missed it on this one.
N/A
> Do not publish soroban-hello test fixture

- .github/workflows/e2e.yml
use newer rel version labels for e2e
e2e was pointing at non-released version refs
waiting for the [quickstart preview9](https://github.com/stellar/quickstart/pull/444) to merge before setting the quickstart version here on e2e
> updating e2e versions

- cmd/soroban-rpc/internal/jsonrpc.go
Fix small logic error preventing responses from being logged.
It's a bug
N/A
> soroban-rpc: Fix response debug printing

- .github/workflows/dependency-check.yml
- scripts/check-dependencies.bash
Add dependency checker script and make it run in CI ~(this last part is still TODO)~.
Close https://github.com/stellar/soroban-tools/issues/572
Parsing of Core/Golang versions doesn’t work when they don’t contain a commit hash.
I left TODOs for them and we can fix it later if needed.
> Add dependency checker script

- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight/src/fees.rs
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
Obtain the configuration for the fee estimation of `simulateTransaction` from the ledger instead of hardcoding it.
Close #665 
Obtaining 4 ledger entries for each `simulateTransaction` call will reduce performance. We need a benchmark to measure the impact.
> soroban-rpc: Obtain fee configuration from the ledger

- cmd/crates/soroban-test/tests/it/arg_parsing.rs
- cmd/soroban-cli/src/strval.rs
Fix a bug parsing "bytes" type args, where the value is all numbers.
Parsing a bytes array of the text "DT" would fail (bytes 0x45, 0x54). The CLI json arg parser would count it as a json number, not a string, so parsing would fail.
[TODO or N/A]
> Fix a bug parsing bytes args where the hex are all numbers

- .github/workflows/soroban-rpc.yml
- README.md
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/lib/preflight/Cargo.toml
Compiling under windows got broken by the internet.
The rust compiler was modified between release 1.69 and 1.70; the suspected culprit is the upgrade for rust to be using LLVM 16.
The solution here is to use the minimal supported version and to use a rust compiler of that version ( 1.69 ). This is a good temporary solution until we can fix the issue properly.
> soroban-rpc: fix compilation on windows

- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/rpc/mod.rs
Small follow-up refactor to https://github.com/stellar/soroban-tools/pull/675
Simplify the `invoke.ts` code by moving the contract spec fetching into the rpc client.
[TODO or N/A]
> soroban-cli: Minor contract spec fetching refactor

- Cargo.lock
- Cargo.toml
- cmd/soroban-cli/src/commands/contract/bindings.rs
- cmd/soroban-cli/src/commands/contract/bindings/json.rs
- cmd/soroban-cli/src/commands/contract/bindings/rust.rs
- cmd/soroban-cli/src/commands/contract/bindings/ts.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- docs/soroban-cli-full-docs.md
Refactor the bindings command into subcommands and adds a TS project.
This way they can each have their own options.
Requires: https://github.com/stellar/rs-soroban-sdk/pull/871
> feat!: convert bindings to subcommands and add a ts one

- .github/workflows/publish.yml
- .github/workflows/rust.yml
Disable fail-fast on soroban-cli builds and publishes.
The fail-fast feature is enabled by default on matrix builds of GitHub Action jobs. When enabled, if any run in the matrix fails, all running variations will be canceled and any yet to run won't run.
Disabling fail-fast will cause all matrix builds to start and run to completion, regardless of whether another run in the matrix succeeds or fails.
It is enabled by default because it makes builds more efficient. Normally if a run fails there's enough information to go on to fix and then run again.
For the soroban-cli it is beneficial if builds that are matrix based on platforms are run without fail-fast because we will get broad signal if a problem is only related to one platform or multiple.
Recently we've had trouble with Windows …
> Disable fail-fast on soroban-cli builds and publishes

- .github/workflows/e2e.yml
- .github/workflows/soroban-rpc.yml
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/lib/preflight/Cargo.toml
Fix compilation issue with soroban-rpc & updated rust compiler.
We previously pinned the rust compiler to 1.69, since the transition to 1.70 included an upgrade to llvm 16.
That upgrade broke binary compatibility between the preflight library and the soroban-rpc.
To overcome these limitations, this PR switches to use the msys2 version of mingw's gcc compiler. This is the same compiler that the gnu implementation of rust is using, and therefore produces the same library symbols.
With this change in place, we can continue upgrading the rust compiler version as needed.
N/A
> preflight: Resolve compilation issue rust 1.70 on windows

- cmd/soroban-cli/Cargo.toml
Currently the following works for installing from binary:
```
cargo binstall \
--pkg-url "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }{ archive-suffix }" \
--force \
soroban-cli
```
> fix: use correct url for cargo-binstall

- .github/workflows/soroban-rpc.yml
In the Github testing, I used \\ ( double slash ) to specify path on windows platform.
In a previous code review, it was suggested to replace these with /, since windows understands both.
It's sightly more aligned with the rest of the yml file content.
N/A. If it works, it works.
> build: update slash direction for windows RPC builds

- cmd/soroban-rpc/docker/Dockerfile
pin the os version on the golang:x.x.x base image used for dockerfile build stage on rpc
without the O/S tag included on golang:x.x.x, the image can potentially change as new Debian OS's are released which may cause un-intended side effects for binaries built/linked within. recommendation from team overall is to pin to `bullseye`
> pin os version of the rpc dockerfile build stage

- Makefile
- cmd/crates/soroban-spec-typescript/fixtures/ts/package.json
- cmd/crates/soroban-spec-typescript/fixtures/ts/src/invoke.ts
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/src/project_template/src/invoke.ts
For JS libraries generated with `soroban contract bindings typescript`:
- upgrade to freighter-api 1.5.0
- use the new methods from `freighter-api@1.5.0` to avoid popping
pop-ups over and over every time a view call is invoked
- if the transaction only needs to be simulated, then the user doesn't
need to have Freighter connected. This now uses a default/dummy
account for such calls, but throws an error if the app author tries to
`signAndSend` such calls.
- upgrade `soroban-client` to 0.8.1, which allows removing the pinned version of `stellar-base`
This greatly improves the devx & ux of apps that use these generated libraries.
N/A
> feat: upgrade freighter-api to 1.5.0 & soroban-client to 0.8.1

- .github/workflows/rust.yml
Following a recent dependency update, the `rust-analyzer` started failing when executing the following:
```sh
rustup run nightly rust-analyzer analysis-stats . 2>&1 | (! grep ERROR)
```
One of the dependencies was including the text "ERROR", which caused this test to fail. This is a false-positive,
since there is no actual failure here. The solution here is to omit the stdout and use the stderr only when scanning for the "ERROR" text.
N/A
> rust: fix rust-analyzer testing

- cmd/crates/soroban-spec-typescript/fixtures/ts/src/server.ts
- cmd/crates/soroban-spec-typescript/src/project_template/src/server.ts
Set `allowHttp` to `true` if the RPC_URL starts with `http:` rather than `https`.
This allows people to use the exported `Server` instance correctly when using a local node.
N/A
> fix: allow generated JS libs to use localhost

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/build.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- docs/soroban-cli-full-docs.md
Add command for building contracts:
```
soroban contract build
```
```
❯ soroban contract build -h
Build a contract from source
Usage: soroban contract build [OPTIONS]
Options:
--manifest-path <MANIFEST_PATH>  Path to Cargo.toml [default: Cargo.toml]
--package <PACKAGE>              Package to build
--profile <PROFILE>              Build with the specified profile [default: release]
--out-dir <OUT_DIR>              Directory to copy wasm files to
-h, --help                           Print help (see more with '--help')
Features:
--features <FEATURES>  Build with the list of features activated, space or comma separated
--all-features         Build with the all features activated
--no-default-features  Build with the default feature not activated
Other:
--print-commands-only  Print commands …
```
> Add command for building contracts

- cmd/soroban-cli/src/commands/contract/build.rs
Remove rustc options:
- `--locked`
- `--package`
The locked option prevents someone from having their Cargo.lock file updated, so it will be surprising / annoying to have in there. I had added it mistakenly thinking someone would only run the build command for final releasing, but likely it'll be used during development too, and it should update the file.
The package option is unnecessary, since each manifest the tool is passing to rustc is a single package.
> Remove unnecessary rustc options

- .github/CODEOWNERS
Add CODEOWNERS with @stellar/contract-committers listed as owners of the soroban contract build command.
So that @stellar/contract-committers are mentioned automatically whenever the build command is being altered or changed. They're responsible for the developer experience developing contracts themselves, and will ensure they stay up to date with the build command if it evolves over time.
Note that this will not require them to approve changes, because the repos is configured not to require code owners approval, so it will have no impact on developer workflows and just serve as a way to knowledge share and keep the team in the loop. Although involving them in changes to the build command would probably be a good idea.
> Add CODEOWNERS to keep contract committers automatically mentioned on changes to soroban contract build

- .github/workflows/publish.yml
Build and upload soroban-cli after publish is complete.
The package process we use for building for uploading is dependent on the publishing being complete. This is because of the same reason we had to make these changes:
- https://github.com/stellar/actions/pull/54
- https://github.com/stellar/soroban-tools/pull/709
Without this change the upload job will fail because it expects crates that are dependencies of soroban-cli are already published. If you wait till the publish job completes, and rerun the upload, the upload will succeed.
We could do some fancy things to make this work entirely locally, like how we do publish dry runs, but simply delaying upload until after publish is simpler.
> Upload after publish of crates

- scripts/check-dependencies.bash
There were a couple of small typos in the dependency checking script
> Fix check-dependencies typos

- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- docs/soroban-cli-full-docs.md
- Rename `root-dir` to `output-dir` to clarify the intent
- If `output-dir` already exists, use `output-dir/contract-name` instead
The old argument name and behavior made it too easy to accidentally
delete your entire project
N/A
> fix(bindings-ts): don't delete existing dirs

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
Just keeping wasm-opt updated.
There isn't much to be aware of in the binaryen 113 release notes:
https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v113
wasm-opt has a minimum rust version of 1.48,
but wasm-opt's cxx dependency has recently changed their minimum rust version to 1.60. it should still be possible to resolve a crate graph that is 1.48 compatible, and I think this lockfile is, but if the cxx dependency in the lockfile is ever re-resolved cargo will probably pick a cxx that is not 1.48 compatible.
> Upgrade wasm-opt to 0.113

- cmd/soroban-cli/src/commands/config/identity/ls.rs
- cmd/soroban-cli/src/commands/config/identity/mod.rs
- cmd/soroban-cli/src/commands/config/locator.rs
- docs/soroban-cli-full-docs.md
`soroban config identity ls -l`, inspired by `soroban config network ls -l`.
Also add a `soroban config identity list` alias.
I originally expected it at `list`, hence the alias.
The long-listing just shows full path to identity file. I was trying to figure
out where some defined identities were coming from while troubleshooting.
This is a bit simpler in implementation than the networks long-list. The
important information for identities is, in my opinion, just the path where the
identity file lives. So this just lists those. Happy to discuss the
implementation specifics, though!
Example:
$ soroban config identity ls -l
/Users/chadoh/code/soroban/dapp/.soroban/identity/token-admin.toml
/Users/chadoh/.config/soroban/identity/default.toml
> feat: long listing for identities

- Cargo.lock
- cmd/crates/soroban-spec-typescript/fixtures/ts/src/index.ts
- cmd/crates/soroban-test/tests/fixtures/test-wasms/hello_world/src/lib.rs
- cmd/crates/soroban-test/tests/it/custom_types.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/lab/token/wrap.rs
- docs/soroban-cli-full-docs.md
This PR sync soroban-xdr-next with main, plus fix few regression not fixed in https://github.com/stellar/soroban-tools/pull/741
fix compilation & testing errors.
n/a
> sync with main

- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
Fix the expected phrase in a soroban-rpc integration test
Got missed in a #730, I assume because all the tests have been broken for so long that lone failures are hard to catch.
[TODO or N/A]
> soroban-rpc: Fix integration test phrasing

- cmd/crates/soroban-spec-typescript/src/boilerplate.rs
- cmd/crates/soroban-test/tests/it/invoke_sandbox.rs
Disable a failing test - fetch
The test is running against futurenet, which wasn't upgraded yet.
This test should be moved to post-deployment testing rather then in here.
n/a
> compile: disable the fetch test

- cmd/soroban-cli/src/commands/lab/xdr/decode.rs
Fix `--type` flag parsing in `soroban xdr lab decode` subcommand.
I was hitting it when trying to debug other failing transactions. Turns out we need a `try_map` to tell clap how to convert the string into a `TypeVariant`. No idea how it ever worked tbh. Maybe some subtle xdr upgrade change broke it.
Previously you would get:
```
thread 'main' panicked at 'Mismatch between definition and access of `type`. Could not downcast to stellar_xdr::next::generated::TypeVariant, need to downcast to alloc::string::String
', cmd/soroban-cli/src/commands/lab/xdr/decode.rs:9:13
```
[TODO or N/A]
> Fix bug in cli lab xdr decode --type parsing

- cmd/soroban-cli/src/commands/contract/deploy.rs
- cmd/soroban-cli/src/commands/contract/fetch.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/events.rs
- cmd/soroban-cli/src/commands/lab/token/wrap.rs
- cmd/soroban-cli/src/rpc/mod.rs
Before we try to talk to the server, check the network_passphrase configured locally matches what the server reports.
For example, the error if you had configured to talk to futurenet, but the server you were talking to is on standalone would look like:
```
error: provided network passphrase "Test SDF Future Network ; October 2022" does not match the server: "Standalone Network ; February 2017"
```
This can prevent confusing and difficult-to-debug errors.
I had debated doing it in-line as part of the `Client::new` call, but that is currently not async. And I thought there might be cases where we want to use the client, but know the network passphrase doesn't matter. So, for now, there is a bit of boilerplate when we create a new client.
> soroban-cli: Verify the network passphrase provided matches the server

- cmd/crates/soroban-test/src/wasm.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-cli/src/utils.rs
Fix two bugs preventing contract deploy from working.
- When updating the xdr in this branch, I had used `TransactionResultMeta`, but it should be `TransactionMeta` from soroban-rpc.
- Contract code hashes are now just `hash(code)`, not a `hash(xdr(BytesM(code)))`
- @dmkozh is this ^ true?
> soroban-cli: fix contract deploy

- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/db/ledgerentry_test.go
- cmd/soroban-rpc/internal/methods/get_latest_ledger_test.go
- cmd/soroban-rpc/internal/methods/get_ledger_entries.go
- cmd/soroban-rpc/internal/methods/get_ledger_entry.go
- cmd/soroban-rpc/internal/preflight/pool.go
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/lib/preflight.h
- cmd/soroban-rpc/lib/preflight/src/fees.rs
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
This PR contains fixes for restore footprint preflighting. They are taken from https://github.com/stellar/soroban-tools/pull/757 (which cannot be merged since it contains a test which takes more than 1 hour to run).
> soroban-rpc: Restore footprint  preflighting fixes

- .github/workflows/e2e.yml
- .github/workflows/soroban-rpc.yml
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/convert.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/convert.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/index.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/convert.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/convert.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/types/convert.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/convert.ts
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/src/project_template/src/convert.ts
Replaces #764 to target `main`.
The only "real" change is to src/convert.ts [here](https://github.com/stellar/soroban-tools/pull/770/files#diff-157cc5d7c8ff4d63f8c66f141d63258c092d3055ffd090d8489637ab8c0446d6); the rest is just generated code.
cc @willemneal @chadoh
>  Upgrade generated TypeScript with Preview 10 changes

- cmd/soroban-cli/src/commands/contract/bump.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
Have bump+restore subcommands either output the new expiration ledger seq, or that the entry could not be bumped.
Previously there was no way to tell if it was successful or not since the core txn is always successful.
Doesn't really differentiate between entry not found and the entry not being bumped. We could check that by querying the rpc after to see if it exists.
> soroban-cli: Add better feedback to bump+restore ops

- cmd/soroban-cli/src/rpc/mod.rs
If the account or contract are not found, tell the user that instead of a cryptic missing ledger entry error. In particular this was painful if you had forgotten to fund your account via friendbot.
Old Error:
```
$ soroban contract invoke --network standalone --source chad --id $TOKEN_ID -- name
error: Missing result in successful response
$ soroban contract fetch --id $TOKEN_ID --network standalone
error: Missing result in successful response
```
New Error:
```
$ soroban contract invoke --network standalone --source chad --id $TOKEN_ID -- name
error: Account not found: GDZL3EOMVTO3EBU2DQJ5K4UQ2IUQ4ZD26SPEVW7323UYSOMEACFFRQAF
$ soroban contract fetch --id $TOKEN_ID --network standalone
error: Contract not found: CADAEZWBSG7EZF6AEANFTHTYBZD7FMU7XGUJS2MOK55JGSF7DUCA4YSY
```
The errors could …
> Output slightly better errors when account/contract are not found

- .github/workflows/e2e.yml
Bumps the latest soroban-client and system-test versions run in end-to-end tests.
Self-explanatory: latest = greatest.
> Bumps end-to-end test versions

- cmd/soroban-cli/src/commands/contract/bump.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- docs/soroban-cli-full-docs.md
Currently users must manually provide the xdr key corresponding ScVal for LedgerKeyContractInstance.
Now when no keys are provided this key is used.
Currently users must use a special magic value. This handles it for them.
[TODO or N/A]
> feat(CLI): restore/bump if no keys provided contract instance used

- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
Allow `soroban contract install` to restore the contract code in case it was previously installed.
This will prevent users from having to do the restore themselves in a second step. Since deploy reuses the install command it works for that too.
N/A
> feat(CLI): Contract Install with internal error restores the code

- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/index.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/index.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/invoke.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/invoke.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/method-options.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/index.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/index.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/invoke.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/invoke.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/method-options.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/types/index.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/types/invoke.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/types/method-options.d.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/index.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/invoke.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/method-options.ts
- cmd/crates/soroban-spec-typescript/src/lib.rs
- cmd/crates/soroban-spec-typescript/src/project_template/src/index.ts
- cmd/crates/soroban-spec-typescript/src/project_template/src/invoke.ts
- cmd/crates/soroban-spec-typescript/src/project_template/src/method-options.ts
By default, if you do not provide a `wallet` option to one of the
exported functions or `invoke`, then it will continue to import and use
Freighter.
But now you can also pass your own Wallet interface to any of these
functions.
This facilitates testing the generated libraries with Node, as well as
using them with other Wallet options.
Does not yet offer similar injectability for network settings & contract
ID.
> feat(bindings-ts): make Wallet injectable

- cmd/crates/soroban-spec-typescript/src/project_template/README.md
The generated libraries come with a useful README, but it's only useful
if it's truthful. This makes it truthful. It also adds more detail about
our current best thinking on how to include a local library in a
project, with links to some of the history there.
N/A
> fix(bindings-ts): correct generated README

- .github/workflows/soroban-rpc.yml
- cmd/crates/soroban-test/tests/fixtures/test-wasms/hello_world/src/lib.rs
- cmd/soroban-rpc/internal/test/captive-core-integration-tests.cfg
- cmd/soroban-rpc/internal/test/core-start.sh
- cmd/soroban-rpc/internal/test/docker-compose.yml
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/internal/test/stellar-core-integration-tests.cfg
Second attempt at #757 now that Core provided `TESTING_MINIMUM_PERSISTENT_ENTRY_LIFETIME` to make it testeable.
> soroban-rpc: Add restore footprint test (now that expiration is tunable)

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
Upgrade wasm-opt to 0.114
Just keeping wasm-opt updated.
There isn't much to be aware of in the binaryen 114 release notes:
https://github.com/WebAssembly/binaryen/blob/main/CHANGELOG.md#v114
na
> Update wasm-opt to 0.114

- cmd/soroban-cli/src/commands/contract/bump.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/wasm.rs
- docs/soroban-cli-full-docs.md
Allow passing a wasm hash when using bump/restore.
Allow restore to take multiple changes per operation.
Also fix issue with trying to store a contract instance (the key flags shouldn't be required).
Still currently only support one operation.
> Feat(CLI) restore/bump --wash_hash

- cmd/crates/soroban-test/tests/it/custom_types.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
Since the boolean type is used else where in the CLI as `true`/`false` the CLI should accept --flag, as `--flag true/false` too.
[TODO or N/A]
> feat: allow passing `true` and `false` to boolean types

- cmd/soroban-cli/src/commands/contract/bindings.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- cmd/soroban-cli/src/wasm.rs
- docs/soroban-cli-full-docs.md
Makes passing the wasm optional otherwise fetches the contract from the network.
[TODO or N/A]
> feat(CLI/bindings/ts): allow fetching contract from network

- cmd/crates/soroban-test/tests/it/custom_types.rs
- cmd/crates/soroban-test/tests/it/invoke_sandbox.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- docs/soroban-cli-full-docs.md
This allows passing file paths in place of arguments.  Files are read as strings for all types except Bytes and BytesN which are read as raw bytes.
The info about the new args is in the help doc header for each subcommand, otherwise the new args are hidden to not clog up the help documentation.
This is particularly useful for passing bytes to contracts and avoids needed to convert them to hex as the current CLI requires.
[TODO or N/A]
> feat(CLI): Each generated contract method adds <contract-arg>-file-path

- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/internal/db/db.go
- cmd/soroban-rpc/internal/db/ledger.go
- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/db/ledgerentry_test.go
- cmd/soroban-rpc/internal/db/transactionalcache.go
- cmd/soroban-rpc/lib/preflight/src/fees.rs
After https://github.com/stellar/soroban-tools/pull/692 I noticed that the DB access to config ledger entries is a big part of the preflight computation.
This PR adds a writethrough cache for config ledger entries.
Before the cache:
```
goos: darwin
goarch: arm64
BenchmarkGetPreflight/In-memory_storage
BenchmarkGetPreflight/In-memory_storage-12         	    6112	    193728 ns/op
BenchmarkGetPreflight/DB_storage
BenchmarkGetPreflight/DB_storage-12                	    2766	    430002 ns/op
PASS
```
After adding the cache:
```
goos: darwin
goarch: arm64
BenchmarkGetPreflight/In-memory_storage …
```
> soroban-rpc: Add writethrough cache for Config ledger entries

- cmd/soroban-rpc/internal/db/ledgerentry_test.go
- cmd/soroban-rpc/internal/db/transactionalcache.go
Leftover from #837 
BTW, the fact that the system tests are failing all the time gets the eye used to seeing red-crosses in CI. This lets problems like this leak through the cracks.
We should probably make the unit tests mandatory for merging although I would prefer for the system tests not to be broken so often (CC @tsachiherman @sreuland )
> soroban-rpc: Fix upstert  bug in DB cache

- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/db/transactionalcache.go
- cmd/soroban-rpc/internal/methods/get_latest_ledger_test.go
- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/preflight/preflight_test.go
As a followup to #837 , also cache all entries queried from the DB in a read transaction.
To have finer control over caching, a new contructor (`NewCachedTx`) has been added. This allows disabling caching in situations in which the cache size could grow out of hand.
The preflight library (which in turn depends on rs-env-host) sometimes queries the same entry more than once.
The performance improvement is not huge, but it allows us to be more flexible on the preflight library, not needing to be careful about querying the same entry multiple times.
Also note that the benchmark is pretty naive and doesn't query a lot of ledger entries from the DB.
Before:
```
goos: darwin
goarch: arm64 …
```
> soroban-rpc: Cache all ledger entries queried from DB in read transaction

- Cargo.lock
- cmd/crates/soroban-test/tests/it/invoke_sandbox.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/config/identity/address.rs
- cmd/soroban-cli/src/commands/config/identity/fund.rs
- cmd/soroban-cli/src/commands/config/identity/generate.rs
- cmd/soroban-cli/src/commands/config/identity/mod.rs
- cmd/soroban-cli/src/commands/config/mod.rs
- cmd/soroban-cli/src/commands/config/network/mod.rs
- cmd/soroban-cli/src/commands/config/secret.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/fund.rs
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/rpc/mod.rs
- docs/soroban-cli-full-docs.md
And new subcommand for funding accounts. And allow funding accounts when using `soroban config identity generate`
Remove the dependency on using tools like curl.
[TODO or N/A]
> feat(CLI): `config identity fund` to fund accounts on networks

- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- docs/soroban-cli-full-docs.md
Fixes #752
Removes the `--contract-name` argument from `bindings typescript`, since
this was often confused with `--output-dir` and, really, just using the
file path from the end of `--output-dir` is sufficient.
Adds `--overwrite`. If you specify an `--output-dir` that already
exists, by default it will not be overwritten. Instead, a descriptive error
will be thrown, letting you know that you can add `--overwrite` to
overwrite the directory.
Previously, if you specified an `--output-dir` that already existed, it
would create a new directory with the same name inside this directory,
which can lead to confusing bugs.
This approach was arrived at with @tyvdh
N/A
> feat(bindings-ts)!: rm --contract-name, add --overwrite

- Cargo.lock
- Cargo.toml
- cmd/crates/soroban-spec-tools/src/utils.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/utils/contract_spec.rs
- cmd/soroban-rpc/lib/preflight/Cargo.toml
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
Review & Update the RPC's rust dependencies
Part of https://github.com/stellar/soroban-tools/issues/791
Upgraded this repo to 0.21.2. Moved to a workspace dep since it is shared with
CLI.
Need to update stellar-xdr to match.
FFI bindings. Already on latest
Updated to 1.0.46. Moved to a workspace dep since it is shared with CLI.
Updated to 0.10.7. Moved to a workspace dep since it is shared with CLI.
Note: We only use this to convert the network_passphrase to the network_id. So we could do that in go and remove this dependency, but not sure it is worth it, since the CLI anyway.
To update separately.
> soroban-rpc: Rust dependency updates

- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/db/ledgerentry_test.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
Fix a ledger entry visibility bug introduced in #846.
Ledger Entries should be visible when `currentLedger == expirationLedgerSeq` (according to https://soroban.stellar.org/docs/fundamentals-and-concepts/state-expiration#expiration-ledger). But the code previously made it a bit unclear which ledger was LatestClosed vs Current (which led to the bug).
[TODO or N/A]
> soroban-rpc: Fix ledgerentry visibility bug

- Cargo.lock
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/lib/preflight/Cargo.toml
- cmd/soroban-rpc/lib/preflight/src/fees.rs
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
- cmd/soroban-rpc/lib/preflight/src/lib.rs
- cmd/soroban-rpc/lib/preflight/src/preflight.rs
- cmd/soroban-rpc/lib/preflight/src/state_expiration.rs
* Split out FFI conversions from actual preflight computations. I added a new file `preflight.rs` which contains the actual preflight computations, separate from the `Go<->Rust` ffi interfacing (which is the only thing left in `lib.rs`).
* Use the [`anyhow`](https://docs.rs/anyhow/latest/anyhow/) crate to:
* Make error handling more readable (`Result<R, Box<dyn Error>>` vs `Result<R>`)
* Add context to errors ( Closes https://github.com/stellar/soroban-tools/issues/858).
* Some other minor changes, making the code more idiomatic/readable.
* Fix a couple of memory leaks in `free_preflight_result()`
> soroban-rpc: refactor libpreflight

- cmd/soroban-rpc/lib/preflight/src/lib.rs
I understand this can be controversial, but there are good reasons for it. I intentionally created a separate followup PR from #875 in case it meets a strong opposition.
* panicking will show the line number where the problem happens whereas otherwise we will get an error with no context at all (as an alternative we could add context to every use of `?` but that would make the code much more unreadable).
* We anyhow capture the panics before returning to Go and thus, the process won't stop.
Further context on why it's OK to use unwrap in these cases https://blog.burntsushi.net/unwrap/
Ideally we would simply have a way to selectively attach a backtrace/line-number to these errors instead, but I don't think that will be possible until https://github.com/rust-lang/rust/issues/53487 lands. …
> soroban-rpc: libpreflight: unwrap() errors due to bugs in the Go<->Rust interface

- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/internal/preflight/preflight_test.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight/src/fees.rs
- cmd/soroban-rpc/lib/preflight/src/lib.rs
- cmd/soroban-rpc/lib/preflight/src/preflight.rs
Even if `host.invoke_host_function()` fails, leading to an error, we can collect and return diagnostic events.
Note that this implies that the events field of the simulate transaction response can be set when an error is returned.
Also, sneak in some review feedback from #875 which I incorrectly pushed to this branch (sorry @tsachiherman )
(Found out about it in https://github.com/stellar/rs-soroban-env/issues/1008 ).
@willemneal we should probably do the same in the CLI's snapshot mode (in case we don't do it already).
> soroban-rpc: simulateTransaction: try to return diagnostic events on failure

- cmd/soroban-rpc/internal/preflight/preflight_test.go
Also, clean up the benchmark configuration and remove unrealistic reuse of DB read transactions between invocations
> soroban-rpc: expand getpreflight benchmarks

- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/db/transactionalcache.go
- cmd/soroban-rpc/internal/preflight/preflight_test.go
The current ledger-entry write-through cache is not very useful as it stands because it's only updated when we process updates in config settings.
Updates in config settings will be infrequent, this means once we restart soroban-rpc after a network reset, the cache will be empty.
To solve this, we also update the missing setting ledger entries on reads
before:
```
goos: darwin
goarch: arm64
BenchmarkGetPreflight/In-memory_storage
BenchmarkGetPreflight/In-memory_storage-12                  4950            238374 ns/op
BenchmarkGetPreflight/DB_storage
BenchmarkGetPreflight/DB_storage-12                         3723            305137 ns/op
BenchmarkGetPreflight/DB_storage,_restarting …
```
> soroban-rpc: Add missing config settings in ledger entry cache on reads

- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/preflight/preflight.go
- cmd/soroban-rpc/lib/preflight.h
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
- cmd/soroban-rpc/lib/preflight/src/lib.rs
Addresses most of #367 
It doesn't yet address  this though, which is hard since, in order to check expirations, we sometimes need to unmarshallthe entry anyways. I will revisit this when once the new expiration changes land.
> The ledger entry is obtained from the DB in binary-serialized XDR
Before:
```
goos: darwin
goarch: arm64
BenchmarkGetPreflight/In-memory_storage
BenchmarkGetPreflight/In-memory_storage-12         	    4802	    239106 ns/op
BenchmarkGetPreflight/DB_storage
BenchmarkGetPreflight/DB_storage-12                	    3680	    304496 ns/op
BenchmarkGetPreflight/DB_storage,_restarting
BenchmarkGetPreflight/DB_storage,_restarting-12    	    3664	    304327 ns/op …
```
> soroban-rpc: libpreflight: Remove base64 encoding between Go and Rust

- cmd/soroban-rpc/internal/preflight/preflight_test.go
* ~Add walllock benchmark metric~
* Exclude db startup from the benchmark
> soroban-rpc: GetPreflight benchmark tweaks

- cmd/soroban-rpc/internal/db/ledgerentry.go
🤦 
This, by itself, doesn't really improve the preflight times though:
before:
```
goos: darwin
goarch: arm64
BenchmarkGetPreflight/In-memory_storage
BenchmarkGetPreflight/In-memory_storage-12         	    7117	    166782 ns/op
BenchmarkGetPreflight/DB_storage
BenchmarkGetPreflight/DB_storage-12                	    4789	    227984 ns/op
BenchmarkGetPreflight/DB_storage,_restarting
BenchmarkGetPreflight/DB_storage,_restarting-12    	    5048	    227909 ns/op
BenchmarkGetPreflight/DB_storage,_no_cache
BenchmarkGetPreflight/DB_storage,_no_cache-12      	    2773	    425975 ns/op
PASS
```
after:
```
goos: darwin
goarch: arm64 …
```
> soroban-rpc: Fix caching of GetLatestLedgerSequence

- cmd/soroban-rpc/internal/db/db.go
- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/db/ledgerentry_test.go
1. Cache statement preparation of `GetLedgerEntries()`
2. Make caching of the `GetLatestLedger()` write-through. This should allow us to only query the latestLedger a maximum of once per run of soroban-rpc.
before:
```
goos: darwin
goarch: arm64
pkg: github.com/stellar/soroban-tools/cmd/soroban-rpc/internal/db
BenchmarkGetLedgerEntry
BenchmarkGetLedgerEntry/With_cache,_include_expired
BenchmarkGetLedgerEntry/With_cache,_include_expired-12         	   19622	     61162 ns/op
BenchmarkGetLedgerEntry/With_cache,_exclude_expired
BenchmarkGetLedgerEntry/With_cache,_exclude_expired-12         	   16340	     72964 ns/op
BenchmarkGetLedgerEntry/Without_cache,_exclude_expired
BenchmarkGetLedgerEntry/Without_cache,_exclude_expired-12      	    4460	    270240 ns/op
pkg: …
```
> soroban-rpc: further DB querying performance tweaks

- Cargo.lock
- cmd/crates/soroban-test/tests/it/dotenv.rs
- cmd/crates/soroban-test/tests/it/main.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/bin/main.rs
Before parsing with clap load in variables found in a .env file. This will allow directories to set, 
- `SOROBAN_NETWORK`
- `SOROBAN_RPC_URL`
- `SOROBAN_NETWORK_PASSPHRASE`
- `SOROBAN_LEDGER_FILE`
- `SOROBAN_EVENTS_FILE`
- `SOROBAN_ACCOUNT`
- `SOROBAN_CONTRACT_ID`
- `SOROBAN_FEE`
To allow tests to use `.env` to setup the CLI calls. Went with `dotenvy` since `dotenv` is unmaintained.
[TODO or N/A]
> feat(CLI): add dotenv so directories can now set CLI args

- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/internal/db/ledger.go
- cmd/soroban-rpc/internal/db/ledger_test.go
- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/ledgerbucketwindow/ledgerbucketwindow.go
- cmd/soroban-rpc/internal/methods/get_latest_ledger_test.go
This halves the startup ledger memory requirements (since we don't no longer need to store all the ledgers in memory before initializing the stores).
Addresses part of https://github.com/stellar/soroban-tools/issues/554
> soroban-rpc: Stream ledgers on initialization

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/config/events_file.rs
This updates to the newest version of `chrono` and updates the deprecated API.
CI seems to ignore the lockfile or update it? Perhaps `--frozen` should be added somewhere.
This causes the chrono crate to update and then cause a deprecation error. 
see #906 & #867 
Still need to update CI to not update Cargo.lock
> fix: datetime api deprecation error

- cmd/crates/soroban-test/tests/it/plugin.rs
- cmd/soroban-cli/src/bin/main.rs
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/plugin.rs
> fix(CLI): move plugin logic to Root and pass clap error if plugin's name is close to a built-in subcommand

- cmd/soroban-rpc/lib/preflight/src/fees.rs
Increase instruction leeway to 20% from 15%
A Horizon test was failing due to not enough instructions being provisioned https://github.com/stellar/go/pull/5023#issuecomment-1699419628
The problem appeared after updating Core/rs-soroban-env at https://github.com/stellar/soroban-tools/pull/884 but I have no idea of why the preflight provisioning stopped being sufficient nor whether 20% will be good enough.
> soroban-rpc: preflight: Increase instruction leeway to 20%

- cmd/crates/soroban-test/tests/it/custom_types.rs
- cmd/soroban-cli/src/bin/main.rs
set the exit code to 1 in case of an error
see https://github.com/stellar/soroban-tools/issues/920
n/a
> soroban-cli: set the exit code to 1 in case of an error

- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight/src/fees.rs
Core stopped including including them
Followup from https://github.com/stellar/soroban-tools/pull/913#discussion_r1313608612
> soroban-rpc: preflight: remove key sizes from read_bytes computation

- .github/workflows/soroban-rpc.yml
- cmd/crates/soroban-test/tests/it/invoke_sandbox.rs
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
Invoke the rust CLI from a go integration test
This will allow testing the CLI against the same RPC server in the repo and not rely on quickstart.
[TODO or N/A]
> feat: try invoking CLI from go test

- cmd/soroban-cli/src/commands/lab/token/wrap.rs
9615897821492671f951169f8f442d69cafb3d81
```console
❯ soroban version
soroban 0.9.4 (v0.9.5-70-g9615897821492671f951169f8f442d69cafb3d81)
soroban-env 0.0.17 (eb5a9ba053a7b64a8eff605db625525378f7bea0)
soroban-env interface version 85899345977
stellar-xdr 0.0.17 (39904e09941046dab61e6e35fc89e31bf2dea1cd)
xdr next (65afa63b7f52c898143ebbe9541ef91fcf290ade)
```
```console
❯ soroban lab token wrap --asset ABC:GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHF
```
I expect the Stellar Asset contract to be deployed resulting in a contract address being outputted.
For example:
```
CBMLAIHYS74DMIS5PXB5SH3KL2N3TRHU5IEYNLDINFPNX5Y3ERMWLANJ
```
```
error: xdr processing error: xdr value invalid
```
The same command works with the RPC, so this issue appears to be isolated to the sandbox …
> soroban-cli: wrap token fails with valid inputs in sandbox mode

- cmd/soroban-rpc/internal/jsonrpc.go
restore CORS support
In https://github.com/stellar/soroban-tools/pull/584, we removed the support for CORS. 
This PR restore the CORS support.
n/a
> soroban-rpc: restore CORS support

- cmd/soroban-rpc/internal/test/cors_test.go
In https://github.com/stellar/soroban-tools/pull/943, we added CORS support. This PR test to see that the CORS support works as intended.
Need to verify the CORS support works.
n/a
> soroban-rpc: add CORS test

- cmd/crates/soroban-test/tests/it/contract_sandbox.rs
add `contract build` unit test for soroban-cli.
making sure to cover all existing functionality.
n/a
> soroban-cli: add contract build unit test

- cmd/soroban-rpc/internal/test/get_ledger_entries_test.go
- cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/internal/test/transaction_test.go
The first commit fixes failing integration tests caused by a change in the [host](https://github.com/stellar/rs-soroban-env/pull/1053/files). Now, the contract upload operation will validate that the wasm is actually valid. This change in behavior broke our integration tests because in some of our tests we upload contracts with a junk binary payload.
The second commit fixes TestSimulateTransactionSucceeds by updating the fee related fields in `expectedTransactionData`.  I'm not sure if this is the appropriate fix or if this is a sign that we need to update the preflight lib to be consistent with core.
[N/A]
> soroban-rpc: Fix integration tests

- cmd/soroban-rpc/internal/network/requestdurationlimiter.go
Fix data race #959 .
When implementing `bufferedResponseWriter.WriteOut`, I attempted to implement the writing to the output stream asynchronously, so that in case of context expiration the writing to the channel would be suspended at once.
Unfortuntally, it led to conflict with go http server library : When the `bufferedResponseWriter.WriteOut` could not complete writing to the stream in time, the method would return. However, the writing operation was still going on it's own pace.
then, the http server was attempting to write to the stream, creating a data race.
The solution is to write to the stream in smaller chunks, and continuously check the ctx.Err in order to examine when it expires.
n/a
> soroban-rpc: fix datarace in bufferedResponseWriter.WriteOut

- Cargo.lock
- cmd/crates/soroban-test/tests/fixtures/test-wasms/hello_world/src/lib.rs
- cmd/crates/soroban-test/tests/it/contract_sandbox.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight/Cargo.toml
- cmd/soroban-rpc/lib/preflight/src/preflight.rs
Set base prng to zero in preflight and invoke.
The base prng seed need to be configured in the host for the prng host functions to work. Without it being set invocatinos of contract functions that use the prng will fail, and simulations will also.
```[tasklist]
```
> Set base prng to zero in preflight and invoke

- Cargo.lock
- cmd/crates/soroban-spec-tools/src/lib.rs
- cmd/crates/soroban-test/tests/it/contract_sandbox.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/bump.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- cmd/soroban-cli/src/commands/contract/read.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/key.rs
- cmd/soroban-cli/src/lib.rs
- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-rpc/internal/test/cli_test.go
- docs/soroban-cli-full-docs.md
Created a new args struct for creating ledger keys. Also adds a new method and new types to the `rpc`, which helps return a struct containing an entry's expiration. 
- Now durability is required, but we could could persistent as the default, as I'm sure it will be for most people.
- I also picked a max ledgers to bump based on trial and error, but could use on official one.
- And in the case where the ledger is before the expiration, the current expiration is returned. 
- Also updated read command to return the current expiration, though could use feedback on updating args if needed.
fix #969
[TODO or N/A]
> Feat(CLI): add `key::Args` and `FullLedgerEntry`/`FullLedgerEntries`

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/config/identity/address.rs
- cmd/soroban-cli/src/commands/config/mod.rs
- cmd/soroban-cli/src/commands/config/secret.rs
- cmd/soroban-cli/src/commands/contract/bump.rs
- cmd/soroban-cli/src/commands/contract/deploy.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/commands/lab/token/wrap.rs
- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-cli/src/rpc/transaction.rs
- cmd/soroban-cli/src/utils.rs
update ed25519-dalek from 1.0.1 to 2.0.0.
Use latest security primitives.
Versions prior to 2 have a vulnerability when generating signature with different public keys and the same private key: https://rustsec.org/advisories/RUSTSEC-2022-0093.
n/a
> soroban-cli: upgrade ed25519-dalek to version 2.0.0

- cmd/crates/soroban-test/tests/it/integration_and_sandbox.rs
> fix(CLI): ignore the expiration in contract_read test

- cmd/crates/soroban-test/tests/fixtures/test-wasms/hello_world/src/lib.rs
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight/src/fees.rs
Include size of system events in fee estimation. They were removed at #844 
I interpreted  from @dmkozh at https://github.com/stellar/soroban-tools/pull/884#discussion_r1305729009 they had to be removed
Fixes #985
N/A
> rpc: preflight: include system events in fee calculation

- .cargo-husky/hooks/pre-commit
- .cargo-husky/hooks/pre-push
- .github/actions/setup-integration-tests/action.yml
- .github/workflows/soroban-rpc.yml
- cmd/crates/soroban-test/tests/fixtures/test-wasms/udt/src/lib.rs
- cmd/soroban-rpc/lib/preflight/src/fees.rs
- cmd/soroban-rpc/lib/preflight/src/ledger_storage.rs
- cmd/soroban-rpc/lib/preflight/src/lib.rs
- cmd/soroban-rpc/lib/preflight/src/preflight.rs
- cmd/soroban-rpc/lib/preflight/src/state_expiration.rs
Ensure that clippy used across repo. Also use an action and split CLI integration tests from normal ones. 
Consistency and make git hooks.
[TODO or N/A]
> fix: clippy --all

- .gitignore
- cmd/soroban-rpc/README.md
This PR adds a README.md to soroban-rpc detailing steps to build it from source.
Some partners have requested building the rpc server from source and currently there is no such documentation for it.
N/A
> soroban-rpc: Add a "Building from Source" README.md

- cmd/soroban-cli/src/commands/config/identity/address.rs
> fix(CLI): fund command now can accept a public strkey

- cmd/soroban-rpc/internal/events/cursor.go
Datartype is casted incorrectly.
trivial bug.
n/a
> fix potential overflow

- .github/workflows/dependency-check.yml
- .github/workflows/golangci-lint.yml
- .github/workflows/soroban-rpc.yml
- go.mod
- go.sum
Note that this PR enforces Go 1.21 transitively due to dependencies (at least github.com/creachadair/jrpc2) enforcing Go 1.21
> Run go mod tidy

- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-rpc/internal/methods/get_ledger_entries.go
The diff is self-explanatory: this appears to be a typo.
> Fix typo in JSON-encoded field for a `getLedgerEntries` result

- cmd/soroban-rpc/internal/ingest/service.go
When stopping soroban-rpc, it would generate a benign warning message:
```
WARN[2023-10-26T11:49:39.561-04:00] could not rollback fillEntriesFromCheckpoint write transactions  error="transaction has already been committed or rolled back" pid=20799
```
The underlying transaction was already rolled back by the database session. There is no need to roll it back again.
Given that this is the exception rather then the rule, I've silenced this particular case.
n/a
> soroban-rpc: remove noisy rollback message

- cmd/soroban-rpc/docker/Dockerfile
updated Dockerfile to use go 1.21
Dockerfile won't build with go 1.20
> update Dockerfile to go 1.21

- cmd/soroban-rpc/internal/daemon/metrics.go
- cmd/soroban-rpc/internal/events/events.go
- cmd/soroban-rpc/internal/ingest/service.go
- cmd/soroban-rpc/internal/jsonrpc.go
- cmd/soroban-rpc/internal/preflight/pool.go
- cmd/soroban-rpc/internal/transactions/transactions.go
This PR explicitly supplies objectives in Prometheus.SummaryOpts because the new version of the Prometheus go client no longer provides the default value.
In previous versions of the Prometheus go client, default objectives were automatically provided in prometheus.SummaryOpts. However, this was [deprecated](https://github.com/prometheus/client_golang/pull/262/files) in [version 1.0.0.](https://github.com/prometheus/client_golang/blob/main/CHANGELOG.md#100--2019-06-15)
N/A
> Explicitly supply objectives in Prometheus SummaryOpts

- cmd/crates/soroban-test/tests/it/integration/util.rs
- cmd/soroban-cli/src/commands/contract/deploy.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-rpc/internal/test/cli_test.go
- docs/soroban-cli-full-docs.md
This PR adds a check to the `soroban contract deploy` command if the Rust SDK version used to compile it is a release candidate SDK version.
If the new flag `--ignore-checks` is present, a warning is displayed. Otherwise, the command will return an error.
Release candidate versions of the Soroban Rust SDK are not suitable for use with the Stellar Public Network. We should at the very least warn users if they are deploying contracts compiled with release candidate SDK versions.
Closes #941
> soroban-cli: Warn or Error When Deploying Contracts Compiled with RC Version of Soroban SDK

- .github/workflows/soroban-rpc.yml
- Cargo.lock
- Cargo.toml
- cmd/soroban-rpc/internal/config/options.go
- cmd/soroban-rpc/internal/test/docker-compose.yml
- cmd/soroban-rpc/lib/preflight/Cargo.toml
Update Rust/Core dependencies and enable preflight debug by default.
Debug was disabled by default before since there wasn't a budget for it. Now (in the latest rs-env Rust library updates there is)
NA
> rpc: preflight: enable debug by default now that there is a debug budget

- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-cli/src/rpc/txn.rs
This renames the `transaction` module to `txn`. Adds `txn::Assembled`. `Assembled` handles the different steps in preparing a transaction to be submitted. This is the first step in allowing intermediate transactions be returned and externally signed.
Also in improving error messages from failed transactions.
> feat(CLI): Assembled Transaction that handle preparing transaction post simulation

- cmd/crates/soroban-spec-typescript/src/lib.rs
- cmd/crates/soroban-test/tests/it/arg_parsing.rs
It was complaining about some unnecessary hashes around raw strings.
See https://rust-lang.github.io/rust-clippy/master/index.html#needless_raw_string_hashes
> cli: Appease new clippy version

- cmd/soroban-rpc/internal/db/ledgerentry.go
- cmd/soroban-rpc/internal/methods/get_ledger_entries.go
- cmd/soroban-rpc/internal/test/get_ledger_entries_test.go
Closes https://github.com/stellar/soroban-tools/issues/1084 
The key->entry correspondence was broken since the code assumed a 1-to-1 match (in size and ordering) between the keys in the request and the keys in the response.
This didn't hold because:
1. Some keys may be missing in the response (if not found in the db).
2. The db access method (`LedgerEntryReadTx.GetLedgerEntries()`) returned a result whose ordering wasn't consistent with its arguments (due to traversing a map to build the result).
This change:
1. Fixes the key->entry mapping
2. Makes `getLedgerEntries` response ordering stable and consistent with the keys provided.
3. Make a few small performance improvements (mostly allocation related) along the way.
4. Increases test coverage.
> rpc: fix multi-entry responses for getLedgerEntries method

- cmd/soroban-rpc/internal/config/config.go
- cmd/soroban-rpc/internal/config/options.go
- cmd/soroban-rpc/internal/config/test.soroban.rpc.config
- cmd/soroban-rpc/internal/config/toml_test.go
- cmd/soroban-rpc/internal/daemon/daemon.go
- cmd/soroban-rpc/internal/test/integration.go
This PR removes the `--captive-core-use-db` flag and forces on-disk mode.
Eventually, the core working-state size will grow, and eventually get too big for RAM. This means in-memory captive-core will not work long-term. Therefore, we should force users to use on-disk mode.
> soroban-rpc: Force On-Disk Mode by Removing --captive-core-use-db

- cmd/soroban-rpc/internal/methods/get_ledger_entries.go
- cmd/soroban-rpc/internal/methods/get_ledger_entry.go
- cmd/soroban-rpc/internal/methods/send_transaction.go
- cmd/soroban-rpc/internal/methods/simulate_transaction.go
This reverts commit 1ee4113b88fb49e9b3ad2aec8700b4d53473efe7 and updates stellar/go to https://github.com/stellar/go/pull/5116
> rpc: Sanity-check allocations when decoding

- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/version.rs
Make output of any way to get at the version consistent.
We should have one version output for folks to provide consistent version info when reporting bugs.
Close #795
> Make output consistent for all ways to get version

- cmd/soroban-cli/src/rpc/mod.rs
- cmd/soroban-rpc/internal/methods/get_events.go
- cmd/soroban-rpc/internal/methods/get_events_test.go
- cmd/soroban-rpc/internal/methods/get_latest_ledger.go
- cmd/soroban-rpc/internal/methods/get_ledger_entries.go
- cmd/soroban-rpc/internal/methods/get_ledger_entry.go
- cmd/soroban-rpc/internal/methods/get_network.go
- cmd/soroban-rpc/internal/methods/get_transaction.go
- cmd/soroban-rpc/internal/methods/send_transaction.go
- cmd/soroban-rpc/internal/methods/simulate_transaction.go
- cmd/soroban-rpc/internal/test/get_ledger_entries_test.go
- cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
Closes https://github.com/stellar/soroban-tools/issues/1081
Consistent is good plus it's cleaner to not stringify fields we don't need to (since they can be treated by javascript).
Downstream tickets are needed.
> rpc: unify all ledger sequence types to uint32 and stop stringyfying integers < 53-bits wide

- cmd/soroban-cli/src/rpc/mod.rs
`soroban events` takes a `uint32` for the `start-ledger` param. We should not convert it to a string before calling the RPC endpoint.
> Don't Convert Start Ledger to String for Events Command

- .github/workflows/e2e.yml
rebased the e2e updates to be applicatble to the the release/v20.0.2
should enable test coverage
> cherry pick the e2e updates for 20.0.2

- cmd/soroban-rpc/lib/preflight/src/fees.rs
increase the instruction budget padding on preflight fees calc
allows more complex contracts with higher compute to still get through preflight w/o fees error.
> increased the instruction padding for preflight fees to 3 million

- cmd/soroban-rpc/internal/test/simulate_transaction_test.go
- cmd/soroban-rpc/lib/preflight/src/fees.rs
increased the instruction fee padding during preflight to 3 million to accommodate new v20 cost model and more complex contracts that use more compute.
avoid preflight fees failure on contracts that used to work pre-v20
[TODO or N/A]
> hot fix v20.0.2, increased preflight instruction fee padding to 3 million

- scripts/check-dependencies.bash
> scripts/check-dependencies: Add support for crate versions

- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/assembled-tx.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/assembled-tx.js
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/assembled-tx.ts
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/src/project_template/src/assembled-tx.ts
- cmd/crates/soroban-spec-typescript/ts-tests/initialize.sh
- cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
- cmd/crates/soroban-spec-typescript/ts-tests/package.json
- update to `stellar-sdk@11.0.1`
- fetch expiration using new `getFootprint` logic
- improve `initialize.sh` to show network status
- latest RPC returns better error messages
- deal with these and parse `getHealth` response
current `bindings typescript` logic is broken with latest Futurenet &
`quickstart:soroban-dev`
Please double-check my `entryRes.entries[0].liveUntilLedgerSeq` logic in
the `getStorageExpiration` function.
> fix(bindings-ts): latest RPC & stellar-sdk

- .github/workflows/e2e.yml
bumped core ref to latest v20 tag.
so tests are accurate for latest v20 versions.
> update e2e core ref 

- .github/workflows/e2e.yml
- .github/workflows/soroban-rpc.yml
- Cargo.lock
- Cargo.toml
- cmd/soroban-rpc/internal/test/docker-compose.yml
This is a follow-up to #1160 that uses the official tags rather than the interim ones.
This is needed for #1163.
n/a
> Bump Core and dependency versions to the official tags/images.

- cmd/soroban-rpc/internal/events/cursor.go
- cmd/soroban-rpc/internal/events/events.go
- cmd/soroban-rpc/internal/events/events_test.go
1. Get rid of the in-memory operation index (since it was always set to zero anyways)
2. Keep events serialized while in memory (it saves quite a bit of space due to the inneficient representation of unions in golang).
> rpc: Reduce event memory footprint

- cmd/soroban-rpc/internal/events/events.go
- cmd/soroban-rpc/internal/events/events_test.go
- cmd/soroban-rpc/internal/methods/get_events.go
- cmd/soroban-rpc/internal/methods/get_events_test.go
Add the transaction hash pertaining to each event in the `getEvents` response
Fixes https://github.com/stellar/soroban-tools/issues/1182
It increases the size of the in-memory event storage (but this should be mitigated by #1183 )
It would be good to have specific numbers (@psheth9 is working on it)
> rpc: Store and serve the event transaction ID

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/init.rs
Embed the contract_init_template files in the binary using `rust-embed` to make sure that they are accessible to the `init` command to copy to the user's filesystem.
Fixes the issue reported here: https://discord.com/channels/897514728459468821/1204799895014346842/1204799895014346842
> fix: embed the init template files in the build

- .github/workflows/e2e.yml
- Cargo.lock
- Cargo.toml
We need to bump these versions because fee padding fix available in the latest release of rpc [here](https://github.com/stellar/soroban-rpc/releases/tag/v20.3.3)
> Bump version of soroban rpc and spec tools

- Makefile
- cmd/soroban-cli/src/commands/contract/optimize.rs
Change the install make target to use the lock file, by adding --locked to all cargo install commands. Also encourage --locked usage elsewhere in CLI help output, and fix old make targets that are no longer needed since the split.
Cargo install won't use the Cargo.lock file at all unless the --locked option is passed. This means that installs in CI are pulling in whatever the latest versions of software that match the Cargo.toml specification. This allows any developer of any dependency to have control over what runs in CI, or on developer machines. It is the main reason to rely on the Cargo.lock file and only update the lock file intentionally.
Cargo build automatically uses the lock file and only modifies it if it needs modifying. Install is one command that unfortunately doesn't use …
> Make builds and tests consistent

- docs/soroban-cli-full-docs.md
Add new `eth-abi` example contract to the docs.
Because building the docs automatically adds it now, and other builds will fail until we merge this one.
[TODO or N/A]
> chore: update docs with new possible example contract

- cmd/soroban-cli/src/commands/contract/init.rs
Returns to hardcoding the examples until we make the check compile time
[TODO or N/A]
> fix: #1229

- cmd/soroban-cli/src/commands/contract/invoke.rs
- docs/soroban-cli-full-docs.md
Change the cli --is-view env var to be `SOROBAN_INVOKE_VIEW` instead of `SYSTEM_TEST_VERBOSE_OUTPUT`, retaining support for the previous env var for backwards compatibility.
In #1194 when the env var was added it appears we accidentally named it a name that doesn't have anything to do with the option. The env var is actually the name of an env var used in the system test suite, so I'm going to guess that a find all and rename went awry and maybe renamed an env var here that shouldn't have been.
At the moment two env vars are attached to the option, and only the second one appears to be useable in my testing, as the second env parameter overrides the first.
This change is not a breaking change and can be released in a patch release as a bug fix.
The old env var is not advertised in the …
> Fix option --is-view env var

- cmd/soroban-cli/src/commands/mod.rs
- docs/soroban-cli-full-docs.md
I noticed when running `soroban` or `soroban --help` the github repo link was still pointing to `stellar/soroban-tools`. So, I changed that, and I added the `/docs` path to the `soroban.stellar.org` URL while I was at it (since there's no landing page at the `/` root path)
> docs: update URLs displayed in the "about" command

- cmd/soroban-cli/src/commands/network/mod.rs
This fixes a issue caused by quotes around the friendbot url caused by using Debug `{uri:?} instead of Display `{uri}`.
> fix: #1251

- .github/workflows/rust.yml
- cmd/crates/soroban-test/tests/it/config.rs
- cmd/soroban-cli/src/commands/network/mod.rs
Remove exception when trying to run `soroban keys generate` on windows.
So we can properly fund testnet accounts on Windows.
N/A
> Do not raise error when trying to fund account on windows.

- cmd/soroban-cli/src/utils/contract-init-template/contracts/hello_world/Cargo.toml.removeextension
Update Cargo.toml template to use generic values.
So it's generic and not tied to SDF. Also update the contract name to match what's currently in our docs.
N/A
> Update Cargo.toml template.

- cmd/soroban-cli/src/commands/contract/init.rs
We're moving to use stellar/soroban-astro-template instead.
So everything is under SDF's org account.
N/A
> Update astro template repo url.

- cmd/soroban-cli/src/commands/contract/init.rs
The `---` is only for the `README.md` file, not `gitignore`.
I've also switched the "(ab)used link label (for use with reference
style links)"-style comment (`[//] #`) for an HTML comment (``). This means it will be rendered in the HTML, which might be
preferable, and is at a minimum benign. I hadn't been familiar with the
`[//]: #`-style comment until I saw it here (and searched to find a
description of it, along with the "(ab)use" line above, [here]), and I
don't think it's worth the potential confusion for users of `soroban
contract init`.
[here]: https://stackoverflow.com/a/20885980/249801
> fix(init): don't gitignore triple-dash

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/init.rs
When initializing a new project with `soroban contract init`, we need to
clean up the `Cargo.toml` of example projects a little. We need to make
sure `soroban-sdk` is always inherited from the workspace, and we need
to make sure there's no `profile` section.
We had a couple issues with the old logic.
1. It was adding a `dev_dependencies` section, with an underscore, which
is deprecated. If the Cargo.toml already had a `dev-dependencies`
section, it would add a second `dev_dependencies`, which cargo would
complain about.
2. The new setting would only set `{ workspace = true }`, even if the
old one included other details like `features = ['testutils']`.
This adds a new crate, `cargo_toml`, which allows us to parse and
manipulate Cargo.toml files in a more sophisticated way, which allows us …
> fix(init): don't add two `dev_dependencies` sections

- cmd/soroban-cli/src/commands/contract/optimize.rs
Removed output line in optimization saying that a file will be written.
```console
$ soroban contract optimize --wasm ./out/webauthn_factory.wasm
Reading: ./out/webauthn_factory.wasm (661 bytes)
Writing to: ./out/webauthn_factory.optimized.wasm...
Optimized: ./out/webauthn_factory.optimized.wasm (586 bytes)
```
```console
$ soroban contract optimize --wasm ./out/webauthn_factory.wasm
Reading: ./out/webauthn_factory.wasm (661 bytes)
Optimized: ./out/webauthn_factory.optimized.wasm (586 bytes)
```
It is immediately followed with an output line that the file has been written, and the duplicate lines is unnecessary noise in the output.
> Removed extra output line in optimization

- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
Full release notes at https://github.com/stellar/js-stellar-sdk/releases/tag/v12.0.0-rc.1 and Full release notes at https://github.com/stellar/js-stellar-sdk/releases/tag/v12.0.0-rc.2
Highlights:
- ContractClient now properly handles methods that take no arguments by making MethodOptions the only parameter, bringing it inline with the types generated by Soroban CLI's soroban contract bindings typescript
- ContractClient now allows publicKey to be undefined
- SentTransaction will only pass allowHttp if (and only if) its corresponding AssembledTransaction#options config allowed it
- The **default timeout for transaction calls is now set to 300 seconds (5 minutes)** from the previous default of 10 seconds. 10 seconds is often not enough time to review transactions before signing, especially …
> feat: update TS Bindings stellar-sdk dep to 12rc2

- cmd/crates/soroban-spec-tools/src/lib.rs
- cmd/crates/soroban-test/src/lib.rs
- cmd/crates/soroban-test/tests/it/integration/hello_world.rs
- cmd/crates/soroban-test/tests/it/integration/util.rs
- cmd/crates/soroban-test/tests/it/util.rs
- cmd/soroban-cli/src/commands/contract/deploy/asset.rs
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
- cmd/soroban-cli/src/commands/contract/extend.rs
- cmd/soroban-cli/src/commands/contract/fetch.rs
- cmd/soroban-cli/src/commands/contract/id/asset.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/contract/read.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/commands/events.rs
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/txn_result.rs
- cmd/soroban-cli/src/fee.rs
- cmd/soroban-cli/src/lib.rs
- cmd/soroban-cli/src/wasm.rs
- docs/soroban-cli-full-docs.md
Fixes #1265.
Requires: #1173 
Commands that build transactions now include the following args to output and exit early:
For example,
```
soroban contract invoke --build-only .. -- hello --world world
```
prints:
[`
AAAAAMwWyQMtAWO6nW4s+cKMRunx+kiaKfjJwIRNZEEclDvRAAAAZAAIgAEAAAANAAAAAAAAAAAAAAABAAAAAAAAABgAAAAAAAAAAQ3DO777M8sdGtPbMau+cuxAles4UILfUkZXOWTsqKvOAAAABWhlbGxvAAAAAAAAAQAAAA8AAAAFd29ybGQAAAAAAAAAAAAAAA==
`](https://laboratory.stellar.org/#xdr-viewer?input=AAAAAMwWyQMtAWO6nW4s+cKMRunx+kiaKfjJwIRNZEEclDvRAAAAZAAIgAEAAAANAAAAAAAAAAAAAAABAAAAAAAAABgAAAAAAAAAAQ3DO777M8sdGtPbMau+cuxAles4UILfUkZXOWTsqKvOAAAABWhlbGxvAAAAAAAAAQAAAA8AAAAFd29ybGQAAAAAAAAAAAAAAA==&type=Transaction&network=test)
```
soroban contract invoke --sim-only .. -- hello --world world
``` …
> feat: add no-build option for fee::Args

- cmd/soroban-cli/src/commands/keys/ls.rs
Remove the automatically added test key from the keys list.
The test key doesn't actually exist. When using `ls` it says one exists, but when attemting to run any other keys subcommand it errors saying:
```
$ soroban keys address test
error: Failed to find config identity for test
```
The test account is created by the soroban-test framework when running the RPC tests. There's no need for it to show up in the list, as it doesn't exist normally.
> Do not auto add test account to keys

- cmd/soroban-cli/src/commands/contract/deploy/asset.rs
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
- cmd/soroban-cli/src/commands/contract/extend.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/commands/txn_result.rs
Output TransactionEnvelope instead of Transaction for --build-only
Tools should always output, and accept as input, full envelopes because otherwise other tools that the inputs/outputs are used with won’t know what type of transaction we’ve given them.
It’s a bit confusing because tools always use the term ‘transaction’ to talk about what they accept as input, but in reality when tools like the Lab and others say they accept or build a transaction, they actually mean a transaction envelope.
> Output TransactionEnvelope instead of Transaction for --build-only

- .cargo/config.toml
- .github/workflows/full-help-docs.yml
- Cargo.lock
- Cargo.toml
- FULL_HELP_DOCS.md
- Makefile
- README.md
- cmd/crates/soroban-test/tests/it/integration/hello_world.rs
- cmd/soroban-cli/src/bin/doc-gen.rs
- cmd/soroban-cli/src/cli.rs
- cmd/soroban-cli/src/commands/config/mod.rs
- cmd/soroban-cli/src/commands/contract/fetch.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/global.rs
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/network/mod.rs
- cmd/soroban-cli/src/commands/version.rs
- cmd/soroban-cli/src/fee.rs
- cmd/soroban-cli/src/lib.rs
- cmd/soroban-cli/src/utils.rs
- cmd/stellar-cli/Cargo.toml
- cmd/stellar-cli/README.md
- cmd/stellar-cli/src/bin/main.rs
- docs/README.md
Add stellar-cli crate alongside soroban-cli
Close #1187
> Add stellar-cli crate alongside soroban-cli

- cmd/soroban-cli/src/commands/network/mod.rs
Switch from `tracing::warn` to `eprintln`
It didn't make it into stderr in tests.
[TODO or N/A]
> fix: switch to stderr directly for when account already exists

- Cargo.lock
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/init.rs
This removes the `cargo_toml` dependency that I just added in https://github.com/stellar/stellar-cli/pull/1296, opting for a simpler regex-based find-and-replace for the soroban-sdk dependency changes. Previous to #1296, we used `toml_edit` for all of these modifications, but did so in a way that ignored and overwrote important fields like `soroban-sdk.features`.
The `toml_edit` approach for editing the `dependencies` and `dev_dependencies` sections was quite verbose, and insufficient to what we needed, as the tests added in #1296 and this PR illustrate. Since we know what is in all the `soroban-examples` projects (for now), I thought maybe the regex approach was sufficient, for the time being. This could prove to be too brittle in the future, though, if one of the examples changes its …
> fix(init): example contracts: keep cdylib, exclude Cargo.lock

- .cargo/config.toml
- FULL_HELP_DOCS.md
- cmd/soroban-cli/example_contracts.list
Remove the contract-ids directory from the .soroban directory prefilled in initialised contracts.
The contract-ids directory isn't used in examples, and isn't a pattern being encouraged since there are plans to add aliases.
cc @elizabethengelman 
N/A
> Remove the contract-ids dir

- FULL_HELP_DOCS.md
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/mod.rs
- cmd/stellar-cli/Cargo.toml
Rename the remaining references from soroban-cli to stellar-cli.
To match the new name.
N/A
> Update other references to stellar-cli.

- Makefile
- cmd/soroban-cli/Cargo.toml
- cmd/stellar-cli/Cargo.toml
Install the `stellar` and `soroban` CLI binaries when installing either the `stellar-cli` or `soroban-cli` crate.
In short this change is being made to improve the developer experience during the rename of the CLI.
The CLI is transitioning from being the Soroban CLI to the Stellar CLI, and with that the binary is also transitioning from being `soroban` to `stellar`. It'll take a while for that rename to reverberate through the community, docs, tutorials, video walkthroughs, etc. During that transition period this rename should be a non-event, uninteresting, boring, and zero impact. For an undetermined (read long) period of time both the `stellar-cli` and `soroban-cli` crates will be published so that if someone is following an old tutorial or docs in a blog somewhere, the install …
> Install stellar and soroban CLIs when installing either

- .github/workflows/binaries.yml
Build artifacts for both stellar-cli and soroban-cli
Both the stellar-cli and soroban-cli are published, but the binary artifacts produced and uploaded to the release are currently only the soroban-cli. Both should be uploaded.
> Build artifacts for both stellar-cli and soroban-cli

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/completion.rs
Updates the completion script to match "stellar" instead of "soroban"
Self explanatory 
N/A
> Update completions to use stellar instead of soroban

- Cargo.lock
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
- cmd/crates/soroban-spec-typescript/src/lib.rs
- cmd/crates/soroban-test/tests/fixtures/test-wasms/custom_account/Cargo.toml
- cmd/crates/soroban-test/tests/fixtures/test-wasms/custom_account/src/lib.rs
- cmd/crates/soroban-test/tests/it/integration/bindings.rs
- cmd/crates/soroban-test/tests/it/integration/util.rs
Exclude functions starting with `__` from the typescript bindings Client methods.  Fix for https://github.com/stellar/stellar-cli/issues/1344
These functions are intended to only be run by the host, they may contain names like `Context` which cannot be imported by the client. 
N/A
> Fix: exclude host only functions from client

- cmd/crates/soroban-spec-typescript/src/lib.rs
Fixes a bug introduced in https://github.com/stellar/stellar-cli/pull/1359
This commit: [8976b6c](https://github.com/stellar/stellar-cli/pull/1359/commits/8976b6cc5f7f91577b487871b2f240169e4eb2a2) needs to be reverted. The original logic was correct. Now all non-functions are being excluded from the typescript generation; I noticed this when working on https://github.com/stellar/stellar-cli/issues/1346 and found that no error enum was being generated. This is because its excluding all function names with __ AND its excluding all Entries that fail the function pattern match. 
none
> fix incorrect filter logic

- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
This is currently unusable as a library because you either don't define
these fields, or get yelled at because you try to define private fields
> fix: mark `deploy::wasm::Cmd` fields as public

- cmd/crates/stellar-ledger/Cargo.toml
Move testcontainers dependency under the `dev-deps` in Cargo.toml
Testcontainers is only used in testing.
We will likely want to revisit the dep mismatches so that we can use a release of testcontainers instead of a specific git sha in the future
> Move testcontainers dep to dev-deps in Cargo.toml

- .github/workflows/rust.yml
The linux arm build is failing with errors related to openssl-sys (or the underlying dependency).
> Disable ubuntu arm.

- cmd/soroban-cli/src/cli.rs
Add back soroban to tracing directive. 
With the renaming if the user is still using soroban, tracing was ignoring logs.
[TODO or N/A]
> fix: add soroban_cli  tracing directive for backwards compatibility

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/config/mod.rs
There has been no default `--source-account` since 8906a53d4 / #1086
> docs: remove "default --source" misinformation

- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
Add alias support to `stellar contract bindings typescript`.
```console
$ stellar contract bindings typescript --network standalone --global --output-dir tmp --id alice --overwrite
added 28 packages, and audited 29 packages in 878ms
5 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
> tmp@0.0.0 build
> tsc
```
So you don't have to use the contract's id.
N/A
> Add support for contract id alias on `stellar contract bindings typescript`.

- cmd/soroban-cli/src/commands/contract/fetch.rs
Add support for alias on `stellar contract fetch`.
So we can use the alias, instead of having to provide the contract id.
N/A
> Add support for alias on `stellar contract fetch`.

- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
Use a clap validator to parse the alias argument.
```console
$ stellar contract deploy --wasm ./target/wasm32-unknown-unknown/release/hello_world.wasm --network standalone --source alice --alias '!foo' --global
error: alias must be 1-30 chars long, and have only letters, numbers, underscores and dashes
```
So we can use a built-in feature.
N/A
> Use clap's validator instead.

- cmd/soroban-cli/src/commands/config/locator.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/fetch.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/events.rs
Add support for alias on `stellar events`.
So we can use the alias, instead of having to provide the contract id.
N/A
> Add support for alias on `stellar events`.

- cmd/soroban-cli/src/commands/contract/invoke.rs
typo
it's been saying "Bytes and Bytes" for almost a year now 🙃
> fix: typo: second "Bytes" should be "BytesN"

- cmd/soroban-cli/src/commands/contract/extend.rs
- cmd/soroban-cli/src/commands/contract/read.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/key.rs
Add support for alias to `stellar contract extend|read|restore`.
```console
$ stellar contract read --id alice --global --network standalone --source alice --durability persistent
LedgerKeyContractInstance,"{""hash"":""d68f72ee0e95c63263e64e1802d0bb511461e0948da7fe355bcfe16163e78b95""}",360380,2433979
$ stellar contract read --id CAYXES5COIN3UEAQ7QM6CNRKQAXGW45YHRH32GHWAMRLI5AR7PWL7OTS --global --network standalone --source alice --durability persistent
LedgerKeyContractInstance,"{""hash"":""d68f72ee0e95c63263e64e1802d0bb511461e0948da7fe355bcfe16163e78b95""}",360380,2433979
```
So users can pass in an alias, rather than the contract id.
N/A
> Add support for alias to `stellar contract extend|read|restore`.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
The original `--alias` implementation had `--force` to overwrite existing contract id aliases, but @leighmcculloch [suggested](https://github.com/stellar/stellar-cli/pull/1356#discussion_r1626762468) that it'd be better to always use the latest id. Now, @willemneal created a [ticket to add that back](https://github.com/stellar/stellar-cli/issues/1417). Until we come to a decision, let's make the flag help explicit.
So people can know that `--alias` will always store the latest contract id without asking for confirmation.
N/A
> Update alias help.

- .cargo-husky/hooks/pre-commit
Regenerate docs on pre-commit.
Right now, the full docs file is only regenerated before pushing changes, which requires you to be aware and do another commit with the changes. We should do it before commiting, so you only have to do it once.
N/A
> Regenerate docs on pre-commit.

- Cargo.lock
- cmd/crates/soroban-test/tests/it/config.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/config/locator.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/network/ls.rs
- cmd/soroban-cli/src/commands/network/mod.rs
Similar to how we support `--network futurenet` before you even set it.
No need to make people go look it up on https://developers.stellar.org/docs/reference/networks
This adds a dependency on [phf](https://crates.io/crates/phf) to construct a compile-time Map of named networks to named network settings.
It also lists default networks with the `network ls [-l]` commands, and slightly updates (fixes, really) the behavior of `network ls`. Previously, if you had a local and global network named the same thing, `network ls` would show that name twice. Now it will only show them once. When you `network ls -l`, it will show all name collisions.
```
$ stellar network ls
future
futurenet
local
testnet
mainnet
$ stellar network ls -l
Local "/Users/chadoh/code/s/cli/.soroban/network/future.toml" …
```
> feat: add (local|testnet|mainnet) default networks

- README.md
Remove brackets from around the license icon in the readme.
Not needed.
> Remove unnecessary brackets from readme

- .gitignore
- .vscode/settings.json
- cmd/crates/soroban-test/README.md
This is for developing as it will allow integration tests (hidden behind the feature flag) to be indexed by RA
> chore: ignore vscode settings

- cmd/soroban-cli/src/commands/network/mod.rs
'testnet' default was using futurenet config and vice versa
Please check if I'm correct on this
> Fixed default futurenet/testnet configs

- .github/workflows/rust.yml
Remove list of crates from publish dry run.
They are no longer required and the workflow can pickup the list of crates itself since:
- https://github.com/stellar/actions/pull/71
> Remove list of crates from publish dry run

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/events.rs
This commit removes the surrounding angle brackets from a link to the docs, turns it into a link definition, and also re-generates the full help docs file.
The syntax `<www.example.com>` will result in an MDX v3 compilation error, due to the unexpected `<` character.
Using the link definition, separated by a "blank" line works in the markdown rendering, and I've tested it (locally) when built into the docs site. The words `ledger sequence` link to the desired `page#and-anchor` in the docs.
What I **don't know** how to check is what this would appear like in the cli help itself. It could be terrible, I just don't know how to check the output from a branch.
> docs: fix markdown link to ledger header docs

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/events.rs
The ledger headers page has moved, and this commit uses the new location.
> docs: correct the URL to the ledger headers page

- cmd/soroban-cli/src/commands/network/mod.rs
- cmd/soroban-cli/src/config/network.rs
Remove windows not supported errors.
We recently did work to make the stellar-cli support windows equally with other platforms. There shouldn't be any new cases where windows isn't supported and no further use of these errors.
> Remove windows not supported errors

- Cargo.lock
Update dependency `bytes` from 1.6.0 to 1.6.1.
Installing `stellar-cli` with the `--locked` option is currently displaying a warning that one of the dependencies, `bytes` 1.6.0, has been yanked.
Usually yanks of a published version are because of something like an accidental publish so we'd want to update urgently and republish so folks can continue to use `cargo install --locked`. In this case it was just a bug fix and that crate has a different policy for yanking where bugs cause yanks too (https://github.com/tokio-rs/bytes/issues/722).
The bug fix isn't critical to the stellar-cli as far as I can tell, but without updating, cargo install displays warnings which can be worrying to users and result in them running cargo install without `--locked` which results in untested code from …
> Update bytes from 1.6.0 to 1.6.1

- cmd/crates/soroban-test/tests/it/integration.rs
- cmd/crates/soroban-test/tests/it/integration/fund.rs
- cmd/crates/soroban-test/tests/it/integration/hello_world.rs
- cmd/soroban-cli/src/config/network.rs
Update fund error handling to generically handle any error message from friendbot.
Friendbot was updated in the change below to allow funding existing accounts if their balance is below the amount that friendbot funds to:
- https://github.com/stellar/go/pull/5399
Error handling in the cli was focused on handling a specific error message. Friendbot delivers error messages that can be passed on to the developer and the cli doesn't need to handle specific cases.
Close https://github.com/stellar/stellar-cli/issues/1389
> Update fund error handling

- .github/workflows/bindings-ts.yml
- cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
- cmd/crates/soroban-spec-typescript/ts-tests/package.json
- cmd/crates/soroban-spec-typescript/ts-tests/src/util.ts
- Update the version of `stellar-sdk` used by the ts-tests
- Import and use the library correctly
- Re-add CI workflow mistakenly removed in #1207 
These tests weren't passing. There's still a couple tests here of the generated types themselves, though #1207 got it right that _most_ of these tests were moved to js-stellar-sdk itself.
Is this workflow too much trouble here to be worth it?
We _could_ generate these types entirely within JS. Maybe within stellar-sdk? Maybe within some other package, run with `npx` or similar? We'd probably want to maintain it in the stellar-sdk monorepo, if it were a monorepo. Then the CLI could just check that you've got NPM installed correctly and run `npx [whatever]`.
> fix(ts-tests): update js-stellar-sdk; use it correctly

- .github/workflows/rpc-tests.yml
- cmd/crates/soroban-test/tests/it/integration/fund.rs
- cmd/soroban-cli/src/config/network.rs
Do not error if friendbot says account already funded.
If friendbot indicated that the account is already fully funded to the starting balance, because the user's goal is to get funded, and the account is funded so it is success much the same.
Close https://github.com/stellar/stellar-cli/issues/1389#issuecomment-2258665409
> Do not error if friendbot says account already funded

- .github/workflows/e2e.yml
Update `system-test` CI workflow's versions of Quickstart image and
stellar-sdk NPM module.
They're real out of date! The version of Quickstart hasn't been updated
for three months, and the version of stellar-sdk is a major version
behind and doesn't have helpful functionality like the contract client.
This will help me fix #1500 in a way that doesn't break every other branch.
[TODO or N/A]
> build: update system-test quickstart & stellar-sdk

- cmd/soroban-cli/src/commands/network/container/start.rs
Remove short flag due to a conflict introduced by #1510.
```console
$ stellar network container start
thread 'main' panicked at /Users/fnando/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.5.8/src/builder/debug_asserts.rs:112:17:
Command start: Short option names must be unique for each argument, but '-v' is in use by both 'protocol_version' and 'verbose'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
N/A
> Remove short name, so it doesn't conflict with the verbose short name.

- .github/workflows/full-help-docs.yml
- .github/workflows/rust.yml
- FULL_HELP_DOCS.md
Require ci doc check on prs. Also use appropriate instance size for small ci jobs that do not require significant resources.
The CI doc check is something we should satisfy before merging, but at the moment it is ignored by the auto merge. Any job named 'complete' will block the auto merge.
> Require ci doc check on prs

- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/snapshot/create.rs
- cmd/soroban-cli/src/commands/snapshot/mod.rs
- cmd/soroban-cli/src/print.rs
Use rich print system instead of printing to stdout. Supersedes #1524.
So we have only one way of doing it (and also respect `--quiet`).
N/A
> Move snapshot output to the rich print system.

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/custom_types.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/print.rs
Change the recently merged (and not yet released) invoke `--send` default behavior so that by default send occurs if there are any contract events, send occurs if there is any soroban auth involved, and change the name of the default enum value to `default`.
Also add output that tells the user simulation-only has occurred automatically.
There's a bug in the code that checks if there are any events, a not that shouldn't be present, so the default behavior is sending when there are no events, rather when there are events.
Also, if auth is required it's more ambiguous to if a user would expect or not a transaction to be sent. Since read-only operations are rarely gated by auth, we can probably assume auth means the transaction should be sent, even if we can't otherwise detect a write to …
> Fix invoke send default behavior

- FULL_HELP_DOCS.md
- cmd/soroban-cli/example_contracts.list
Adds `other_custom_types` to example list (https://github.com/stellar/soroban-examples/pull/322)
Keeping list synced with the examples
N/A
> Add `other_custom_types` example

- .gitignore
- CONTRIBUTING.md
- flake.lock
- flake.nix
This PR adds a [devshell environment](https://nix.dev/tutorials/first-steps/declarative-shell.html) using [nix](https://nixos.org/guides/how-nix-works/) 
Currently, in order to develop stellar-cli locally you need to install some dependencies, and sometimes you also need to modify your `.<shell>rc` file to make your environment easy to use for development.
However, this makes switching between different branches/versions or switching between development/production builds more complicated.
This change adds a configuration for a development shell, which automatically does the following:
1. Installs all necessary dependencies (only accessible in the shell) -> rust, make, libudev, etc. without affecting your global environment. Dependencies are pinned into the lockfile. We can always update …
> Add dev shell environment

- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/network/container.rs
- cmd/soroban-cli/src/commands/network/container/start.rs
- cmd/soroban-cli/src/commands/network/container/stop.rs
- cmd/soroban-cli/src/commands/network/mod.rs
```console
$ stellar network container start testnet
ℹ️ Starting testnet network
✅ Started container
🔎 You can see logs by running `stellar network container logs testnet`
ℹ️ To stop this container, use `stellar network container stop testnet`
$ stellar network container stop testnet
ℹ️ Stopping testnet container
✅ Container has been stopped
```
So we only have one way of printing rich output everywhere.
N/A
> Move container output to the rich print system.

- cmd/soroban-cli/src/commands/network/container/start.rs
- cmd/soroban-cli/src/print.rs
Closes https://github.com/stellar/stellar-cli/issues/1354
To make sure that the user is aware if they are using an up-to-date version of the quickstart image or not, this PR adds some additional logging with that information. 
```
$ stellar network container start local
ℹ️ Starting local network
ℹ️ Pulling from stellar/quickstart
ℹ️ Digest: sha256:12d852bb5224f72415cb74624eabc2220c83cd16b2ea50646a6b078b219c430e
ℹ️ Status: Image is up to date for stellar/quickstart:testing
✅ Started container
🔎 Watch logs with `stellar network container logs local`
ℹ️ Stop the container with `stellar network container stop local`
```
```
$ stellar network container start local
ℹ️ Starting local network
⚠️ Failed to fetch image from dockerhub.
⚠️ Attempting to start local quickstart image instead. Please …
```
> Print status messages when pulling quickstart image

- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
- cmd/soroban-cli/src/commands/contract/install.rs
Update pretty print callers to use the `ln` suffix to add new lines.
Output wasn't very pretty:
[TODO or N/A]
> fix: use print.infoln, etc

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/alias.rs
- cmd/soroban-cli/src/commands/contract/alias/remove.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- cmd/soroban-cli/src/config/locator.rs
Add command to remove contract aliases.
```console
$ cat ~/.config/soroban/contract-ids/increment.json
{"ids":{"Test SDF Network ; September 2015":"CCYBGMETD5TYZJ2ZBT3JBBCWODYJJWP274JA4LX4S7JGNUNQPXZBMNUY"}}%
$ cargo run contract alias remove increment --network standalone --global
Compiling soroban-cli v21.4.1 (/Users/fnando/Projects/stellar/stellar-cli/cmd/soroban-cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.22s
Running `target/debug/soroban contract alias remove increment --network standalone --global`
ℹ️ Network passphrase: Standalone Network ; February 2017
error: no contract found with alias `increment`
$ cargo run contract alias remove increment --network testnet --global
Compiling soroban-cli v21.4.1 …
```
> Add `contract alias remove`.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/alias.rs
- cmd/soroban-cli/src/commands/contract/alias/add.rs
- cmd/soroban-cli/src/commands/contract/alias/remove.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
```console
$ cargo run contract alias add increment --id CDUQDWIBBXWYHEEROXASCIBNZOZ45WJ3EOMAGMG4VTY36O2SGQTWCM23 --network testnet --global --overwrite
Compiling soroban-cli v21.4.1 (/Users/fnando/Projects/stellar/stellar-cli/cmd/soroban-cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.09s
Running `target/debug/soroban contract alias add increment --id CDUQDWIBBXWYHEEROXASCIBNZOZ45WJ3EOMAGMG4VTY36O2SGQTWCM23 --network testnet --global --overwrite`
ℹ️ Contract alias 'increment' will reference CDUQDWIBBXWYHEEROXASCIBNZOZ45WJ3EOMAGMG4VTY36O2SGQTWCM23 on network 'Test SDF Network ; September 2015'
✅ Contract alias 'increment' has been added
$ cargo run contract alias add increment --id CALLOOCCCJRZ6AZAJSKNCTDZ766N4ANVRKRJPHC65KDV7RJCS37PS4XY --network testnet --global …
```
> Add `contract alias add`.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/alias.rs
- cmd/soroban-cli/src/commands/contract/alias/remove.rs
- cmd/soroban-cli/src/commands/contract/alias/show.rs
```console
$ cargo run contract alias show increment --network testnet --global
Compiling soroban-cli v21.4.1 (/Users/fnando/Projects/stellar/stellar-cli/cmd/soroban-cli)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 3.05s
Running `target/debug/soroban contract alias show increment --network testnet --global`
ℹ️ Contract alias 'increment' references CALLOOCCCJRZ6AZAJSKNCTDZ766N4ANVRKRJPHC65KDV7RJCS37PS4XY on network 'Test SDF Network ; September 2015'
CALLOOCCCJRZ6AZAJSKNCTDZ766N4ANVRKRJPHC65KDV7RJCS37PS4XY
$ cargo run contract alias show increment --network testnet --global > /tmp/id.txt
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.21s
Running `target/debug/soroban contract alias show increment --network testnet --global`
ℹ️ Contract alias 'increment' …
```
> Add `contract alias show`.

- cmd/crates/soroban-test/tests/it/help.rs
- cmd/soroban-cli/src/commands/contract/arg_parsing.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
Technically this is a breaking change because of the Error type change, but not from CLI perspective
> chore: move custom arg parsing to separate module for reuse

- cmd/soroban-cli/src/commands/contract/extend.rs
- cmd/soroban-cli/src/commands/contract/read.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/key.rs
Currently for the commands that used `key::Args`, the contract was resolved even if it wasn't required to generate the ledger keys involved.
fixes: #1557
> fix: only resolve contract alias if needed when generating ledger keys

- cmd/soroban-cli/src/commands/contract/init.rs
It was marked as `pub` so the checker didn't tell us it was unused.
But it's not used anywhere else in the codebase.
> chore: remove unused `enum FrontendTemplate`

- cmd/soroban-cli/src/utils/contract-init-template/contracts/hello_world/src/lib.rs
- cmd/soroban-cli/src/utils/contract-init-template/contracts/hello_world/src/test.rs
Updates `hello_world` to match the version that has been in
`soroban-examples` since https://github.com/stellar/soroban-examples/pull/314
because `Symbol` is so annoying!!
[TODO or N/A]
> fix(init): use String, not Symbol, in hello_world

- cookbook/contract-lifecycle.mdx
- cookbook/deploy-contract.mdx
- cookbook/deploy-stellar-asset-contract.mdx
- cookbook/extend-contract-instance.mdx
- cookbook/extend-contract-storage.mdx
- cookbook/extend-contract-wasm.mdx
- cookbook/install-deploy.mdx
- cookbook/install-wasm.mdx
- cookbook/payments-and-assets.mdx
- cookbook/restore-contract-instance.mdx
- cookbook/restore-contract-storage.mdx
Remove periods at end of descriptions ( see https://github.com/stellar/stellar-cli/pull/1541 )
This reflects the most recent docs changes
N/a
> unifying formatting to reflect stellar-docs#1541

- cmd/crates/soroban-test/tests/it/integration/hello_world.rs
- cmd/soroban-cli/src/log/event.rs
Change the output of contract events in logs from successful invocations from Rust debug to XDR and JSON.
```
❯ stellar contract invoke --id $(stellar contract asset id --asset native) -- transfer --from me --to you --amount 1
2024-09-11T23:51:12.556972Z  INFO contract_event: soroban_cli::log::event: 1: DiagnosticEvent {
in_successful_contract_call: true,
event: ContractEvent {
ext: V0,
contract_id: Some(
Hash(d7928b72c2703ccfeaf7eb9ff4ef4d504a55a8b979fc9b450ea2c842b4d1ce61),
),
type_: Contract,
body: V0(
ContractEventV0 {
topics: VecM(
[
Symbol(
ScSymbol(
StringM(transfer),
),
),
Address(
Account(
AccountId(
PublicKeyTypeEd25519(
Uint256(309d08c0d6e866993dfb33067291149d652b1ca75b690853b52a042b2947b1f5),
),
),
),
),
Address(
Account(
AccountId(
PublicKeyTypeEd25519( …
```
> Change output of events in logs from Rust debug to JSON

- cmd/soroban-cli/src/commands/contract/deploy/asset.rs
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
- cmd/soroban-cli/src/commands/contract/extend.rs
- cmd/soroban-cli/src/commands/contract/install.rs
- cmd/soroban-cli/src/commands/contract/invoke.rs
- cmd/soroban-cli/src/commands/contract/restore.rs
- cmd/soroban-cli/src/config/mod.rs
Allow public keys to be used with `--source`.
This is will be useful for `--sign-with-lab` which users will likely copy their public keys from their wallet to use on the CLI. It will also be useful when we expand `--sign-with-*` more generally allowing a different key than the source account to sign the transaction.
Currently this would fail if not `--build-only` since we rely on source account being a reference to a private key or seed
> feat: allow source account to be a public key

- flake.lock
Update nix lockfile to use the latest rustc
After latest changes, 1.81.0+ is required
N/A
> Update nix lockfile

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/hello_world.rs
- cmd/soroban-cli/src/config/mod.rs
Previously source_account() assumed string passed to only be identity, and failed on secret key/passphrase. Not it uses correct function to get the source account.
In addition, I updated description of the --source-account flag and added a test for public key.
(Let me know if the PR should be split in 2)
Bug fix
N/A
> Fix source account bug

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/cookbook.rs
- cmd/soroban-cli/src/commands/contract/id/asset.rs
- cmd/soroban-cli/src/config/mod.rs
- cookbook/deploy-stellar-asset-contract.mdx
- cookbook/payments-and-assets.mdx
Close #1645
Because we don't need a source account or hd path to return the asset's contract id.
N/A
> Do not require source account when fetching an asset's contract id.

- cmd/soroban-cli/src/commands/global.rs
Adds a color theme to the help message printed on the terminal
- Improved Readability
- More engaging presentation
> feat: Bring colors to help message

- cmd/soroban-cli/src/upgrade_check.rs
Make all logs in upgrade check debug
The user shouldn't be distracted with upgrade check failures. Error logs output to stdout.
Close #1654
> Make all logs in upgrade check debug

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/cookbook.rs
- cmd/soroban-cli/src/commands/contract/read.rs
- cmd/soroban-cli/src/config/mod.rs
- cookbook/contract-lifecycle.mdx
Before:
```console
$ stellar contract read --id hello --network testnet
error: the following required arguments were not provided:
--source-account <SOURCE_ACCOUNT>
Usage: stellar contract read --source-account <SOURCE_ACCOUNT> --id <CONTRACT_ID> --network <NETWORK>
For more information, try '--help'.
```
After:
```console
$ stellar contract read --id hello --network testnet
LedgerKeyContractInstance,"{""hash"":""4e1ff745c9f12141dca37e5116e994594812c23c091650c5756a2de7857423d3""}",329089,2402688
```
The source account was being required just because of how clap's flattening work.
N/A
> Do not require source account when reading contract.

- .github/workflows/binaries.yml
Add attestation of binaries uploaded to release.
So that folks can run `gh attestation stellar --repo stellar/stellar-cli` to verify that a binary they've downloaded from the releases page was built by a github workflow on the repo, and which workflow built it, to confirm that it hasn't been tampered with.
> Add attestation of binaries uploaded to release

- .github/workflows/binaries.yml
Fix attestation during binary release
When I added the attestation logic, I forgot to add permissions for it to the workflow.
> Fix attestation during binary release

- .github/workflows/binaries.yml
- action.yml
Verify GitHub attestation in install action for the cli and fail if the verification fails, or the verified subject does not match the binaries.yml build for the tag of the release.
The GitHub Attestation allows us to see who produced the binary. We may as well at install points check that the binary being installed from the GitHub releases was built by the appropriate job, and not modified at some point.
> Use attestation in install action

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/tx/new/create_account.rs
The default value parser failed when the string contained underscores.
[TODO or N/A]
> fix: default value for starting balance in create_account

- Cargo.lock
- Cargo.toml
Still need to update soroban client to a released version. Otherwise just updating to newest release candidates
> fix: update stellar dependencies

- cmd/soroban-cli/src/config/network.rs
Now the error of missing network args is deferred to when the network is resolved.
> fix: remove clap from enforcing network args and update error message

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/config.rs
- cmd/soroban-cli/src/commands/env/mod.rs
- cmd/soroban-cli/src/commands/keys/default.rs
- cmd/soroban-cli/src/commands/keys/mod.rs
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/network/default.rs
- cmd/soroban-cli/src/commands/network/mod.rs
- cmd/soroban-cli/src/config/locator.rs
- cmd/soroban-cli/src/config/mod.rs
This pr introduces a global config file called `~/.stellar/config.toml`. Right now, it contains a new section called `defaults`, which can hold the values set by the new commands `stellar keys use NAME` and `stellar network use NAME`. An upcoming pr will use this values by default, when available.
```console
$ stellar network use testnet
ℹ️ The default network is set to `testnet`
$ stellar keys use alice
ℹ️ The default source account is set to `alice`
$ stellar env
STELLAR_NETWORK=testnet # default
STELLAR_ACCOUNT=alice   # default
$ cat ~/.config/stellar/config.toml
[defaults]
network = "testnet"
identity = "alice"
```
This is the first step to implement #1396.
N/A
> Add global config for default network and identity.

- .github/workflows/binaries.yml
Change the macOS binary builds so that the x86 build is done on macos-12 and the arm64 build is done on macos-14.
The builds are currently configured in reverse, with x86 building on macos-14 and arm64 building on macos-12. This was a mistake, because macos-14's arch is arm64 and macos-12's arch is x86.
The builds run slower too than what they would if they were run on their native archs.
> Fix which macOS arch is used for binary builds

- .github/workflows/rust.yml
- Makefile
- cmd/crates/soroban-test/tests/fixtures/test-wasms/swap/src/test.rs
Update GH workflow to use Makefile and re-enabled ARM tests. Makefile was also updated to run all workspace tests, that included 4 tests that were previously not run with the job's for loop. Switched instance for ARM Linux tests from X86-64 Ubuntu to ARM Ubuntu. 
Note: binaries for distribution are still build on x86-64 (Ubuntu 20) in order to use an older glibc
Pipeline improvements 
N/A
> Cleanup unit testing/add ARM support

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/config/address.rs
- cmd/soroban-cli/src/config/mod.rs
Resolve identity from default config.
```console
$ stellar keys ls
alice
$ stellar keys use alice
ℹ️ The default source account is set to `alice`
$ stellar contract deploy --wasm target/wasm32-unknown-unknown/release/hello_world.wasm --alias hello --network testnet
$ stellar contract build
ℹ️ CARGO_BUILD_RUSTFLAGS=--remap-path-prefix=/Users/fnando/.cargo/registry/src/= cargo rustc --manifest-path=contracts/hello_world/Cargo.toml --crate-type=cdylib --target=wasm32-unknown-unknown --release
Finished `release` profile [optimized] target(s) in 0.05s
$ stellar contract deploy --wasm target/wasm32-unknown-unknown/release/hello_world.wasm --alias hello --network testnet
ℹ️ Skipping install because wasm already installed
ℹ️ Using wasm hash …
```
> Resolve identity from default config.

- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
- cmd/crates/soroban-spec-typescript/ts-tests/package.json
Upgrade the version of stellar-sdk-js used by TS Bindings-generated libraries
This is the latest version
[TODO or N/A]
> feat(ts-bindings): upgrade stellar-sdk to 12.2.0

- cmd/soroban-cli/src/cli.rs
- cmd/soroban-cli/src/commands/env/mod.rs
Load default config defaults (`~/.config/stellar/config.toml`) into env vars.
```console
$ stellar keys use alice
ℹ️ The default source account is set to `alice`
$ stellar network use testnet
ℹ️ The default network is set to `testnet`
$ stellar env
STELLAR_ACCOUNT=alice   # use
STELLAR_NETWORK=testnet # use
$ STELLAR_NETWORK=futurenet stellar env
STELLAR_ACCOUNT=alice     # use
STELLAR_NETWORK=futurenet # env
$ STELLAR_NETWORK_SOURCE=what STELLAR_NETWORK=futurenet stellar env
STELLAR_ACCOUNT=alice     # use
STELLAR_NETWORK=futurenet # env
```
So we can use the values set by `stellar network use` and `stellar keys use`.
N/A
> Load default configuration into env vars.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/mod.rs
- outdated url when running `stellar -h`
- broken link. it's outdated.
N/A
> update cli doc url

- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
- cmd/crates/soroban-spec-typescript/ts-tests/package.json
Update js-sdk to 13.0.0
Make sure everything works (tests pass) with the latest js-sdk
- The js-sdk is not yet released, so we are using the release candidate. We can keep this PR around and update to the final release once it is available.
> build: update js-sdk to 13.0.0

- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
Use a single network and contract resolution for all of the bindings generation logic.
There were two network resolutions being performed in the typescript bindings generation. It doesn't make sense to potentially select two different networks, and even if there couldn't be two selected due to some quality of them, it doesn't bring much value to write the logic two ways inside the same function.
There are also two resolutions for the contract ID. When downloading the contract spec the command resolves the alias to an address, but then when filling out the placeholders in the generated files the command goes back to simply outputting the alias name. We shouldn't leak alias names into generated code. Aliases are potentially personal to one developers computer.
This change also includes what …
> Use the same network and contract resolution for all of the bindings generation logic

- CONTRIBUTING.md
**Description:**  
This pull request fixes a typo in the **"Setting up development environment"** section of the Stellar CLI documentation. The original text stated:  
> "There are 2 ways to **being** developing stellar-cli"  
The word **"being"** has been corrected to **"begin"**, so the revised text now reads:  
> "There are 2 ways to **begin** developing stellar-cli"  
---
**Why is this important?**  
Clear and accurate documentation is critical for fostering collaboration and ensuring new contributors can easily set up their development environment. Typos in setup instructions may lead to confusion and diminish the professional appearance of the project. Fixing this typo enhances the overall quality and accessibility of the documentation.
---
**Checklist:**  
---
**Testing:**  
This …
> Typo Update CONTRIBUTING.md

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/bindings.rs
- cmd/soroban-cli/src/commands/contract/bindings/python.rs
See https://github.com/stellar/stellar-cli/issues/1633#issuecomment-2500765235
If this link can be provided in the CLI, it may be easier for users to find it; otherwise, they might not know that Python bindings can be generated.
N/A
> Add Python bindings generation command

- cmd/crates/soroban-test/tests/it/integration/tx/operations.rs
- cmd/soroban-cli/src/commands/tx/new/create_account.rs
- cmd/soroban-cli/src/commands/tx/new/payment.rs
- cmd/soroban-cli/src/tx/builder.rs
- cmd/soroban-cli/src/tx/builder/amount.rs
New type which parses strings that include `_` as i64s.
When entering amounts users will want to use `_`s to better read what they are typing. Also with this approach we could add more complex parsing for example `1 XLM`.
Allows for any number of `_`s as long as they don't start or end the string.We might want to be stricter. e.g. only allow them where a `,` would go e.g. `10_000_000`
> feat: Amount type that allows separating numbers with `_`s

- .github/workflows/rust.yml
- deny.toml
Add bitflags to deny and mark deny ban and licenses as required.
Looks like just after we fixed the deny bans we missed marking it as required and it broke again. Fixing it in this change, and marking it as required from now on. Also, the licenses check can be required too and isn't, so marking it as such as well.
> Add bitflags to deny and mark deny ban and licenses as required

- .github/workflows/binaries.yml
This way, we do attestation on the correct path.
To fix the GHA.
N/A
> Move windows installer once it is built.

- .github/workflows/stale.yml
Add a stale CI workflow that closes old pull requests and issues.
Pull requests are closed if they have been idle for more than 30 days. They can be preserved by pushing an update or removing the stale label.
Issues are closed if they've been assigned to someone for more than 30 days with no activity. They can be preserved by updating the assignee either to another person or to no one, or the stale label removed.
Keep the repo fresh.
> Add a stale CI workflow

- cmd/soroban-cli/src/commands/snapshot/create.rs
Set the protocol version of the created snapshot to the latest protocol version of all the bucket lists.
The logic as is uses the protocol version of the last bucket, but the last bucket is the oldest and therefore the protocol version set in the snapshot file can be a previous protocol version after a network upgrade where newer buckets have new protocol versions and the oldest still has the previous.
cc @kalepail
> fix setting of protocol version in created snapshots

- FULL_HELP_DOCS.md
- cmd/crates/soroban-spec-typescript/ts-tests/initialize.sh
- cmd/soroban-cli/src/commands/contract/bindings.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/info.rs
- cmd/soroban-cli/src/commands/contract/info/env_meta.rs
- cmd/soroban-cli/src/commands/contract/info/interface.rs
- cmd/soroban-cli/src/commands/contract/info/meta.rs
- cmd/soroban-cli/src/commands/contract/info/shared.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
Allow generating TS Bindings from a wasm hash, instead of only contract ID or wasm file path.
This is useful for generating TS Bindings for wasm files that have been uploaded to the network, but for which no contracts have yet been deployed.
> feat(ts-bindings): allow generating from wasm hash

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/mod.rs
Shorten the long env help.
It's sooo long it messes up the default help a bit. Moving the long version into the long description makes it available whne doing `stellar env --help` while the shorter version will be displayed in `stellar --help`.
> Shorten the long env help

- cmd/soroban-cli/src/utils/contract-workspace-template/Cargo.toml.removeextension
Update the version of SDK included in code generated by contract init to v22.
It's the latest version of the SDK that is released, and the soroban-examples and embedded hello-world example use SDK v22 now.
Close #1797
> Fix the version of SDK generated with contract init

- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/info/env_meta.rs
- cmd/soroban-cli/src/commands/contract/info/interface.rs
- cmd/soroban-cli/src/commands/contract/info/meta.rs
- cmd/soroban-cli/src/commands/contract/info/shared.rs
Follow-up to https://github.com/stellar/stellar-cli/pull/1780, implementing
@leighmcculloch's [suggestions].
[suggestions]: https://github.com/stellar/stellar-cli/pull/1780#pullrequestreview-2499059771
Rename `fetch_wasm` to `fetch` and clean up its return value, making all possible return types more understandable.
To keep our code clean and maintainable.
> chore: clean up interface for info::shared::fetch

- Cargo.lock
- Cargo.toml
Bumps SDK dependencies to latest
Build started to fail due to outdated ctor version, coming from RC Soroban SDK dependency
N/A
> Bump SDK dependency

- .github/workflows/rust.yml
Also include libdbus-1-dev for ubuntu dry run
libdbus-1-dev is a dependency for the keychain create we're using, keyring
[TODO or N/A]
> Install libdbus-1-dev for dry run for ubuntu

- .github/workflows/stale.yml
Stalebot wait 90 days before closing
> Stalebot wait 90 days before closing

- cmd/crates/soroban-test/README.md
I noticed a typo in the section title where "Itegration" was misspelled. I corrected it to "Integration."
Additionally, there was a redundant repetition of the word "tests" in the last sentence. I’ve fixed that as well.
Because I love this project and I’m here to save the day, one typo at a time!
> docs: Fix typo and redundant word Update README.md

- Cargo.lock
- FULL_HELP_DOCS.md
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/build.rs
- cmd/soroban-cli/src/commands/licenses.rs
- cmd/soroban-cli/src/commands/mod.rs
- deny.toml
Add `stellar licenses` to display all dependencies' licenses.
```console
$ cargo run licenses
Name: soroban-cli
Version: 22.2.0
License: Apache-2.0
Repo: https://github.com/stellar/stellar-cli
URL: https://github.com/stellar/stellar-cli
Name: adler
Version: 1.0.2
License: 0BSD OR MIT OR Apache-2.0
Repo: https://github.com/jonas-schievink/adler.git
Name: adler2
Version: 2.0.0
License: 0BSD OR MIT OR Apache-2.0
Repo: https://github.com/oyvindln/adler2
Name: ahash
Version: 0.8.11
License: MIT OR Apache-2.0
Repo: https://github.com/tkaitchuck/ahash
Name: aho-corasick
Version: 1.1.3
License: Unlicense OR MIT
Repo: https://github.com/BurntSushi/aho-corasick
URL: https://github.com/BurntSushi/aho-corasick
Name: android-tzdata
Version: 0.1.1
License: MIT OR Apache-2.0
Repo: …
```
> Add `stellar licenses` to display all dependencies' licenses

- cmd/soroban-cli/src/commands/contract/asset.rs
- cmd/soroban-cli/src/commands/contract/deploy.rs
- cmd/soroban-cli/src/commands/contract/deploy/asset.rs
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
Print old contract when overriding existing alias. Notice that we're bypassing the rich printer, because it can be silenced. Instead, we print the contract straight to stderr unconditionally.
```console
$ stellar contract deploy --wasm target/wasm32-unknown-unknown/release/hello_world.wasm --alias=hello
ℹ️ Skipping install because wasm already installed
ℹ️ Using wasm hash 89123eaa2902ec32e26db0141e2d0247e5e00846489f4d8b17d597a85466e863
ℹ️ Simulating deploy transaction…
🌎 Submitting deploy transaction…
ℹ️ Transaction hash is ab3a11357ef533134efd4685985ac19f464e48be86d9732fbc81abcdab6e8c56
🔗 https://stellar.expert/explorer/testnet/tx/ab3a11357ef533134efd4685985ac19f464e48be86d9732fbc81abcdab6e8c56
ℹ️ Signing transaction: ab3a11357ef533134efd4685985ac19f464e48be86d9732fbc81abcdab6e8c56
🔗 …
```
> Print old contract when overriding existing alias.

- cmd/soroban-cli/src/commands/keys/add.rs
```
$ stellar keys add test --seed-phrase
Type a secret key or 12/24 word seed phrase:
⚠️ The provided seed phrase lacks sufficient entropy and should be avoided. Using a 24-word seed phrase is a safer option.
⚠️ To generate a new key, use the `stellar keys generate` command.
✅ Key saved with alias KeyName("test") in "/Users/fnando/Projects/stellar/hello/.stellar/identity/test.toml"
```
Close #1806
N/A
> Check seed phrase entropy and warn user when using a 12-word seed.

- cmd/crates/soroban-spec-typescript/ts-tests/package.json
Increases timeout for TS tests to 30 seconds
The default timeout is not enough. Running tests in CI with default timeout fails 3 tests (locally 1), with 30 seconds all tests pass
N/A
> Increase TS timeouts

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/keys/secret.rs
Add support for returning seed phrases on `stellar keys secret`.
```console
$ stellar keys secret dapp --phrase
egg judge require window warfare odor uniform where relief mouse battle cattle
$ stellar keys secret dapp
SCA5R6VLL6OE3TIFV6XPY6Q6JR6ITZSLYZFONB6D34TUBK5L3NEZWSCT
$ stellar keys secret dapp --phrase --hd-path 0
error: the argument '--phrase' cannot be used with '--hd-path <HD_PATH>'
Usage: stellar keys secret --phrase <NAME>
For more information, try '--help'.
$ stellar keys secret sekret --phrase
❌ error: identity is not tied to a seed phrase
```
- Close #1055
- Close #1824
- Close #1828
N/A
> Add support for returning seed phrases on `stellar keys secret`.

- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/build.rs
Add features for guarding code based on the P23.
The idea is to allow adding/removing code without having to keep a long running branch for either the current or next version.
This approach also allow us to easily enable features from the next protocol version when running tests, but using cargo hack.
N/A
> Add features for guarding code based on the P23.

- cmd/soroban-cli/src/commands/network/mod.rs
Based on https://github.com/stellar/stellar-cli/pull/1863
Closes https://github.com/stellar/stellar-cli/issues/1363
Remove deprecated `network container` commands.
We moved container commands to the root, and have marked these as deprecated for a couple of major releases now, so it should be safe to remove them. 
n/a
> Remove `network container` commands

- .github/workflows/ledger-emulator.yml
- Cargo.lock
Update openssl to 0.10.70
`cargo deny check advisories` is currently failing with the following vulnerability error:
```
error[vulnerability]: ssl::select_next_proto use after free
┌─ /stellar/stellar-cli/Cargo.lock:289:1
│
289 │ openssl 0.10.68 registry+https://github.com/rust-lang/crates.io-index
│ --------------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2025-0004
= Advisory: https://rustsec.org/advisories/RUSTSEC-2025-0004
= In `openssl` versions before `0.10.70`, `ssl::select_next_proto` can return a slice pointing into the `server` argument's buffer but with a lifetime bound to the `client` argument. In situations where the `server` buffer's lifetime is shorter than the `client` buffer's, this can cause a use after free. …
```
> Update openssl to 0.10.70 per cargo deny advisories suggestion

- .github/workflows/rust.yml
- Cargo.lock
- deny.toml
Update cargo deny. Most removed rules now have the same defaults.
https://github.com/EmbarkStudios/cargo-deny/pull/611
So we get the latest changes.
N/A
> Update cargo deny.

- cmd/soroban-cli/src/commands/keys/add.rs
- cmd/soroban-cli/src/commands/keys/generate.rs
Closes https://github.com/stellar/stellar-cli/issues/1844
We should print out the key name (or alias) instead of the full struct for `stellar keys add` and `stellar keys generate`.
[TODO or N/A]
> Print KeyName string instead of struct

- .cargo-husky/hooks/pre-commit
- .cargo-husky/hooks/pre-push
- .github/workflows/binaries.yml
- cmd/crates/soroban-test/tests/fixtures/test-wasms/swap/src/lib.rs
`#[allow(clippy::too_many_arguments)]` was being ignored, so let's use a module rule instead.
So pre-commit hook works as expected.
N/A
> Fix pre push hook

- Cargo.lock
- deny.toml
* Update hickory version
* Allow [multiple dependency versions](https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html#the-multiple-versions-field-optional) (set to `warn` -- default config)
https://rustsec.org/advisories/RUSTSEC-2025-0006
N/A
> Fix cargo-deny issues

- .github/workflows/binaries.yml
Change instance of arm builder to `ubuntu-jammy-16-cores-arm64` 
Failing cross-compilation build on x64
glibc will be updated to [2.35](https://packages.ubuntu.com/source/jammy/glibc) from [2.31](https://packages.ubuntu.com/source/focal/glibc) for ARM build
> Fix arm cross compilation

- cmd/crates/stellar-ledger/Cargo.toml
Publish stellar-ledger crate. 
- without publishing this crate, we are seeing a failure in the publish-dry-run workflow because stellar-ledger isn't included in the vendor file, and needs to be there in order to be packaged in soroban-cli
- we had held off publishing stellar-ledger because of a dependency vulnerability, but that has now been handled: https://github.com/stellar/stellar-cli/issues/1706
I'm not sure familiar with the release process/ rust packaging, so maybe there is another way to handle this, but just wanted to get a PR up to get some eyes on the issue.
> Allow stellar-ledger to be published

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/tx/hash.rs
- cmd/soroban-cli/src/commands/tx/mod.rs
- cmd/soroban-cli/src/commands/tx/op/add/args.rs
- cmd/soroban-cli/src/commands/tx/op/add/mod.rs
- cmd/soroban-cli/src/commands/tx/send.rs
- cmd/soroban-cli/src/commands/tx/sign.rs
- cmd/soroban-cli/src/commands/tx/simulate.rs
- cmd/soroban-cli/src/commands/tx/xdr.rs
Makes `stellar tx` subcommands to accept stdin/string/file as an input
#1827 
#1822 
* Only takes one string/file as an input
* Some copy-paste from `rs-stellar-xdr` that can be addressed later
> Implement stellar tx to accept string/file as an input

- Cargo.lock
Upgrade scc crate from 2.1.9 to 2.3.3 and sdd crate from 2.1.0 to 3.0.7.
scc 2.1.9 was yanked. According to the maintainer it is because of a use-after-free bug that existed in the lib.
- https://github.com/wvwwvwwv/scalable-concurrent-containers/issues/178
> Upgrade scc and sdd deps

- cmd/soroban-cli/src/commands/tx/xdr.rs
Improves TX reading UX, adding an STDERR message indicating user to input transaction using stdin
Currently there are no indication of what to do, which could be confusing for the user 
N/A
> Improve tx reading UX

- cmd/crates/soroban-test/Cargo.toml
- cmd/crates/soroban-test/build.rs
Fixes protocol features for manual testing.
1. Adds features to `soroban-test` crate
2. Updates `build.rs` to only enable `version_lt_23` if `version_gte_23` is not enabled (previously if toml file's version set to 22 `version_lt_23` would always be enabled) 
Previously it was impossible to test p23 changes
N/A
> Fix protocol features for testing

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/bindings.rs
- cmd/soroban-cli/src/commands/contract/bindings/java.rs
Add Java bindings generation command.
See #1897
N/A
> Add Java bindings generation command.

- .github/workflows/rust.yml
bump cargo-deny-action to 2.0.7
Fixes the CI (see [slack discussion](https://stellarfoundation.slack.com/archives/C06KTGUULUF/p1741050856664549))
N/A
> bump cargo-deny-action to 2.0.7

- cmd/crates/soroban-test/tests/it/config.rs
- cmd/crates/soroban-test/tests/it/rpc_provider.rs
- cmd/crates/soroban-test/tests/it/util.rs
- cmd/soroban-cli/src/commands/keys/generate.rs
Previously, `--fund` flag was added, and funding by default gave a warning.
In this PR `-no-fund` flag was removed, and default behavior flipped to no longer fund 
Closing #1407
Depends on #1888
> Make `keys generate` to no longer fund

- cookbook/tx-new.mdx
- cookbook/tx-op-add.mdx
- cookbook/tx-sign.mdx
This PR removes the backticks in the cookbook front matter titles. 
We were seeing a failure in the dev docs build with the following error:
```
Error:  Error while parsing Markdown front matter.
...
[cause]: YAMLException: end of the stream or a document separator is expected at line 2, column 8:
title: `tx` Commands
```
[TODO or N/A]
> Remove backticks from cookbook front matter

- .github/workflows/binaries.yml
The ubuntu-20.04 image is deprecated since Feb 1 and will be officially unsupported starting Apr 1.
Update ubuntu to 22.04.
The ubuntu-20.04 image is deprecated since Feb 1 and will be officially unsupported starting Apr 1.
N/A
> Update ubuntu version.

- Cargo.lock
- deny.toml
Update ring dependency.
I was seeing a cargo deny error that `ring v0.17.8` has a security vulnerability:
```
error[vulnerability]: Some AES functions may panic when overflow checking is enabled.
┌─ /Users/ebethme/Desktop/projects/stellar/stellar-cli/Cargo.lock:334:1
│
334 │ ring 0.17.8 registry+https://github.com/rust-lang/crates.io-index
│ ----------------------------------------------------------------- security vulnerability detected
│
= ID: RUSTSEC-2025-0009
```
There is also an error about `paste` no longer being maintained that I added to the ignore list - happy to rethink this!
> Update ring dependency (to fix cargo deny advisories)

- cmd/crates/soroban-test/tests/it/build.rs
- cmd/soroban-cli/src/commands/contract/build.rs
Fixes metadata not properly written. See previous discussion in #1694
Original implementation took artifact straight from the build directory, wrote metadata there, and then copied it to destination directory (if provided).
Naturally, if no code changes happens between rebuilds, cargo will simply do nothing, as the result WASM file is unchanged according to cargo. However, we already modified it in our code previously, and we write new metadata entries in that existing WASM file.
With this change we require output dir to be specified if we writing any meta (thus ensuring WASM is first copied and only then modified). Then, do the same steps as before.
#1694
It's technically a breaking change to require output dir
> Fix metadata entry not properly written

- cmd/soroban-cli/src/commands/contract/build.rs
- cmd/soroban-cli/src/print.rs
Add build summary displaying file location, hash, and exported functions, to the `stellar contract build` command.
```
$ stellar contract build
ℹ️ CARGO_BUILD_RUSTFLAGS=--remap-path-prefix=/Users/leighmcculloch/.cargo/registry/src= cargo rustc --manifest-path=Cargo.toml --crate-type=cdylib --target=wasm32-unknown-unknown --release
Finished `release` profile [optimized] target(s) in 0.08s
ℹ️ Build Summary:
Wasm File: target/wasm32-unknown-unknown/release/soroban_increment_contract.wasm
Wasm Hash: 8153ca452b10ed4edaefeb5235145b9938786c8c6a626e060e3dce85752c0cc3
Exported Functions: 2 found
• _
• increment
✅ Build Complete
```
I think it could be helpful to output the wasm hash in the logs of builds.
It also outputs the exported functions because I was recently thinking more about the …
> Add build summary to output of build command

- action.yml
Fix `action.yml`
Example [run after fix](https://github.com/stellar/soroban-examples/actions/runs/13820848385/job/38665604577?pr=368)
```
using version: a06ff9fd2bcd9e45a86ec3518b1a83bde898b32a
Run version="a06ff9fd2bcd9e45a86ec3518b1a83bde898b32a"
https://github.com/stellar/stellar-cli/releases/download/va06ff9fd2bcd9e45a86ec3518b1a83bde898b32a/stellar-cli-a06ff9fd2bcd9e45a86ec3518b1a83bde898b32a-x86_64-unknown-linux-gnu.tar.gz
```
Example [run before fix
](https://github.com/stellar/soroban-examples/actions/runs/13820464519/job/38664345285)
```
Run version=""
https://github.com/stellar/stellar-cli/releases/download/v/stellar-cli--x86_64-unknown-linux-gnu.tar.gz
```
We got github action'd
https://github.com/orgs/community/discussions/49245
TLDR: `version=${{ inputs.version || …
> Fix `action.yml`

- cmd/soroban-cli/src/config/network.rs
We should encourage users using `network use` instead of env variables 
Improving error message and usability
N/A
> Update error message on missing network

- .github/workflows/binaries.yml
- .github/workflows/rust.yml
Remove packaging steps in the GitHub workflow for building binaries.
When I wrote the binary build workflow, my goal was to have it match installing from cargo install as closely as possible. For that goal I had the build occur using a locally built package, generated with `cargo package`. This worked fine when the stellar-cli was a single crate in this repo.
When we started adding additional crates to the repo this approach became flawed. The cargo package process doesn't have any workspace intelligence built in, so it needs any dependencies to have already been published to crates.io.
While flawed, the binary builds continued to work for a time because the cargo publish was always occurring before the binary build step because both occurred in the same workflow.
At some point I split …
> Remove package step from binary build workflow for releases

- .github/workflows/binaries.yml
- .github/workflows/rust.yml
Downgrade macos runner to 13
This is the latest macos runner on Intel. We currently use ARM runner for our x86-64 builds and tests, but Intel runner should provide a native experience (i.e. we will catch if there's any potential x86-64 issue specifically on Macos, for external libraries/e2e integration, etc.) 
Previously used runner is v14, but there shouldn't be any issues with downgrading
> Change macos runner

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/keys/generate.rs
- cmd/soroban-cli/src/config/secret.rs
Remove default seed option from generate command.
It appears to be broken:
```
$ stellar keys generate --default-seed issuer
⚠️ Behavior of `generate` will change in the future, and it will no longer fund by default. If you want to fund please provide `--fund` flag. If you don't need to fund your keys in the future, ignore this warning. It can be suppressed with -q flag.
❌ error: invalid word in phrase
```
We could fix it, but if it's broken and no one has noticed it suggests it isn't being used anywhere. I believe it was added for testing at some point, but it also scares me a bit that there's an option on the key generation command that results in a fixed test key getting used. There's no case where that should be used in the production release.
> Remove default seed option from generate command

- cmd/crates/soroban-test/Cargo.toml
Prevent the soroban-test crate from being published to crates.io by setting publish=false in Cargo.toml.
The soroban-test crate is intended for internal use only and should not be available on crates.io. While we can publish it, it introduces a lot of builds into the publish-dry-run workflow. It's unclear why it's being published, so unpublishing it for the time being seems okay. If someone brings it to our attention that publishing had some value, we can return to doing so as needed.
Close https://github.com/stellar/stellar-cli/issues/1969
> Disable publishing soroban-test crate

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/tx/edit.rs
- cmd/soroban-cli/src/commands/tx/mod.rs
Add default json structure when calling `stellar tx edit` without piping. It also updates the help message with an example:
```
$ stellar tx edit --help
Edit a transaction envelope from stdin. This command respects the environment variables `STELLAR_EDITOR`, `EDITOR` and `VISUAL`, in that order.
Example: Start a new edit session
$ stellar tx edit
Example: Pipe an XDR transaction envelope
$ stellar tx new manage-data --data-name hello --build-only | stellar tx edit
```
It's a better ux overall. It gives users the ability to explore the transaction editing from zero.
N/A
> Add default json structure when calling `stellar tx edit`.

- .github/workflows/rust.yml
- cmd/stellar-cli/Cargo.toml
Fixes publish-dry-run with reducing number of permutations down to 11
```
> cargo-hack hack --feature-powerset --skip version_gte_23,emulator-tests --group-features default,version_lt_23 --ignore-private --ignore-unknown-features --print-command-list package        
cargo package --manifest-path cmd/stellar-cli/Cargo.toml --no-default-features
cargo package --manifest-path cmd/stellar-cli/Cargo.toml --no-default-features --features opt
cargo package --manifest-path cmd/soroban-cli/Cargo.toml --no-default-features
cargo package --manifest-path cmd/soroban-cli/Cargo.toml --no-default-features --features opt,default,version_lt_23
cargo package --manifest-path cmd/soroban-cli/Cargo.toml --no-default-features --features opt
cargo package --manifest-path cmd/soroban-cli/Cargo.toml …
```
> Fix cargo-hack

- Cargo.lock
- Cargo.toml
- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/network/health.rs
- cmd/soroban-cli/src/commands/network/mod.rs
- cmd/soroban-cli/src/print.rs
Adds `network health` command
```
> cargo run network health --network=local
❌ Unhealthy
❌ failed to fetch network health: Networking or low-level protocol error: HTTP error: error trying to connect: tcp connect error: Connection refused (os error 111)
> cargo run network health              
✅ Healthy
ℹ️ Latest ledger: 104038
> cargo run network health --output json-formatted
{
"status": "healthy",
"latestLedger": 104044,
"oldestLedger": 256,
"ledgerRetentionWindow": 120960
}
```
Closing #1913
Depends on https://github.com/stellar/rs-stellar-rpc-client/pull/24
> Add `network health` command

- cmd/crates/soroban-spec-tools/src/lib.rs
- cmd/crates/soroban-test/tests/it/help.rs
Update example values for numeric and byte types that are presented to users in docs about a contract on the invoke command. 
The examples provided were a mix of rather random values, such as 'beefface123' for bytes, and some integers were exampled as '42', others contained negative signs which looked a bit confusing when seeing a suggestion to use a negative value for values in a contract that should never be negative.
Also, the BytesN command outputted invalid examples whenever the N was not event.
> Update invoke example values for numeric and byte types

- .github/workflows/rpc-tests.yml
And ARM Linux and Mac support for integration tests
#1941 
Set threads to 1, this doesn't slow build too much.
Current main:[ ~10 minutes](https://github.com/stellar/stellar-cli/actions/runs/14133879663/job/39600795975)
Multiplatform multithread (using `ubuntu-latest-16-cores`): [~7 minutes](https://github.com/stellar/stellar-cli/actions/runs/14120868525/job/39560755321) -> making a lot of requests in multithreaded environment messes up the fees and leads to failures. This doesn't happen with smaller instance because it doesn't send as much requests (however, it still leads to [flaky tests](https://github.com/stellar/stellar-cli/issues/1954) for the same reason -- fees)
Multiplatform singlethread: [~11 minutes](https://github.com/stellar/stellar-cli/actions/runs/14131787359/job/39616081641 …
> [ci] Integration tests: support for Linux/Mac

- .github/workflows/ledger-emulator.yml
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/config/address.rs
- cmd/soroban-cli/src/config/secret.rs
- cmd/soroban-cli/src/config/sign_with.rs
- cmd/soroban-cli/src/signer/keyring.rs
- cmd/soroban-cli/src/signer/ledger.rs
- cmd/soroban-cli/src/signer/mod.rs
Based on https://github.com/stellar/stellar-cli/pull/1977, this PR adds support for including the `ledger-stellar` crate in the additional-libs feature.
Allows for a smaller binary, and less system dependencies.
N/A
> additional-libs feature for ledger-stellar dependencies (ledger signing)

- .github/workflows/ledger-emulator.yml
@Ifropc I think that this change should get the emulator tests running on macos-13. The last run took 32min, but i had noticed it being quicker in previous attempts, so it may need some fine tuning still. 
Set the DOCKER_HOST to the colima host and pipe to github env
the emulator tests were failing on macos because we need to account for colima's socket being different than the default docker socket. and the test containers library (and it's dep bollard) were expecting the socket to be at the default docker host.
the cargo deny failure should be fixed once `emulator-multiplatform` and this branch are updated with main.
> Set DOCKER_HOST to colima so that macos-13 emulator tests work

- cmd/crates/soroban-test/tests/it/plugin.rs
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/plugin.rs
Add support for subcommand plugins lookup. If you have a binary like `stellar-contract-bindings-typescript`, that means you can call it by using `stellar contract bindings typescript`.
```console
$ which stellar-hello
/Users/fnando/Projects/stellar/stellar-cli/target/debug/stellar-hello
$ stellar hello
running `stellar hello` with args:
$ stellar hello 1
running `stellar hello` with args: 1
$ which stellar-contract-hello
/Users/fnando/Projects/stellar/stellar-cli/target/debug/stellar-contract-hello
$ stellar contract hello
running `stellar contract hello` with args:
$ stellar contract hello foo bar --nice 1
running `stellar contract hello` with args: foo bar --nice 1
$ stellar env
STELLAR_ACCOUNT=me      # use
STELLAR_NETWORK=testnet # use
```
This allows publishers to extend the CLI by …
> Add subcommand lookup for missing commands.

- cmd/crates/soroban-test/tests/fixtures/test-wasms/custom_account/src/lib.rs
- cmd/soroban-cli/src/commands/contract/deploy/utils.rs
- cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
Remove 30-char length limit on aliases.
Does this serve a purpose? Will there be actual problems caused by people (or tooling) creating humongously long aliases?
I ran into this limit while incorporating [OpenZeppelin's `fungible-token-interface-example`](https://github.com/OpenZeppelin/stellar-contracts/blob/main/examples/fungible-token-interface/Cargo.toml) into https://github.com/AhaLabs/scaffold-stellar-frontend. The alias is not for human use; it's for tooling. It is generated automatically.
But even if people want to create ridiculously long aliases, why should the CLI limit them?
None???
> Remove contract alias length limit

- cmd/crates/soroban-spec-typescript/src/lib.rs
- cmd/crates/soroban-test/tests/fixtures/test-wasms/custom_type/src/lib.rs
We were generating a separate `const Errors` definition for every `#[contracterror]` in the original contract source. For example, with the new `custom_type` source code, the generated TS would be:
```ts
export const Errors = {
/**
* Please provide an odd number
*/
1: {message:"NumberMustBeOdd"}
}
export const Errors = {
/**
* Some contract libraries contain extra #[contracterror] definitions that end up compiled
* into the main contract types. We need to make sure tooling deals with this properly.
*/
100: {message:"HowCouldYou"}
}
```
This now names the `const` after the name of the error enum in the original file, following the logic of other enum types. It will also rename `Error` to `Errors`, to avoid conflicts with JS `Error` type. So the updated `custom_type` source code now …
> fix(ts-bindings): valid TS when >1 contracterror

- cmd/crates/soroban-spec-typescript/fixtures/test_constructor/package.json
- cmd/crates/soroban-spec-typescript/fixtures/test_constructor/src/index.ts
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/index.ts
- cmd/crates/soroban-spec-typescript/src/lib.rs
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
- cmd/crates/soroban-spec-typescript/ts-tests/package.json
Update `@stellar/stellar-sdk` npm dependencies to allow anything in the 13.x major version
So generated TS libraries have the latest & greatest.
When the bindings were new, they needed specific features in specific patch-level updates of js-stellar-sdk. That's no longer true. Anything in the 13.x range will work fine.
> update npm dependency stellar-sdk for TS bindings

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/tx/fetch.rs
- cmd/soroban-cli/src/commands/tx/fetch/args.rs
- cmd/soroban-cli/src/commands/tx/fetch/envelope.rs
- cmd/soroban-cli/src/commands/tx/fetch/meta.rs
- cmd/soroban-cli/src/commands/tx/fetch/mod.rs
- cmd/soroban-cli/src/commands/tx/fetch/result.rs
- cmd/soroban-cli/src/commands/tx/mod.rs
- cmd/soroban-cli/src/config/network.rs
In order to flatten an optional field, I needed to remove the group(skip) on network::Args. But this lead to a conflict because there are multiple groups with an implicit name of 'Args' that were all trying to be flattened. The solution to this was add a specific group id to network::Args.
> Make envelope the default fetch when no subcommand is given

- .cargo-husky/hooks/pre-commit
- .cargo-husky/hooks/pre-push
- .cargo/config.toml
- Cargo.lock
- FULL_HELP_DOCS.md
- Makefile
- cmd/soroban-cli/Cargo.toml
Move `cargo md-gen` to an ignored test. This allows moving clap-markdown to dev-dependency allowing the use of a fork and removing an unneeded dependency since the markdown generation is pre-release.
> feat(markdown docs): add aliases to options and subcommands

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/tx/new/payment.rs
- Clarify that amount is specified in stroops
- Add explanation of stroop to asset conversion (1 stroop = 0.0000001 of asset)
- Update both source code comment and generated documentation
- Example: 1 XLM = 10_000_000 stroops
(https://github.com/stellar/stellar-cli/issues/1693)
> Improve payment amount parameter description

- cmd/soroban-cli/src/commands/container/start.rs
- Start the lab by default.
- Override container args by passing `STELLAR_CONTAINER_ARGS`
Because scaffold needs it.
N/A
> Start lab by default.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/optimize.rs
Make `stellar contract optimize` accept one or more files.
```console
$ stellar contract optimize --wasm target/wasm32v1-none/release/hello_world.wasm target/wasm32v1-none/release/bye.wasm
Reading: target/wasm32v1-none/release/hello_world.wasm (574 bytes)
Optimized: target/wasm32v1-none/release/hello_world.optimized.wasm (537 bytes)
Reading: target/wasm32v1-none/release/bye.wasm (565 bytes)
Optimized: target/wasm32v1-none/release/bye.optimized.wasm (528 bytes)
$ stellar contract optimize
error: the following required arguments were not provided:
--wasm <WASM>...
Usage: stellar contract optimize --wasm <WASM>...
For more information, try '--help'.
$ stellar contract optimize --wasm target/wasm32v1-none/release/hello_world.wasm target/wasm32v1-none/release/bye.wasm --wasm-out tmp/foo.wasm
❌ …
```
> Optimize several wasm files at once.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/alias/ls.rs
- cmd/soroban-cli/src/commands/network/settings.rs
- cmd/soroban-cli/src/config/locator.rs
```console
$ tree -a a
a
└── b
├── .stellar
│   └── identity
│       └── 19510.toml
└── c
5 directories, 1 file
$ cd a/b/c
$ stellar keys address 19510
⚠️ A local config was found at "/Users/fnando/Projects/stellar/a/b/.stellar".
Local config is deprecated and will be removed in the future.
Run `stellar config migrate` to move the local config into the global config ("/Users/fnando/.config/stellar").
GBUX5OWVZN4OGIM72GQZ4OH7USWQMQNFWNX3HGB5QIFQBB433S23DWOA
```
Fix #2105 
N/A
> Fix how config dir is displayed for the deprecation message.

- cmd/soroban-cli/src/commands/contract/build.rs
Use the correct env var (`TARGET_wasm32-unknown-unknown_RUSTFLAGS` or `TARGET_wasm32v1-none_RUSTFLAGS`) based on the target that will be used.
So the behavior matches the actual target.
N/A
> Conditionally set rustflags based on the target that should be used.

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/tx/operations.rs
- cmd/soroban-cli/src/commands/tx/args.rs
- cmd/soroban-cli/src/commands/tx/help.rs
- cmd/soroban-cli/src/commands/tx/new/manage_sell_offer.rs
- cmd/soroban-cli/src/commands/tx/new/mod.rs
Add support for MANAGE_SELL_OFFER operation.
```console
$ stellar tx new manage-sell-offer --selling native --buying USDC:GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5 --price 1:2 --amount 10000000 --build-only | stellar xdr decode --type TransactionEnvelope --output json-formatted
{
"tx": {
"tx": {
"source_account": "GDMHFOFH7IQSGGTIUYOUORZ3K2ZDP6PYNZDOL2AKSK7MRLPX5HF7DEA4",
"fee": 100,
"seq_num": "3179774742626315",
"cond": "none",
"memo": "none",
"operations": [
{
"source_account": null,
"body": {
"manage_sell_offer": {
"selling": "native",
"buying": {
"credit_alphanum4": {
"asset_code": "USDC",
"issuer": "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
}
},
"amount": "10000000",
"price": {
"n": 1,
"d": 2
},
"offer_id": "0"
}
}
}
],
"ext": "v0"
},
"signatures": [] …
```
> Add `stellar tx new manage-sell-offer`.

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/tx/operations.rs
- cmd/soroban-cli/src/commands/tx/help.rs
- cmd/soroban-cli/src/commands/tx/new/manage_buy_offer.rs
- cmd/soroban-cli/src/commands/tx/new/mod.rs
Add support for MANAGE_BUY_OFFER operation.
```console
$ stellar tx new manage-buy-offer --selling native --buying USDC:GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5 --price 1:2 --amount 10000000 --build-only | stellar xdr decode --type TransactionEnvelope --output json-formatted
{
"tx": {
"tx": {
"source_account": "GDMHFOFH7IQSGGTIUYOUORZ3K2ZDP6PYNZDOL2AKSK7MRLPX5HF7DEA4",
"fee": 100,
"seq_num": "3179774742626317",
"cond": "none",
"memo": "none",
"operations": [
{
"source_account": null,
"body": {
"manage_buy_offer": {
"selling": "native",
"buying": {
"credit_alphanum4": {
"asset_code": "USDC",
"issuer": "GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5"
}
},
"buy_amount": "10000000",
"price": {
"n": 1,
"d": 2
},
"offer_id": "0"
}
}
}
],
"ext": "v0"
},
"signatures": [] …
```
> Add `stellar tx new manage-buy-offer`.

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration/tx/operations.rs
- cmd/soroban-cli/src/commands/tx/help.rs
- cmd/soroban-cli/src/commands/tx/new/mod.rs
- cmd/soroban-cli/src/commands/tx/new/path_payment_strict_receive.rs
Add support for PATH_PAYMENT_STRICT_RECEIVE operation.
```console
$ stellar tx new path-payment-strict-receive --send-asset native --send-max 1000000 --destination default --dest-asset USDC:GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5 --dest-amount 1000 --build-only | stellar xdr decode --type TransactionEnvelope --output json-formatted
{
"tx": {
"tx": {
"source_account": "GDMHFOFH7IQSGGTIUYOUORZ3K2ZDP6PYNZDOL2AKSK7MRLPX5HF7DEA4",
"fee": 100,
"seq_num": "3179774742626317",
"cond": "none",
"memo": "none",
"operations": [
{
"source_account": null,
"body": {
"path_payment_strict_receive": {
"send_asset": "native",
"send_max": "1000000",
"destination": "GCNV6VMPZNHQTACVZC4AE75SJAFLHP7USOQWGE2HWMLXDKP6XOLGJR7S",
"dest_asset": {
"credit_alphanum4": {
"asset_code": "USDC",
"issuer": …
```
> Add `stellar tx new path-payment-strict-receive`. 

- cmd/soroban-cli/src/commands/tx/edit.rs
Update schema URL used in tx edit to be pinned to the schema compatible with the cli's embedded xdr.
New URL reflects the specific version of the schema being used, ensuring correct validation. It also uses the stellar.org domain which is shorter and looks better.
> Update schema URL used in tx edit

- cmd/crates/soroban-spec-typescript/fixtures/test_constructor/package.json
- cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
- cmd/crates/soroban-spec-typescript/src/lib.rs
- cmd/crates/soroban-spec-typescript/src/project_template/package.json
- cmd/crates/soroban-spec-typescript/src/types.rs
Adds a stub to the `EventV0` branch of `ScSpecEntry`.
Bindings fail to generate if your wasm uses the new `#[contractevent]` macro, but they shouldn't:
```
$ stellar contract bindings typescript --output-dir testing --wasm target/wasm32v1-none/release/events.wasm 
ℹ️ Loading contract spec from file...
thread 'main' panicked at /home/george/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/soroban-spec-typescript-23.0.0/src/types.rs:255:40:
not yet implemented: EventV0 is not implemented yet
```
We should still let them be generated, even though there aren't bindings for the events themselves.
n/a, I confirmed that building this branch and running the above commands generates bindings.
> Stub out `EventV0` specs so bindings still generate

- Cargo.lock
- Cargo.toml
- cmd/crates/soroban-spec-tools/src/lib.rs
- cmd/crates/soroban-test/tests/fixtures/test-wasms/hello_world/src/lib.rs
- cmd/crates/soroban-test/tests/fixtures/test-wasms/token/src/contract.rs
- cmd/soroban-cli/Cargo.toml
- cmd/soroban-cli/src/commands/contract/arg_parsing.rs
- cmd/soroban-cli/src/commands/contract/bindings/typescript.rs
- cmd/soroban-cli/src/commands/contract/info/interface.rs
- cmd/soroban-cli/src/get_spec.rs
- cookbook/payments-and-assets.mdx
StellarAssetSpec got refactored in https://github.com/stellar/rs-soroban-sdk/pull/1536
This PR is to adapt to the new crate stellar-asset-spec v23.0.0-rc.3
Plus pick up the dependencies from other crates released within rs-soroban-sdk v23.0.0-rc.3.
> Uptake stellar-asset-spec crate from refactoring in rs-soroban-sdk PR#1536

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/bindings.rs
- cmd/soroban-cli/src/commands/contract/bindings/flutter.rs
- cmd/soroban-cli/src/commands/contract/bindings/php.rs
- cmd/soroban-cli/src/commands/contract/bindings/swift.rs
Adds contract bindings subcommands for `flutter`, `swift` and `php`. They display a link to the [`stellar-contract-bindings`](https://github.com/lightsail-network/stellar-contract-bindings) tool, similar to the subcommands for `python` and `java`.
Contract bindings generation is now supported in the `stellar-contract-bindings` tool and corresponding SDKs for `flutter`, `swift/ios` and `php`.
The bindings are not generated by the cli. The cli only displays the link to the `stellar-contract-bindings` tool similar to `python` and `java`.
> Add contract bindings subcommands for flutter, swift and php

- cmd/soroban-cli/src/commands/contract/restore.rs
Fixes #2154
support single change format in restore metadata parsing
Handle cases where restore operation returns only one change instead of expected two changes, preventing TxSorobanInvalid errors.
> support single change format in restore metadata parsing

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/tx/op/add/claim_claimable_balance.rs
- cmd/soroban-cli/src/commands/tx/op/add/create_claimable_balance.rs
- cmd/soroban-cli/src/commands/tx/op/add/create_passive_sell_offer.rs
- cmd/soroban-cli/src/commands/tx/op/add/manage_buy_offer.rs
- cmd/soroban-cli/src/commands/tx/op/add/manage_sell_offer.rs
- cmd/soroban-cli/src/commands/tx/op/add/mod.rs
- cmd/soroban-cli/src/commands/tx/op/add/path_payment_strict_receive.rs
- cmd/soroban-cli/src/commands/tx/op/add/path_payment_strict_send.rs
I added these commands but didn't know we had to add them to `tx op add` as well.
```console
$ stellar tx op add --help
Add Operation to a transaction
Usage: stellar tx operation add [OPTIONS] <COMMAND>
Commands:
account-merge                Transfer XLM balance to another account and remove source account
bump-sequence                Bump sequence number to invalidate older transactions
change-trust                 Create, update, or delete a trustline
claim-claimable-balance      Claim a claimable balance by its balance ID
create-account               Create and fund a new account
create-claimable-balance     Create a claimable balance that can be claimed by specified accounts
create-passive-sell-offer    Create a passive sell offer on the Stellar DEX
manage-buy-offer …
```
> Add missing operations to `tx op add`.

- .github/workflows/docs.yml
- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/tx/new/create_claimable_balance.rs
Changing the way the `--claimant` examples are presented.
Docs builds are currently failing to parse the examples as-is.
N/A
> modify claimant examples to be more docs-friendly

- FULL_HELP_DOCS.md
- cmd/crates/soroban-spec-tools/src/lib.rs
- cmd/crates/soroban-test/tests/it/integration/tx/operations.rs
- cmd/soroban-cli/src/commands/tx/help.rs
- cmd/soroban-cli/src/commands/tx/new/clawback_claimable_balance.rs
- cmd/soroban-cli/src/commands/tx/new/mod.rs
- cmd/soroban-cli/src/commands/tx/new/revoke_sponsorship.rs
- cmd/soroban-cli/src/commands/tx/op/add/mod.rs
- cmd/soroban-cli/src/commands/tx/op/add/revoke_sponsorship.rs
> Add `stellar tx new revoke-sponsorship` and `stellar tx op add revoke-sponsorship`.

- cmd/soroban-cli/src/commands/tx/args.rs
- cmd/soroban-cli/src/commands/tx/new/revoke_sponsorship.rs
- cmd/soroban-cli/src/commands/tx/new/set_options.rs
```console
$ stellar tx new set-options --signer sponsor --signer-weight=20
error: invalid value 'sponsor' for '--signer <SIGNER>': xdr value invalid
$ stellar tx new set-options --signer sponsor --signer-weight=20 --build-only
AAAAAgAAAACkBZuRlmsx0id9DepMyDU50OLurzdOysfTio7sxz6HzwAAAGQAANJ2AAAAAwAAAAAAAAAAAAAAAQAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAIogPEBhv4JY/n4BwiL6KsNVbNk/LyVwhverKE31ymPPAAAAFAAAAAAAAAAA
```
Fix #2214.
N/A
> Add support for identities as signer on `tx new set-options`.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/mod.rs
- cmd/soroban-cli/src/commands/snapshot/create.rs
- cmd/soroban-cli/src/print.rs
#2198
So we have a better snapshot representation.
N/A
> Fetch snapshot values dynamically rather than hardcoding them.

- FULL_HELP_DOCS.md
- cmd/crates/soroban-test/tests/it/integration.rs
- cmd/crates/soroban-test/tests/it/integration/contract/fetch.rs
- cmd/crates/soroban-test/tests/it/integration/contract/mod.rs
- cmd/soroban-cli/src/commands/contract/fetch.rs
- cmd/soroban-cli/src/wasm.rs
Support fetch contract wasm using a hash instead of contract ID. Add new --wasm-hash argument to contract fetch command.
Enable fetching WASM files directly by their content hash for faster deployment and verification. Support hash-based retrieval alongside existing ID-based approach.
Close #2223
> Add WASM fetch by hash support

- cmd/soroban-cli/src/commands/contract/build.rs
Closes https://github.com/stellar/stellar-cli/issues/1721
Before
```
> stellar contract build --manifest-path ./cmd/crates/soroban-test/tests/fixtures/test-wasms/test/Cargo.toml --meta one=two --meta three=four
> wasm-tools print target/wasm32v1-none/release/test.wasm
...
(@producers
(language "Rust" "")
(processed-by "rustc" "1.89.0 (29483883e 2025-08-04)")
)
(@custom "target_features" (after data) "\01+\0fmutable-globals")
(@custom "contractmetav0" (after data) "\00\00\00\00\00\00\00\03one\00\00\00\00\03two\00")
(@custom "contractmetav0" (after data) "\00\00\00\00\00\00\00\05three\00\00\00\00\00\00\04four")
)
```
After
```
> cargo run contract build --manifest-path ./cmd/crates/soroban-test/tests/fixtures/test-wasms/test/Cargo.toml --meta one=two --meta three=four
> wasm-tools print …
```
> Append custom meta entries in one section

- .cargo-husky/hooks/pre-commit
- .cargo-husky/hooks/pre-push
- .github/copilot-instructions.md
- .github/workflows/docs.yml
- .github/workflows/rust.yml
- CONTRIBUTING.md
- FULL_HELP_DOCS.md
- Makefile
- README.md
- cmd/crates/soroban-spec-typescript/README.md
- cmd/crates/soroban-spec-typescript/ts-tests/README.md
- cmd/crates/soroban-test/README.md
- cmd/crates/soroban-test/tests/fixtures/workspace/README.md
- cmd/soroban-cli/src/utils/contract-workspace-template/README.md
- cookbook/asset-management.mdx
- cookbook/contract-lifecycle.mdx
- cookbook/deploy-contract.mdx
- cookbook/extend-contract-storage.mdx
- cookbook/extend-contract-wasm.mdx
- cookbook/install-wasm.mdx
- cookbook/payments-and-assets.mdx
- cookbook/restore-contract-storage.mdx
- cookbook/tx-new-create-claimable-balance.mdx
- cookbook/tx-new.mdx
- cookbook/tx-op-add.mdx
- cookbook/tx-sign.mdx
- package-lock.json
- package.json
- prettier.config.js
Change some of the documentation links in the cookbook files.
We're currently in the process of moving the cookbook files in the docs site closer to the CLI manual (stellar/stellar-docs#1834). These links will then be incorrect, and could cause the docs build to fail.
I've replaced full URLS (`https://developers.stellar.org/docs/path/whatever`) with relative URLs (`../path/whatever`) anywhere i saw it in the cookbook files. (commit 423c46a for reference). I could definitely see some benefit to having them as full URLs here in the CLI repo, though. So, if it'd be better, i can revert that change and change any other relative URLs to full URLs.
I've also run these cookbook files through the same markdown linter/formatter we use in the docs, just to get the styles consistent.
To test this …
> change cookbook docs links

- cmd/soroban-cli/src/commands/doctor.rs
- cmd/soroban-cli/src/print.rs
```console
$ stellar doctor
✅ You are using the latest version of Stellar CLI: 23.1.4
ℹ️ Rust version: 1.89.0
✅ Rust target `wasm32v1-none` is installed
⚙️ Config directory: /Users/fnando/.config/stellar
📁 Data directory: /Users/fnando/.local/share/stellar-cli
ℹ️ XDR version: 4b7a2ef7931ab2ca2499be68d849f38190b443ca
🌎 Default network "local" (http://localhost:8000/rpc)
protocol 23
rpc f225766c37ffa46b7e456054280f973ecb19b07
🌎 Default network "futurenet" (https://rpc-futurenet.stellar.org:443)
protocol 23
rpc 23.0.4-7c2b6f34c6b5f953d574e1b4f0ca0cf4ee78cf97
🌎 Default network "testnet" (https://soroban-testnet.stellar.org)
protocol 23
rpc 23.0.4-7c2b6f34c6b5f953d574e1b4f0ca0cf4ee78cf97
🌎 Network "dev" (http://localhost:8000/rpc)
protocol 23
rpc f225766c37ffa46b7e456054280f973ecb19b07
🌎 …
```
> Add data dir to `stellar doctor`.

- cmd/soroban-cli/src/commands/snapshot/create.rs
```console
$ truncate -s 0 /Users/fnando/.local/share/stellar-cli/bucket/bucket-f10cc0c81fcea299e9fe0806d0921d086362a1b11c8757b236468deb1abc97fe.xdr
$ stellar snapshot create --network pubnet --address CATRNPHYKNXAPNLHEYH55REB6YSAJLGCPA4YM6L3WUKSZOPI77M2UMKI --output json --out /tmp/sorobandomains.json
🌎 Downloading history https://history.stellar.org/prd/core-live/core_live_001/.well-known
🌎 Downloaded history https://history.stellar.org/prd/core-live/core_live_001/.well-known/stellar-history.json
ℹ️ Ledger: 59262079
ℹ️ Network Passphrase: Public Global Stellar Network ; September 2015
ℹ️ Network id: 7ac33997544e3175d266bd022439b22cdb16508c01163f26e5cb2a3e1045a979
🌎 Downloading ledger headers https://history.stellar.org/prd/core-live/core_live_001/ledg
🌎 Downloaded ledger headers for …
```
> Ensure snapshot's bucket cache is not corrupted.

- FULL_HELP_DOCS.md
- cmd/soroban-cli/src/commands/contract/build.rs
- cmd/soroban-cli/src/commands/contract/mod.rs
- cmd/soroban-cli/src/commands/contract/optimize.rs
- cmd/soroban-cli/src/print.rs
- licenses.rb
```console
$ stellar contract build --optimize
ℹ️ CARGO_BUILD_RUSTFLAGS=--remap-path-prefix=/Users/fnando/.cargo/registry/src= cargo rustc --manifest-path=contracts/foo/Cargo.toml --crate-type=cdylib --target=wasm32v1-none --release
Finished `release` profile [optimized] target(s) in 0.04s
ℹ️ Build Summary:
Wasm File: target/wasm32v1-none/release/foo.wasm (537 bytes (original size was 574 bytes))
Wasm Hash: 9276bc278792b46e89b299bb55beffd6ca2fa2d17d723abe1ec615e6d5752485
Wasm Size: 537 bytes optimized (original size was 574 bytes)
Exported Functions: 2 found
• _
• hello
✅ Build Complete
$ stellar contract build
ℹ️ CARGO_BUILD_RUSTFLAGS=--remap-path-prefix=/Users/fnando/.cargo/registry/src= cargo rustc --manifest-path=contracts/foo/Cargo.toml --crate-type=cdylib --target=wasm32v1-none …
```
> Deprecate `stellar contract optimize` in favor of `stellar contract build --optimize`.
