stellar/stellar-cli

src/inspect.rs
src/invoke.rs
src/main.rs
src/version.rs

Add interface version to version subcommand.
Close https://github.com/stellar/stellar-contract-cli/issues/37
[TODO or N/A]

Add interface version to version subcommand

---

Cargo.lock
Cargo.toml
README.md
src/deploy.rs
src/inspect.rs
src/invoke.rs
src/snapshot.rs
src/strval.rs
src/utils.rs
src/version.rs

A big search and replace. As with previous repos, this will require a followup change to Cargo.toml once the repos are renamed.

rename crates to soroban

---

Cargo.lock
Cargo.toml
Makefile
README.md

Release prep

---

Cargo.lock
Cargo.toml
src/strval.rs

Support G- strkey public keys as arguments

---

src/gen.rs

Add scaffolding for adding additional code gen types.
So that it is clearer how we can add JSON, TypeScript and other code generation to the CLI.

Add scaffolding for adding additional code gen types

---

Cargo.lock
Cargo.toml
src/deploy.rs
src/invoke.rs
src/serve.rs
src/snapshot.rs

Update the `cli serve` api
To match the new API design, and also include `footprint` and `cost` fields for `simulateTransaction`.
Follow-up from https://github.com/stellar/soroban-cli/issues/58 and https://github.com/stellar/soroban-cli/issues/78
- General parsing, validation, and return values are all pretty janky for now. I've left `TODO` where there is obvious work needed.

Update cli serve api

---

Cargo.lock
Cargo.toml
src/main.rs
src/network.rs
src/read.rs
src/serve.rs

Add sendTransaction, getTransactionStatus, and getContractData methods
Fixes #59, and #60
[TODO or N/A]

Add sendTransaction, getTransactionStatus, and getContractData methods

---

Cargo.lock
Cargo.toml

Update stellar-xdr, soroban-env-*, soroban-spec.
cc @2opremio

Update stellar-xdr, soroban-env-*, soroban-spec

---

src/serve.rs

I noticed a couple small inconsistencies while I was writing the API docs.
This is more consistent in capitalization, and between methods.
[TODO or N/A]

Fix up a couple discrepancies from the api docs

---

src/serve.rs

Add CORS headers to cli serve.
This allows webapps running on a different domain (or port) to query it. This is helpful for local development.
Fixes #93 
We should allow user to make this stricter when deploying soroban-rpc for production use.

Add cors support to cli serve

---

Cargo.lock
Cargo.toml

Update stellar-xdr, soroban-env-*, soroban-sdk.

Update stellar-xdr, soroban-env-*, soroban-sdk

---

src/read.rs

Make read accept strval or xdr, and output strval, json, or xdr.
To make it easier to use, and to include its use in examples.

Make read accept strval or xdr, and output strval, json, or xdr

---

Cargo.lock
Cargo.toml

Update dependencies for release.

Update dependencies for release

---

Cargo.lock
Cargo.toml

Update soroban-spec, stellar-strkey, soroban-env-*, soroban-wasmi.

Update soroban-spec, stellar-strkey, soroban-env-*, soroban-wasmi

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/strval.rs

Update stellar-xdr, soroban-env, soroban-spec.
Mostly to get the latest soroban-spec definitions that support integer enums.
Close https://github.com/stellar/rs-soroban-sdk/issues/217

Update stellar-xdr, soroban-env, soroban-spec

---

Cargo.lock
Cargo.toml

Update soroban-env, soroban-spec, stellar-xdr.

Update soroban-env, soroban-spec, stellar-xdr

---

Cargo.lock
Cargo.toml
src/invoke.rs

Support debug logs
Related to https://github.com/stellar/rs-soroban-env/pull/464

Support debug logs

---

Cargo.lock
Cargo.toml
src/gen.rs
src/invoke.rs
src/strval.rs

Add support for account as invoker auth.
Close #153

Support account id auth

---

Cargo.lock
Cargo.toml
src/main.rs
src/xdr.rs
src/xdr/decode.rs

Add xdr subcommand for decoding xdr
Debugging the new XDR is inconvenient without something like this.

Add xdr subcommand for decoding xdr

---

Cargo.lock
Cargo.toml
src/invoke.rs
src/serve.rs

Update soroban-spec, soroban-env, stellar-xdr.

Update soroban-spec, soroban-env, stellar-xdr

---

Cargo.lock
Cargo.toml
src/invoke.rs
src/read.rs
src/serve.rs

Update stellar-xdr, soroban-spec, soroban-env

Update stellar-xdr, soroban-spec, soroban-env

---

src/serve.rs

Change footprint in serve responses to be the base64 of the LedgerFootprint XDR type, instead of a JSON structure containing arrays of items.
-

Change footprint in serve responses to use xdr

---

src/deploy.rs
src/invoke.rs
src/token/create.rs
src/token/wrap.rs
src/utils.rs

Rename private-strkey to secret-key.
Consistency across commands.
Close https://github.com/stellar/soroban-cli/issues/189

Rename private-strkey to secret-key

---

src/deploy.rs
src/invoke.rs
src/read.rs
src/serve.rs
src/token/create.rs
src/token/wrap.rs

- Fixing a typo in cli flags
- Adding env vars for all network config flags

Add env vars for network config flags

---

src/rpc/mod.rs

Inspect and use the error field from the `simulateTransaction` response.
Close #191 
#191 
N/A

Inspect and use the error from simulateTransaction

---

src/deploy.rs
src/invoke.rs

Reorder options in commands.
So they're consistent.

Reorder options in commands

---

Cargo.lock
Cargo.toml

Update soroban-spec, soroban-env, stellar-strkey, etc.
Preparing for release.

Update soroban-spec, soroban-env, stellar-strkey, etc

---

src/invoke.rs

Improve error when invoking a token contract and no wasm is passed to `missing token contract code, please pass it through the --wasm flag`
We we should really do is get the contract spec from `soroban-env-host` but, AFAIK, it doesn't expose it.
The error used to be: `error: unexpected contract code data type: Object(Some(ContractCode(Token)))`, which is much worse.
N/A

invoke: Improve error when invoking a token contract and no wasm is passed

---

Cargo.lock
Cargo.toml
src/inspect.rs
src/strval.rs

Update deps and get BytesM/StringM
See stellar/xdrgen#143
Close https://github.com/stellar/xdrgen/issues/125 
Close https://github.com/stellar/xdrgen/issues/119 
Close https://github.com/stellar/xdrgen/issues/118

Update deps and get BytesM/StringM

---

src/optimize.rs

Enable converge on wasm-opt optimization
https://github.com/stellar/soroban-cli/pull/236#issuecomment-1297325311

Enable converge on wasm-opt optimization

---

.github/workflows/soroban-rpc.yml

changed core version to latest build to be used in tests
verify test coverage against most recent soroban core release candidate build

updated soroban core version for integration tests

---

README.md
cmd/soroban-cli/README.md

- Add a readme to soroban-cli so rust can publish: https://github.com/stellar/soroban-tools/actions/runs/3631215259/jobs/6125551822
- Add a readme to the root so there is at least something there.

Fix up readmes to fix up rust publish

---

.github/workflows/publish.yml

Same as #301, but for the publish workflow

Fix apt-get install in publish workflow

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
README.md

Add GitHub linting for GO code
Better code, less bugs.
N/A

Add GitHub linting for GO code

---

Cargo.lock
Cargo.toml
cmd/soroban-cli/src/deploy.rs
cmd/soroban-cli/src/install.rs
cmd/soroban-cli/src/invoke.rs
cmd/soroban-cli/src/serve.rs
cmd/soroban-cli/src/strval.rs
cmd/soroban-cli/src/token/wrap.rs
cmd/soroban-cli/src/utils.rs
cmd/soroban-cli/tests/it/invoke_sandbox.rs

update rust dependencies
it's time.
N/A

soroban-cli: update rust dependencies

---

cmd/soroban-cli/README.md

updated the example in cli README to reflect new dynamic named fn args on invoke.

updated readme for fn args example

---

cmd/soroban-rpc/internal/config/config.go
cmd/soroban-rpc/internal/jsonrpc.go
cmd/soroban-rpc/internal/methods/health.go
cmd/soroban-rpc/internal/test/integration.go
cmd/soroban-rpc/main.go

soroban-rpc: set a maximum ledger latency in /health method

---

cmd/soroban-cli/src/strval.rs

Added new Errors
So that users get a proper error message.
[TODO or N/A]

fix(CLI): Add new errors to replace placeholder `Unknown`

---

cmd/soroban-rpc/internal/test/simulate_transaction_test.go

Fix test compilation error introduced in #516

soroban-rpc: Fix test compilation problem from #516

---

cmd/soroban-rpc/internal/methods/get_events.go
cmd/soroban-rpc/internal/methods/get_events_test.go

Add support for diagnostic events filtering in the  `getEvents` method
Closes https://github.com/stellar/soroban-tools/issues/473
N/A

soroban-rpc: Add filtering support for diagnostic events

---

cmd/soroban-rpc/internal/daemon/daemon.go
cmd/soroban-rpc/internal/ingest/service.go
cmd/soroban-rpc/internal/jsonrpc.go
cmd/soroban-rpc/internal/preflight/preflight.go

Standarize logging output format. (e.g. always start logs in lowercase, use an error field)
#497 
N/A

soroban-rpc: standarize logging output format

---

cmd/soroban-rpc/internal/daemon/daemon.go

Remove unused methods from the daemon
Cleanup!
N/A

soroban-rpc: Minor daemon cleanup

---

.github/workflows/soroban-rpc.yml
cmd/soroban-cli/src/commands/contract/inspect.rs
cmd/soroban-cli/src/wasm.rs

merge soroban cli inspect from main
merge soroban cli inspect from main
N/A

port: merge soroban cli inspect from main

---

.github/workflows/soroban-rpc.yml
cmd/soroban-rpc/internal/test/docker-compose.yml
go.mod
go.sum

update build dependencies to include the latests go monorepo + latest core image.
bind correctly before release.
n/a

build: update build dependencies

---

.github/workflows/e2e.yml

updating the component version refs on e2e to what's available for preview 9
see what e2e tests are passing/failing

e2e for preview9

---

cmd/soroban-cli/src/commands/contract/invoke.rs

Allow parsing Contract Addresses
Part of the move from Bytes<32> to Address anywhere a contract id is used.
[TODO or N/A]

fix(CLI): contract id parsing

---

Cargo.lock
cmd/crates/soroban-test/Cargo.toml
cmd/crates/soroban-test/tests/it/invoke_sandbox.rs
cmd/soroban-cli/src/commands/config/network/ls.rs
cmd/soroban-cli/src/commands/contract/fetch.rs
cmd/soroban-cli/src/commands/contract/inspect.rs
cmd/soroban-cli/src/commands/contract/invoke.rs
cmd/soroban-cli/src/commands/contract/mod.rs
cmd/soroban-cli/src/rpc/mod.rs
cmd/soroban-cli/src/utils.rs
cmd/soroban-cli/src/utils/contract_spec.rs
cmd/soroban-cli/src/wasm.rs
docs/soroban-cli-full-docs.md

Downloads the bytes of a contract. Print to stdout or write to a file
Other commands already do this so it would best to implement it once and it's handy for build tools.
[TODO or N/A]

feat(CLI): contract fetch

---

.github/workflows/publish.yml
cmd/soroban-cli/Cargo.toml

Update #626 with main so we can merge it.
Closes #626

fix(CLI): revert taring published artifacts

---

.github/workflows/soroban-rpc.yml
Cargo.lock
Cargo.toml
cmd/crates/soroban-test/tests/fixtures/test-wasms/custom_type/src/lib.rs
cmd/crates/soroban-test/tests/fixtures/test-wasms/hello_world/src/lib.rs
cmd/crates/soroban-test/tests/fixtures/test-wasms/udt/src/lib.rs
cmd/soroban-rpc/internal/methods/simulate_transaction.go
cmd/soroban-rpc/internal/preflight/preflight.go
cmd/soroban-rpc/internal/test/docker-compose.yml
cmd/soroban-rpc/internal/test/get_ledger_entries_test.go
cmd/soroban-rpc/internal/test/get_ledger_entry_test.go
cmd/soroban-rpc/internal/test/simulate_transaction_test.go
cmd/soroban-rpc/lib/preflight.h
cmd/soroban-rpc/lib/preflight/src/lib.rs

Adapt Go and Rust code to the latest XDR changes
Needed for preview 10 release.
The `TestSimulateInvokeContractTransactionSuceeds` is failing with:
```
Error Trace:	/Users/fons/soroban-tools/cmd/soroban-rpc/internal/test/simulate_transaction_test.go:153
/Users/fons/soroban-tools/cmd/soroban-rpc/internal/test/simulate_transaction_test.go:336
Error:      	Should be empty, but was panic during preflight_host_function() call: recorded_auth_payload_to_xdr: address and nonce present independently (address: Some(Account(AccountId(PublicKeyTypeEd25519(Uint256(7376fde88e4cd61cc0fb294a1786b3f1d061f5f2f1ca57465faa932211b946d6))))), nonce: None)
```

soroban-rpc: Adapt Go and Rust code to the latest XDR changes

---

cmd/soroban-rpc/internal/db/ledgerentry_test.go

Fix the ledgerentry_test.go unit tests
I think they got missed when I merged https://github.com/stellar/soroban-tools/pull/724
Just gets the rpc unit tests passing

Fix ledgerentry tests for new xdr

---

cmd/soroban-cli/src/commands/lab/token/id.rs
cmd/soroban-cli/src/commands/lab/token/mod.rs
cmd/soroban-cli/src/commands/lab/token/wrap.rs
cmd/soroban-cli/src/utils.rs
docs/soroban-cli-full-docs.md
scripts/check-dependencies.bash

Quick one to merge main into soroban-xdr-next to keep it up to date.
https://github.com/stellar/soroban-tools/pull/693 introduced a conflict with the new preview10 changes.
[TODO or N/A]

Merge origin/main into soroban-xdr-next

---

.github/workflows/e2e.yml
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
cmd/crates/soroban-spec-typescript/src/project_template/package.json

Attempt to fix the e2e test.
This is an incomplete fix. There are other issues in the e2e that are beyond this fix.
Within this fix, I have:
1. updated system test version to 1.0.16.
2. changed the js-soroban-client to use 0.9.0 instead of the hashed version.
n/a

update e2e tests

---

.github/workflows/soroban-rpc.yml

fix CI bug in soroban-rpc testing
trivial fix.
n/a

fix CI bug in soroban-rpc testing

---

Makefile
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/cjs/index.js
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/esm/index.js
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/index.ts
cmd/crates/soroban-spec-typescript/src/wrapper.rs
cmd/crates/soroban-test/README.md
cmd/crates/soroban-test/src/lib.rs
cmd/crates/soroban-test/tests/fixtures/test-wasms/custom_type/src/lib.rs
cmd/crates/soroban-test/tests/it/custom_types.rs
cmd/deptool/analyze.go
cmd/deptool/scanner.go
docs/soroban-cli-full-docs.md

fix:js, go and md files

---

cmd/crates/soroban-spec-tools/src/lib.rs
cmd/soroban-cli/src/commands/contract/invoke.rs
cmd/soroban-cli/src/commands/contract/optimize.rs
cmd/soroban-cli/src/rpc/transaction.rs
cmd/soroban-rpc/lib/preflight/src/fees.rs
cmd/soroban-rpc/lib/preflight/src/lib.rs

Companion to https://github.com/stellar/rs-soroban-env/pull/979

Enable sign-ext and mutable-globals in use of wasm_opt

---

.github/workflows/dependency-check.yml

add rust dep checker
Verify we don't add references to commit hashes that would "disappear".
n/a

build: add rust dep checker

---

.github/workflows/soroban-rpc.yml
Cargo.lock
Cargo.toml
cmd/soroban-rpc/internal/test/docker-compose.yml
cmd/soroban-rpc/internal/test/simulate_transaction_test.go

update core dependencies 9/5/2023
fons fixed a bug in env. Core dependencies need to be updated to reflect that.
n/a

build: update core dependencies

---

cmd/soroban-rpc/internal/test/cli_test.go
cmd/soroban-rpc/internal/test/integration.go
cmd/soroban-rpc/internal/test/simulate_transaction_test.go

Add a few more basic CLI integration tests

---

.github/workflows/dependency-check.yml
scripts/check-dependencies.bash

https://github.com/stellar/soroban-tools/pull/912 broke it two weeks ago and it wasn't noticed :S

Fix dependency checker GitHub workflow

---

cmd/soroban-cli/src/rpc/mod.rs
cmd/soroban-cli/src/utils/contract_spec.rs

Reverts stellar/soroban-tools#950

Revert "cli: Remove explicit decoding depths"

---

cmd/soroban-cli/src/commands/contract/bump.rs
cmd/soroban-rpc/internal/test/cli_test.go
cmd/soroban-rpc/internal/test/simulate_transaction_test.go

Add integration tests which exercise the bump and restore commands against soroban-rpc.

cli: Add cli tests for bump and restore

---

cmd/soroban-rpc/internal/test/simulate_transaction_test.go

Unit test needs update.
creating false positive.
n/a

fix simulate-event rpc unit test

---

cmd/soroban-rpc/internal/config/config.go
cmd/soroban-rpc/internal/config/options.go
cmd/soroban-rpc/internal/daemon/daemon.go
cmd/soroban-rpc/internal/preflight/pool.go
cmd/soroban-rpc/internal/preflight/preflight.go
cmd/soroban-rpc/internal/preflight/preflight_test.go
cmd/soroban-rpc/internal/test/integration.go
cmd/soroban-rpc/lib/preflight.h
cmd/soroban-rpc/lib/preflight/src/lib.rs
cmd/soroban-rpc/lib/preflight/src/preflight.rs
go.mod

rpc: add commandline flag to parameterize (opt-in) preflight debug info

---

cmd/crates/soroban-test/tests/it/integration.rs
cmd/crates/soroban-test/tests/it/integration/wrap.rs

chore: add burn test

---

cmd/soroban-rpc/lib/preflight/src/fees.rs

800k was actually not sufficient. I had to bump the fudge factor to 1 million to get all the tests to pass

soroban-rpc: fix comment about fees fudge factor

---

.github/workflows/e2e.yml

cherry pick v20 e2e config updates into v20.0.2 hotfix
assert test coverage on hot fix

Stable e2e

---

Cargo.lock
Cargo.toml

Update soroban-env-*, soroban-sdk-*
Keep the CLI updated and get it ready for release.

Update soroban-env-*, soroban-sdk-*

---

.github/workflows/soroban-rpc.yml
cmd/soroban-rpc/internal/test/docker-compose.yml

Update soroban-rpc integration tests to use latest core build.

soroban-rpc: Update core build

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
cmd/crates/soroban-spec-tools/Cargo.toml
cmd/crates/soroban-spec-tools/README.md
cmd/crates/soroban-spec-tools/src/contract.rs
cmd/crates/soroban-spec-tools/src/lib.rs
cmd/crates/soroban-spec-tools/src/utils.rs

Add soroban-spec-tools.
Part of moving the crate back to this repo.
Related:
- https://github.com/stellar/soroban-rpc/pull/80

Add soroban-spec-tools

---

cmd/crates/soroban-spec-typescript/src/project_template/package.json

Update dependencies used by the TypeScript bindings.
Freighter, especially, has a new version with breaking changes.
[TODO or N/A]

feat(ts-bindings): update freighter and stellar-sdk

---

cmd/soroban-cli/src/commands/config/locator.rs
cmd/soroban-cli/src/commands/config/secret.rs

Fix typos.

---

.gitignore

Ignore test snapshots.
So we don't risk adding those by accident.
N/A

Ignore test snapshots.

---

cmd/crates/soroban-test/tests/fixtures/test-wasms/token/src/test.rs

Fix issue of a function over 100 lines.
Make clippy happy
[TODO or N/A]

fix: clippy in ft tests

---

cmd/soroban-cli/README.md
cmd/stellar-cli/README.md

Self explanatory. Link has a typo.

Update README.md typo

---

CONTRIBUTING.md
README.md

Rename stellar-cli in README.md and CONTRIBUTING.md

Rename to stellar-cli

---

Cargo.lock
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package.json
cmd/crates/soroban-spec-typescript/src/project_template/package.json
cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
cmd/crates/soroban-spec-typescript/ts-tests/package.json

Lots of good stuff that we get in the latest version of stellar-sdk; see
[its release notes](https://github.com/stellar/js-stellar-sdk/releases/tag/v12.1.0)

feat(bindings): update js-stellar-sdk dependency

---

FULL_HELP_DOCS.md

these got out of date on the main branch

docs: update full docs

---

Cargo.lock
Cargo.toml

Update stellar-xdr, soroban-env-\*, soroban-sdk-\*, stellar-rpc-client.
Update the crates to get the latest xdr lib.

Update stellar-xdr, soroban-env-*, soroban-sdk-*, stellar-rpc-client

---

Cargo.lock
cmd/crates/soroban-test/tests/it/integration/hello_world.rs
cmd/soroban-cli/Cargo.toml
cmd/soroban-cli/src/commands/contract/deploy/asset.rs
cmd/soroban-cli/src/commands/contract/invoke.rs
cmd/soroban-cli/src/commands/keys/fund.rs
cmd/soroban-cli/src/fee.rs
cmd/soroban-cli/src/utils.rs

Reverts stellar/stellar-cli#1478
Friendbot supports top ups now as of:
- https://github.com/stellar/go/pull/5399

Revert "change fund to top off if balance below 10k xlm"

---

README.md

Update homebrew command

---

cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/index.d.ts
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/dist/index.js
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/package-lock.json
cmd/crates/soroban-spec-typescript/fixtures/test_custom_types/src/index.ts

Run `make build-snapshot`, commit the changes
I forgot to run `make build-snapshot` as part of https://github.com/stellar/stellar-cli/pull/1577
If you run `make build-snapshot` on `main` right now, you end up with these artifact changes.

fix: update snapshot fixtures

---

cmd/soroban-cli/src/print.rs

VScode and Apple Terminal doesn't work well with emojis that have 2 codepoints; in this case, we need to add an extra space, so it works properly.
Fix #1568 
So text alignment is consistent.
N/A

Handle emoji codepoint size for some not so great terminals.

---

.github/workflows/binaries.yml
.github/workflows/publish.yml

Install missing dependency. Depends on https://github.com/stellar/actions/pull/69.
https://github.com/stellar/stellar-cli/actions/runs/9798824274/job/27057923832#step:6:1731
N/A

Add libudev-dev as dep.

---

Cargo.toml
cmd/crates/soroban-test/tests/it/integration/tx.rs
cmd/crates/soroban-test/tests/it/plugin.rs

fix: bug in tx sign and send test

---

cmd/crates/soroban-test/tests/it/integration/util.rs

fix: add test to check if default is used for durability

---

cmd/crates/soroban-test/tests/it/integration/tx.rs
cmd/soroban-cli/src/assembled.rs
cmd/soroban-cli/src/commands/contract/deploy/asset.rs
cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
cmd/soroban-cli/src/commands/contract/extend.rs
cmd/soroban-cli/src/commands/contract/install.rs
cmd/soroban-cli/src/commands/contract/invoke.rs
cmd/soroban-cli/src/commands/tx/simulate.rs
cmd/soroban-cli/src/fee.rs
cmd/soroban-cli/src/lib.rs

Add Assembled from stellar/stellar-rpc-client@9f74833.
The type and related functionality is being moved into the cli repo.
See the following related issue for why:
- https://github.com/stellar/rs-stellar-rpc-client/pull/15

Add Assembled from stellar-rpc-client@9f74833

---

action.yml

Add GitHub Action for installing stellar-cli in GitHub CI.
To make installing and using the cli in GitHub more convenient.

Add GitHub Action for installing stellar-cli in repos

---

README.md
cmd/stellar-cli/README.md

Update install instructions to match stellar-docs
- https://github.com/stellar/stellar-docs/pull/1045

Update install instructions to match stellar-docs

---

cmd/soroban-cli/src/commands/global.rs
cmd/soroban-cli/src/commands/mod.rs
cmd/soroban-cli/src/config/locator.rs

Adds Options (Global)" heading to global options.

feat: add help headings for global command options

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/config/address.rs
cmd/soroban-cli/src/config/mod.rs

This reverts commit 9912694cfb6f67c4ccfbcba62a27aa22aa43cc17.

Revert "Resolve identity from default config. (#1711)"

---

.github/workflows/binaries.yml

We need to first upload the file, then issue the attestation.
So that it works.
N/A

Fix attestation order.

---

Cargo.lock

Update futures-util and co
The version we're using was yanked.

Update futures-util and co

---

cmd/soroban-cli/src/config/secret.rs

Generate 24-word keys instead of 12-word.
Close #1803

keys: generate 24-word keys

---

.github/workflows/binaries.yml

I moved paths around, but forgot to change this one path.
So it works.
N/A

Read correct path when uploading asset to release.

---

cmd/crates/soroban-spec-typescript/ts-tests/src/util.ts

Fix TS tests

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/commands/contract/deploy.rs
cmd/soroban-cli/src/commands/contract/deploy/asset.rs
cmd/soroban-cli/src/commands/contract/deploy/utils.rs
cmd/soroban-cli/src/commands/contract/deploy/wasm.rs

Add support for `--alias` on `contract asset deploy`. Close #1793
https://github.com/stellar/stellar-cli/issues/1793
N/A

Add support alias on `contract asset deploy`

---

cookbook/contract-lifecycle.mdx
cookbook/deploy-contract.mdx
cookbook/deploy-stellar-asset-contract.mdx
cookbook/extend-contract-instance.mdx
cookbook/extend-contract-storage.mdx
cookbook/extend-contract-wasm.mdx
cookbook/install-deploy.mdx
cookbook/install-wasm.mdx
cookbook/payments-and-assets.mdx
cookbook/restore-contract-instance.mdx
cookbook/restore-contract-storage.mdx
cookbook/tx-new.mdx
cookbook/tx-op-add.mdx
cookbook/tx-sign.mdx

Add custom edit url to all cookbook files.
Close #1608
N/A

Add custom edit url to all cookbook files.

---

cmd/soroban-cli/src/utils/contract-template/src/lib.rs

Add an explanatory comment to the generated file.
So users can have a better idea of what's being generated.
n/a

Add an explanatory comment to the generated file.

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/commands/container/logs.rs
cmd/soroban-cli/src/commands/container/start.rs
cmd/soroban-cli/src/commands/container/stop.rs

Set local network as the default for container commands.
Close #1848
N/A

Set local network as the default for container commands.

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/config/mod.rs
cmd/soroban-cli/src/config/network.rs

Add short flags for network and source account.
Close #794.
N/A

Add short flags for network and source account.

---

.github/workflows/bindings-ts.yml
.github/workflows/rpc-tests.yml
.github/workflows/rust.yml

Update apt in workflows

---

.github/workflows/binaries.yml

Generate json schema for TransactionEnvelope when building binaries
So we can use this with `stellar tx edit` for autocompletion.
N/A

Generate json schema.

---

cmd/crates/soroban-test/tests/it/integration/tx.rs
cmd/crates/soroban-test/tests/it/integration/util.rs
cmd/soroban-cli/src/commands/contract/deploy/asset.rs
cmd/soroban-cli/src/commands/contract/deploy/wasm.rs
cmd/soroban-cli/src/commands/contract/invoke.rs
cmd/soroban-cli/src/commands/contract/upload.rs
cmd/soroban-cli/src/fee.rs

Remove sim only flag
#1547 
N/A

Remove sim only flag

---

README.md

Update README to include installation for Github actions
Currently not very discoverable 
N/A

Update README to include installation for Github actions

---

.github/workflows/docs.yml

Adds a call to doc validation workflow added on stellar-docs side
#1908 
Depends on https://github.com/stellar/stellar-docs/pull/1460

Add docs validation workflow

---

.github/workflows/bindings-ts.yml

Enables TS bindings for linux and mac
Previously there have been some known issues leading to multiplatform failure caused by npm
This tests are only running multiplatform on merge to main, so should be low impact
N/A

[ci] TS bindings tests: support for Linux/Mac

---

README.md

Add Deepwiki integration
Deepwiki will auto refresh

Add Deepwiki integration 

---

cmd/soroban-cli/src/config/network.rs

Solves
https://github.com/stellar/stellar-cli/issues/2049

default to testnet  when no network specified

---

.github/workflows/bindings-ts.yml
cmd/crates/soroban-spec-typescript/src/project_template/package.json
cmd/crates/soroban-spec-typescript/ts-tests/initialize.sh
cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json
cmd/crates/soroban-spec-typescript/ts-tests/package.json

Update typescript bindings tests to use sdk@14.

---

cmd/soroban-cli/src/commands/keys/fund.rs
cmd/soroban-cli/src/commands/keys/generate.rs
cmd/soroban-cli/src/config/address.rs

Fix keyname display.

---

cmd/crates/soroban-spec-typescript/ts-tests/package-lock.json

Upgrade npm packages.
To fix npm vulnerabilities that only affect tests.
N/A

Upgrade npm packages.

---

FULL_HELP_DOCS.md
cmd/crates/soroban-test/tests/it/integration/tx/operations.rs
cmd/soroban-cli/src/commands/tx/help.rs
cmd/soroban-cli/src/commands/tx/new/create_claimable_balance.rs
cmd/soroban-cli/src/commands/tx/new/mod.rs
cookbook/tx-new-create-claimable-balance.mdx

```console
$ stellar tx new create-claimable-balance --amount 100000 --claimant default --build-only | stellar xdr decode --type TransactionEnvelope --output json-formatted
{
"tx": {
"tx": {
"source_account": "GDMHFOFH7IQSGGTIUYOUORZ3K2ZDP6PYNZDOL2AKSK7MRLPX5HF7DEA4",
"fee": 100,
"seq_num": "503258497941507",
"cond": "none",
"memo": "none",
"operations": [
{
"source_account": null,
"body": {
"create_claimable_balance": {
"asset": "native",
"amount": "100000",
"claimants": [
{
"claimant_type_v0": {
"destination": "GCNV6VMPZNHQTACVZC4AE75SJAFLHP7USOQWGE2HWMLXDKP6XOLGJR7S",
"predicate": "unconditional"
}
}
]
}
}
}
],
"ext": "v0"
},
"signatures": []
}
}
```
#2129
N/A

Add `stellar tx new create-claimable-balance`.

---

cookbook/deploy-contract.mdx

Update deploy-contract recipe to use alias

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/commands/tx/args.rs
cmd/soroban-cli/src/commands/tx/help.rs
cmd/soroban-cli/src/commands/tx/new/liquidity_pool_deposit.rs
cmd/soroban-cli/src/commands/tx/new/mod.rs
cmd/soroban-cli/src/commands/tx/op/add/liquidity_pool_deposit.rs
cmd/soroban-cli/src/commands/tx/op/add/mod.rs

Add two commands:
- `stellar tx new liquidity-pool-deposit`
- `stellar tx op add liquidity-pool-deposit`
#2129
N/A

Add `stellar tx new liquidity-pool-deposit` and `stellar tx op add liquidity-pool-deposit`.

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/commands/tx/help.rs
cmd/soroban-cli/src/commands/tx/new/liquidity_pool_withdraw.rs
cmd/soroban-cli/src/commands/tx/new/mod.rs
cmd/soroban-cli/src/commands/tx/op/add/liquidity_pool_withdraw.rs
cmd/soroban-cli/src/commands/tx/op/add/mod.rs

Add `stellar tx new liquidity-pool-withdraw` and `stellar tx op add liquidity-pool-withdraw`.
#2129
N/A

Add `stellar tx new liquidity-pool-withdraw` and `stellar tx op add liquidity-pool-withdraw`.

---

FULL_HELP_DOCS.md
cmd/soroban-cli/src/commands/contract/id/asset.rs

Clarify docs to include other asset formats.
